YOUR NAME's CS132 programs: TEST
TEST (fullInferenceCheck , testLabelOutput)
Test for inference module.
Tests that the number of bounding boxes returned are same as the ground truth.
Definition at line 74 of file DetectionTest.cpp.
References ImageInference::applyNMS(), ASSERT_EQ, ImageInference::getBoxes(), gmock_output_test::output, IOModule::readImage(), ImageInference::runForwardPass(), and ImageInference::setModelParams().
{
     ImageInference infer;
     IOModule iomodule;
     Mat image = iomodule.readImage("../data/testImage.jpg", false);
     infer.setModelParams();
     vector<Mat> finalLayerOut = infer.runForwardPass(image);
     infer.applyNMS(image, finalLayerOut);
     auto output = infer.getBoxes();
     uint8_t reqOutput = 1;
     ASSERT_EQ(output.size(), reqOutput);
 }