YOUR NAME's CS132 programs: TEST
TEST (frameTransformCheck , testShapeimgToCam)
Test for image to camera frame transformation method.
Tests the size of the output returned after transforming bounding box coordinates from image to camera frame.
Definition at line 44 of file FrameTransformTest.cpp.
References ImageInference::applyNMS(), ASSERT_EQ, ImageInference::getBoxes(), FrameTransform::getCoordsCam(), FrameTransform::imageToCamera(), gmock_output_test::output, IOModule::readImage(), ImageInference::runForwardPass(), and ImageInference::setModelParams().
{
     ImageInference infer;
     IOModule iomodule;
     FrameTransform ft;
     Mat image = iomodule.readImage("../data/testImage.jpg", false);
     infer.setModelParams();
     vector<Mat> finalLayerOut = infer.runForwardPass(image);
     infer.applyNMS(image, finalLayerOut);
     vector<cv::Rect> boxes = infer.getBoxes();
     ft.imageToCamera(boxes);
     Mat output = ft.getCoordsCam();
     uint8_t reqOutput = 3;
     ASSERT_EQ(output.rows, reqOutput);
 }