YOUR NAME's CS132 programs: TEST
TEST (camToBaseCheck , testShapeCamtoBase)
Test for camera to Base frame method.
Tests the output dimension returned after transforming bounding box coordinates from camera frame to robot's base frame.
Definition at line 64 of file FrameTransformTest.cpp.
References ImageInference::applyNMS(), ASSERT_EQ, FrameTransform::cameraToBase(), ImageInference::getBoxes(), FrameTransform::getCoords3D(), FrameTransform::getCoordsCam(), FrameTransform::imageToCamera(), gmock_output_test::output, IOModule::readImage(), ImageInference::runForwardPass(), and ImageInference::setModelParams().
{
     ImageInference infer;
     IOModule iomodule;
     FrameTransform ft;
     Mat image = iomodule.readImage("../data/testImage.jpg", false);
     infer.setModelParams();
     vector<Mat> finalLayerOut = infer.runForwardPass(image);
     infer.applyNMS(image, finalLayerOut);
     vector<cv::Rect> boxes = infer.getBoxes();
     ft.imageToCamera(boxes);
     Mat _output = ft.getCoordsCam();
     ft.cameraToBase();
     Mat output = ft.getCoords3D();
     uint8_t reqOutput = 4;
     ASSERT_EQ(output.rows, reqOutput);
 }