YOUR NAME's CS132 programs: TEST
TEST (checkInputRead , testInputRead)
Test for read methods.
Tests if the functions taking user inputs read data as required.
Definition at line 41 of file IOModuleTest.cpp.
References ASSERT_EQ, IOModule::readInputDir(), IOModule::readInputType(), IOModule::readOutputDir(), IOModule::returnCameraID(), IOModule::returnInputDir(), IOModule::returnInputType(), IOModule::returnOutputDir(), and IOModule::setCameraID().
{
     std::istringstream inputType("2");
     std::istringstream inputDir("../data/");
     std::istringstream outputDir("../data/");
     std::istringstream setID("0");
     IOModule ioHandler;
     ioHandler.readInputType(inputType);
     ioHandler.readInputDir(inputDir);
     ioHandler.readOutputDir(outputDir);
     ioHandler.setCameraID(setID);
     ASSERT_EQ(ioHandler.returnInputType(), 2);
     ASSERT_EQ(ioHandler.returnInputDir(), "../data/");
     ASSERT_EQ(ioHandler.returnOutputDir(), "../data/");
     ASSERT_EQ(ioHandler.returnCameraID(), 0);
 }