YOUR NAME's CS132 programs: testing::Test::TearDown
void Test::TearDown () protected virtual
Reimplemented in ProtectedFixtureMethodsTest, Predicate5Test, Predicate4Test, Predicate3Test, Predicate2Test, FatalFailureInSetUpTest, NonFatalFailureInSetUpTest, FatalFailureInFixtureConstructorTest, NonFatalFailureInFixtureConstructorTest, testing::internal::ListenerTest, Predicate1Test, CommonTest< T >, QuickTest, PropertyOne, and PropertyTwo.
Definition at line 2233 of file gtest.cc.
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), ProtectedFixtureMethodsTest::TearDown(), and testing::TEST_F().
                     {
 }