YOUR NAME's CS132 programs: testing::internal::TestResultAccessor::test_part_results
static const std::vector<testing::TestPartResult>& testing::internal::TestResultAccessor::test_part_results (const TestResult & test_result) inline static
Definition at line 1026 of file gtest-internal-inl.h.
References testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestPartResult::file_name(), GTEST_API_, GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, GTEST_LOG_, testing::TestPartResult::line_number(), testing::TestPartResult::message(), gtest_output_test::message, testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::Passed(), testing::UnitTest::Passed(), testing::TestInfo::result(), and testing::internal::StreamableToString().
{
     return test_result.test_part_results();
   }