YOUR NAME's CS132 programs: Interface::~Interface
virtual Interface::~Interface () inline virtual
Definition at line 193 of file gmock_link_test.h.
References IntFromString(), IntRefFromString(), StringFromString(), VoidFromDouble(), VoidFromFloat(), VoidFromFunc(), VoidFromIntRef(), VoidFromString(), and VoidFromVector().
 {}