YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3193 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), testing::UnitTest::elapsed_time(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), GTEST_FLAG, testing::UnitTest::Passed(), testing::UnitTest::reportable_disabled_test_count(), testing::internal::StreamableToString(), testing::UnitTest::successful_test_count(), testing::UnitTest::test_case_to_run_count(), and testing::UnitTest::test_to_run_count().
{
   ColoredPrintf(COLOR_GREEN,  "[==========] ");
   printf("%s from %s ran.",
          FormatTestCount(unit_test.test_to_run_count()).c_str(),
          FormatTestCaseCount(unit_test.test_case_to_run_count()).c_str());
   if (GTEST_FLAG(print_time)) {
     printf(" (%s ms total)",
            internal::StreamableToString(unit_test.elapsed_time()).c_str());
   }
   printf("\n");
   ColoredPrintf(COLOR_GREEN,  "[  PASSED  ] ");
   printf("%s.\n", FormatTestCount(unit_test.successful_test_count()).c_str());
   int num_failures = unit_test.failed_test_count();
   if (!unit_test.Passed()) {
     const int failed_test_count = unit_test.failed_test_count();
     ColoredPrintf(COLOR_RED,  "[  FAILED  ] ");
     printf("%s, listed below:\n", FormatTestCount(failed_test_count).c_str());
     PrintFailedTests(unit_test);
     printf("\n%2d FAILED %s\n", num_failures,
                         num_failures == 1 ? "TEST" : "TESTS");
   }
   int num_disabled = unit_test.reportable_disabled_test_count();
   if (num_disabled && !GTEST_FLAG(also_run_disabled_tests)) {
     if (!num_failures) {
       printf("\n");  // Add a spacer if no FAILURE banner is displayed.
     }
     ColoredPrintf(COLOR_YELLOW,
                   "  YOU HAVE %d DISABLED %s\n\n",
                   num_disabled,
                   num_disabled == 1 ? "TEST" : "TESTS");
   }
   // Ensure that Google Test output is printed before, e.g., heapchecker output.
   fflush(stdout);
 }