YOUR NAME's CS132 programs: gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration (self)
Definition at line 293 of file gtest_shuffle_test.py.
References gtest_shuffle_test.GetTestsForAllIterations(), gtest_shuffle_test.RandomSeedFlag(), gtest_shuffle_test.RepeatFlag(), and gtest_shuffle_test.ShuffleFlag().
   def testShuffleGeneratesNewOrderInEachIteration(self):
     [tests_in_iteration1, tests_in_iteration2, tests_in_iteration3] = (
         GetTestsForAllIterations(
             {}, [ShuffleFlag(), RandomSeedFlag(1), RepeatFlag(3)]))
     self.assert_(tests_in_iteration1 != tests_in_iteration2,
                  tests_in_iteration1)
     self.assert_(tests_in_iteration1 != tests_in_iteration3,
                  tests_in_iteration1)
     self.assert_(tests_in_iteration2 != tests_in_iteration3,
                  tests_in_iteration2)