YOUR NAME's CS132 programs: testing::internal::FilePath::CreateFolder
bool testing::internal::FilePath::CreateFolder () const
Definition at line 325 of file gtest-filepath.cc.
References c_str(), DirectoryExists(), and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively().
{
 #if GTEST_OS_WINDOWS_MOBILE
   FilePath removed_sep(this->RemoveTrailingPathSeparator());
   LPCWSTR unicode = String::AnsiToUtf16(removed_sep.c_str());
   int result = CreateDirectory(unicode, NULL) ? 0 : -1;
   delete [] unicode;
 #elif GTEST_OS_WINDOWS
   int result = _mkdir(pathname_.c_str());
 #else
   int result = mkdir(pathname_.c_str(), 0777);
 #endif  // GTEST_OS_WINDOWS_MOBILE
   if (result == -1) {
     return this->DirectoryExists();  // An error is OK if the directory exists.
   }
   return true;  // No error.
 }