YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::listeners
TestEventListeners* testing::internal::UnitTestImpl::listeners () inline
Definition at line 590 of file gtest-internal-inl.h.
Referenced by ConfigureXmlOutput(), PostFlagParsingInit(), RecordProperty(), testing::internal::DefaultGlobalTestPartResultReporter::ReportTestPartResult(), RunAllTests(), and UnitTestImpl().
 { return &listeners_; }