YOUR NAME's CS132 programs: MyString::Set
void MyString::Set (const char * c_string)
Definition at line 51 of file sample2.cc.
References CloneCString().
Referenced by Length(), MyString(), and TEST().
{
   // Makes sure this works when c_string == c_string_
   const char* const temp = MyString::CloneCString(a_c_string);
   delete[] c_string_;
   c_string_ = temp;
 }