YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd
void testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd (const TestCase & test_case) virtual
Implements testing::TestEventListener.
Definition at line 3149 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestCase::elapsed_time(), GTEST_FLAG, testing::TestCase::name(), testing::internal::StreamableToString(), and testing::TestCase::test_to_run_count().
{
   if (!GTEST_FLAG(print_time)) return;
   const std::string counts =
       FormatCountableNoun(test_case.test_to_run_count(), "test", "tests");
   ColoredPrintf(COLOR_GREEN, "[----------] ");
   printf("%s from %s (%s ms total)\n\n",
          counts.c_str(), test_case.name(),
          internal::StreamableToString(test_case.elapsed_time()).c_str());
   fflush(stdout);
 }