YOUR NAME's CS132 programs: gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition
def gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition (self)
Definition at line 305 of file gtest_shuffle_test.py.
References gtest_shuffle_test.GetTestsForAllIterations(), gtest_test_utils.Main(), gtest_shuffle_test.RandomSeedFlag(), and gtest_shuffle_test.ShuffleFlag().
   def testShuffleShardedTestsPreservesPartition(self):
     # If we run M tests on N shards, the same M tests should be run in
     # total, regardless of the random seeds used by the shards.
     [tests1] = GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                          SHARD_INDEX_ENV_VAR: '0'},
                                         [ShuffleFlag(), RandomSeedFlag(1)])
     [tests2] = GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                          SHARD_INDEX_ENV_VAR: '1'},
                                         [ShuffleFlag(), RandomSeedFlag(20)])
     [tests3] = GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                          SHARD_INDEX_ENV_VAR: '2'},
                                         [ShuffleFlag(), RandomSeedFlag(25)])
     sorted_sharded_tests = tests1 + tests2 + tests3
     sorted_sharded_tests.sort()
     sorted_active_tests = []
     sorted_active_tests.extend(ACTIVE_TESTS)
     sorted_active_tests.sort()
     self.assertEqual(sorted_active_tests, sorted_sharded_tests)