YOUR NAME's CS132 programs: gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride
def gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride (self)
Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT
Definition at line 109 of file gtest_env_var_test.py.
References gtest_env_var_test.AssertEq(), gtest_env_var_test.GetFlag(), gtest_test_utils.Main(), and gtest_env_var_test.SetEnvVar().
   def testXmlOutputFileOverride(self):
     """Tests that $XML_OUTPUT_FILE is overridden by $GTEST_OUTPUT"""
     SetEnvVar('GTEST_OUTPUT', 'xml:tmp/foo.xml')
     SetEnvVar('XML_OUTPUT_FILE', 'tmp/bar.xml')
     AssertEq('xml:tmp/foo.xml', GetFlag('output'))