YOUR NAME's CS132 programs: testing::internal::NativeArray::operator==
template<typename Element> bool testing::internal::NativeArray< Element >::operator== (const NativeArray< Element > & rhs) const inline
Definition at line 1065 of file gtest-internal.h.
References testing::internal::ArrayEq(), testing::internal::NativeArray< Element >::begin(), testing::internal::CopyArray(), GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_REFERENCE_AND_CONST_, and testing::internal::NativeArray< Element >::size().
{
     return size() == rhs.size() &&
         ArrayEq(begin(), size(), rhs.begin());
   }