YOUR NAME's CS132 programs: testing::internal::FilePath::FilePath
testing::internal::FilePath::FilePath () inline
Definition at line 61 of file gtest-filepath.h.
Referenced by ConcatPaths(), GetCurrentDir(), MakeFileName(), RemoveDirectoryName(), RemoveExtension(), RemoveFileName(), and RemoveTrailingPathSeparator().
 : pathname_("") { }