YOUR NAME's CS132 programs: testing::TestPartResult::type
Type testing::TestPartResult::type () const inline
Definition at line 72 of file gtest-test-part.h.
Referenced by testing::TestCase::GetTestInfo(), testing::internal::HasOneFailure(), testing::internal::PrettyUnitTestResultPrinter::OnTestPartResult(), and testing::operator<<().
 { return type_; }