YOUR NAME's CS132 programs: testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile
std::string testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile () static
Definition at line 426 of file gtest.cc.
References testing::internal::FilePath::ConcatPaths(), testing::internal::FilePath::GenerateUniqueFileName(), testing::internal::GetCurrentExecutableName(), testing::UnitTest::GetInstance(), GTEST_FLAG, testing::internal::FilePath::IsAbsolutePath(), testing::internal::FilePath::IsDirectory(), gmock_output_test::output, and testing::internal::FilePath::string().
Referenced by testing::internal::UnitTestImpl::ConfigureXmlOutput().
{
   const char* const gtest_output_flag = GTEST_FLAG(output).c_str();
   if (gtest_output_flag == NULL)
     return "";
   const char* const colon = strchr(gtest_output_flag, ':');
   if (colon == NULL)
     return internal::FilePath::ConcatPaths(
         internal::FilePath(
             UnitTest::GetInstance()->original_working_dir()),
         internal::FilePath(kDefaultOutputFile)).string();
   internal::FilePath output_name(colon + 1);
   if (!output_name.IsAbsolutePath())
     // TODO(wan@google.com): on Windows \some\path is not an absolute
     // path (as its meaning depends on the current drive), yet the
     // following logic for turning it into an absolute path is wrong.
     // Fix it.
     output_name = internal::FilePath::ConcatPaths(
         internal::FilePath(UnitTest::GetInstance()->original_working_dir()),
         internal::FilePath(colon + 1));
   if (!output_name.IsDirectory())
     return output_name.string();
   internal::FilePath result(internal::FilePath::GenerateUniqueFileName(
       output_name, internal::GetCurrentExecutableName(),
       GetOutputFormat().c_str()));
   return result.string();
 }