YOUR NAME's CS132 programs: testing::internal::TypedExpectation::After
template<typename F> TypedExpectation& testing::internal::TypedExpectation< F >::After (const ExpectationSet & s) inline
Definition at line 964 of file gmock-spec-builders.h.
References testing::ExpectationSet::begin(), and testing::ExpectationSet::end().
Referenced by testing::internal::TypedExpectation< F >::After().
{
     ExpectSpecProperty(last_clause_ <= kAfter,
                        ".After() cannot appear after .WillOnce(),"
                        " .WillRepeatedly(), or "
                        ".RetiresOnSaturation().");
     last_clause_ = kAfter;
     for (ExpectationSet::const_iterator it = s.begin(); it != s.end(); ++it) {
       immediate_prerequisites_ += *it;
     }
     return *this;
   }