YOUR NAME's CS132 programs: gtest_output_test.GTestOutputTest.RemoveUnsupportedTests
def gtest_output_test.GTestOutputTest.RemoveUnsupportedTests (self, test_output)
Definition at line 260 of file gtest_output_test.py.
References gtest_output_test.RemoveMatchingTests(), and gtest_output_test.RemoveStackTraces().
Referenced by gtest_output_test.GTestOutputTest.testOutput().
   def RemoveUnsupportedTests(self, test_output):
     if not SUPPORTS_DEATH_TESTS:
       test_output = RemoveMatchingTests(test_output, 'DeathTest')
     if not SUPPORTS_TYPED_TESTS:
       test_output = RemoveMatchingTests(test_output, 'TypedTest')
       test_output = RemoveMatchingTests(test_output, 'TypedDeathTest')
       test_output = RemoveMatchingTests(test_output, 'TypeParamDeathTest')
     if not SUPPORTS_THREADS:
       test_output = RemoveMatchingTests(test_output,
                                         'ExpectFailureWithThreadsTest')
       test_output = RemoveMatchingTests(test_output,
                                         'ScopedFakeTestPartResultReporterTest')
       test_output = RemoveMatchingTests(test_output,
                                         'WorksConcurrently')
     if not SUPPORTS_STACK_TRACES:
       test_output = RemoveStackTraces(test_output)
     return test_output