YOUR NAME's CS132 programs: testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched
bool testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched (const ::std::vector< string > & element_printouts, const MatchMatrix & matrix, MatchResultListener * listener) const protected
Definition at line 444 of file gmock-matchers.cc.
References testing::internal::MatchMatrix::HasEdge(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), testing::internal::MatchMatrix::RhsSize(), and testing::MatchResultListener::stream().
{
   bool result = true;
   ::std::vector<char> element_matched(matrix.LhsSize(), 0);
   ::std::vector<char> matcher_matched(matrix.RhsSize(), 0);
   for (size_t ilhs = 0; ilhs < matrix.LhsSize(); ilhs++) {
     for (size_t irhs = 0; irhs < matrix.RhsSize(); irhs++) {
       char matched = matrix.HasEdge(ilhs, irhs);
       element_matched[ilhs] |= matched;
       matcher_matched[irhs] |= matched;
     }
   }
   {
     const char* sep =
         "where the following matchers don't match any elements:\n";
     for (size_t mi = 0; mi < matcher_matched.size(); ++mi) {
       if (matcher_matched[mi])
         continue;
       result = false;
       if (listener->IsInterested()) {
         *listener << sep << "matcher #" << mi << ": ";
         matcher_describers_[mi]->DescribeTo(listener->stream());
         sep = ",\n";
       }
     }
   }
   {
     const char* sep =
         "where the following elements don't match any matchers:\n";
     const char* outer_sep = "";
     if (!result) {
       outer_sep = "\nand ";
     }
     for (size_t ei = 0; ei < element_matched.size(); ++ei) {
       if (element_matched[ei])
         continue;
       result = false;
       if (listener->IsInterested()) {
         *listener << outer_sep << sep << "element #" << ei << ": "
                   << element_printouts[ei];
         sep = ",\n";
         outer_sep = "";
       }
     }
   }
   return result;
 }