YOUR NAME's CS132 programs: testing::InitGoogleTestTest::TestParsingFlags
template<typename CharType > static void testing::InitGoogleTestTest::TestParsingFlags (int argc1, const CharType ** argv1, int argc2, const CharType ** argv2, const Flags & expected, bool should_print_help) inline static protected
Definition at line 5660 of file gtest_unittest.cc.
References testing::internal::CaptureStdout(), EXPECT_EQ, EXPECT_PRED_FORMAT2, testing::internal::g_help_flag, testing::internal::GetCapturedStdout(), testing::IsNotSubstring(), testing::IsSubstring(), and testing::internal::ParseGoogleTestFlagsOnly().
{
     const bool saved_help_flag = ::testing::internal::g_help_flag;
     ::testing::internal::g_help_flag = false;
 #if GTEST_HAS_STREAM_REDIRECTION
     CaptureStdout();
 #endif
     // Parses the command line.
     internal::ParseGoogleTestFlagsOnly(&argc1, const_cast<CharType**>(argv1));
 #if GTEST_HAS_STREAM_REDIRECTION
     const std::string captured_stdout = GetCapturedStdout();
 #endif
     // Verifies the flag values.
     CheckFlags(expected);
     // Verifies that the recognized flags are removed from the command
     // line.
     AssertStringArrayEq(argc1 + 1, argv1, argc2 + 1, argv2);
     // ParseGoogleTestFlagsOnly should neither set g_help_flag nor print the
     // help message for the flags it recognizes.
     EXPECT_EQ(should_print_help, ::testing::internal::g_help_flag);
 #if GTEST_HAS_STREAM_REDIRECTION
     const char* const expected_help_fragment =
         "This program contains tests written using";
     if (should_print_help) {
       EXPECT_PRED_FORMAT2(IsSubstring, expected_help_fragment, captured_stdout);
     } else {
       EXPECT_PRED_FORMAT2(IsNotSubstring,
                           expected_help_fragment, captured_stdout);
     }
 #endif  // GTEST_HAS_STREAM_REDIRECTION
     ::testing::internal::g_help_flag = saved_help_flag;
   }