YOUR NAME's CS132 programs: testing::Message::GetString
std::string testing::Message::GetString () const
Definition at line 981 of file gtest.cc.
References testing::internal::scoped_ptr< T >::get(), and testing::internal::StringStreamToString().
Referenced by testing::internal::AppendUserMessage(), testing::ArrayAsVector(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::GetBoolAssertionFailureMessage(), testing::UnitTest::listeners(), testing::internal::MakeAndRegisterTestInfo(), Message(), testing::internal::EventRecordingListener::OnTestIterationEnd(), testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd(), SequenceTestingListener::OnTestIterationEnd(), testing::internal::EventRecordingListener::OnTestIterationStart(), testing::operator<<(), testing::AssertionResult::operator<<(), testing::internal::ParseInt32(), testing::internal::ReadEntireFile(), testing::Test::RecordProperty(), testing::internal::ReportFailureInUnknownLocation(), testing::internal::ShouldShard(), and TEST().
{
   return internal::StringStreamToString(ss_.get());
 }