YOUR NAME's CS132 programs: testing::TestCase::total_test_count
int testing::TestCase::total_test_count () const
Definition at line 2707 of file gtest.cc.
Referenced by testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::UnitTestHelper::GetSortedTests(), GetTestInfo(), testing::TestInfoTest::GetTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::TEST(), and testing::internal::UnitTestImpl::total_test_count().
{
   return static_cast<int>(test_info_list_.size());
 }