YOUR NAME's CS132 programs: testing::internal::WhenSortedByMatcher::Impl::MatchAndExplain
template<typename Comparator, typename ContainerMatcher> template<typename LhsContainer > virtual bool testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2649 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       ::std::vector<LhsValue> sorted_container(lhs_stl_container.begin(),
                                                lhs_stl_container.end());
       ::std::sort(
            sorted_container.begin(), sorted_container.end(), comparator_);
       if (!listener->IsInterested()) {
         // If the listener is not interested, we do not need to
         // construct the inner explanation.
         return matcher_.Matches(sorted_container);
       }
       *listener << "which is ";
       UniversalPrint(sorted_container, listener->stream());
       *listener << " when sorted";
       StringMatchResultListener inner_listener;
       const bool match = matcher_.MatchAndExplain(sorted_container,
                                                   &inner_listener);
       PrintIfNotEmpty(inner_listener.str(), listener->stream());
       return match;
     }