YOUR NAME's CS132 programs: testing::UnitTest::GetInstance
UnitTest * testing::UnitTest::GetInstance () static
Definition at line 3972 of file gtest.cc.
Referenced by testing::AddGlobalTestEnvironment(), testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::TestCase::GetTestInfo(), testing::internal::GetUnitTestImpl(), testing::internal::Log(), main(), testing::internal::AssertHelper::operator=(), testing::Test::RecordProperty(), testing::internal::UnitTestImpl::RegisterParameterizedTests(), testing::internal::ReportFailureInUnknownLocation(), testing::internal::ScopedTrace::ScopedTrace(), testing::CurrentTestInfoTest::SetUpTestCase(), testing::internal::FinalSuccessChecker::TearDown(), testing::CurrentTestInfoTest::TearDownTestCase(), testing::internal::TEST(), TEST(), testing::TEST_F(), and testing::internal::ScopedTrace::~ScopedTrace().
{
   // When compiled with MSVC 7.1 in optimized mode, destroying the
   // UnitTest object upon exiting the program messes up the exit code,
   // causing successful tests to appear failed.  We have to use a
   // different implementation in this case to bypass the compiler bug.
   // This implementation makes the compiler happy, at the cost of
   // leaking the UnitTest object.
   // CodeGear C++Builder insists on a public destructor for the
   // default implementation.  Use this implementation to keep good OO
   // design with private destructor.
 #if (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
   static UnitTest* const instance = new UnitTest;
   return instance;
 #else
   static UnitTest instance;
   return &instance;
 #endif  // (_MSC_VER == 1310 && !defined(_DEBUG)) || defined(__BORLANDC__)
 }