YOUR NAME's CS132 programs: testing::internal::UnitTestHelper::GetSortedTests
static TestInfo const** testing::internal::UnitTestHelper::GetSortedTests (const TestCase * test_case) inline static
Definition at line 86 of file gtest-unittest-api_test.cc.
References testing::gmock_generated_actions_test::Dummy(), testing::TestCase::GetTestInfo(), testing::internal::kTypedTestCases, testing::internal::kTypedTests, testing::TestCase::total_test_count(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
{
     TestInfo const** const tests =
         new const TestInfo*[test_case->total_test_count()];
     for (int i = 0; i < test_case->total_test_count(); ++i)
       tests[i] = test_case->GetTestInfo(i);
     std::sort(tests, tests + test_case->total_test_count(),
               LessByName<TestInfo>());
     return tests;
   }