YOUR NAME's CS132 programs: testing::internal::PairMatcherImpl::MatchAndExplain
template<typename PairType > virtual bool testing::internal::PairMatcherImpl< PairType >::MatchAndExplain (PairType a_pair, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< PairType >.
Definition at line 3033 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     if (!listener->IsInterested()) {
       // If the listener is not interested, we don't need to construct the
       // explanation.
       return first_matcher_.Matches(a_pair.first) &&
              second_matcher_.Matches(a_pair.second);
     }
     StringMatchResultListener first_inner_listener;
     if (!first_matcher_.MatchAndExplain(a_pair.first,
                                         &first_inner_listener)) {
       *listener << "whose first field does not match";
       PrintIfNotEmpty(first_inner_listener.str(), listener->stream());
       return false;
     }
     StringMatchResultListener second_inner_listener;
     if (!second_matcher_.MatchAndExplain(a_pair.second,
                                          &second_inner_listener)) {
       *listener << "whose second field does not match";
       PrintIfNotEmpty(second_inner_listener.str(), listener->stream());
       return false;
     }
     ExplainSuccess(first_inner_listener.str(), second_inner_listener.str(),
                    listener);
     return true;
   }