YOUR NAME's CS132 programs: testing::internal::ExpectationBase::CheckActionCountIfNotDone
void testing::internal::ExpectationBase::CheckActionCountIfNotDone () const protected
Definition at line 173 of file gmock-spec-builders.cc.
References action_count_checked_, cardinality(), cardinality_specified_, testing::Cardinality::ConservativeLowerBound(), testing::Cardinality::ConservativeUpperBound(), DescribeLocationTo(), testing::Cardinality::DescribeTo(), testing::internal::kWarning, testing::internal::Log(), repeated_action_specified_, source_text(), and untyped_actions_.
{
   bool should_check = false;
   {
     MutexLock l(&mutex_);
     if (!action_count_checked_) {
       action_count_checked_ = true;
       should_check = true;
     }
   }
   if (should_check) {
     if (!cardinality_specified_) {
       // The cardinality was inferred - no need to check the action
       // count against it.
       return;
     }
     // The cardinality was explicitly specified.
     const int action_count = static_cast<int>(untyped_actions_.size());
     const int upper_bound = cardinality().ConservativeUpperBound();
     const int lower_bound = cardinality().ConservativeLowerBound();
     bool too_many;  // True if there are too many actions, or false
     // if there are too few.
     if (action_count > upper_bound ||
         (action_count == upper_bound && repeated_action_specified_)) {
       too_many = true;
     } else if (0 < action_count && action_count < lower_bound &&
                !repeated_action_specified_) {
       too_many = false;
     } else {
       return;
     }
     ::std::stringstream ss;
     DescribeLocationTo(&ss);
     ss << "Too " << (too_many ? "many" : "few")
        << " actions specified in " << source_text() << "...\n"
        << "Expected to be ";
     cardinality().DescribeTo(&ss);
     ss << ", but has " << (too_many ? "" : "only ")
        << action_count << " WillOnce()"
        << (action_count == 1 ? "" : "s");
     if (repeated_action_specified_) {
       ss << " and a WillRepeatedly()";
     }
     ss << ".";
     Log(kWarning, ss.str(), -1);  // -1 means "don't print stack trace".
   }
 }