YOUR NAME's CS132 programs: testing::internal::String::EndsWithCaseInsensitive
bool testing::internal::String::EndsWithCaseInsensitive (const std::string & str, const std::string & suffix) static
Definition at line 1949 of file gtest.cc.
References testing::internal::CaseInsensitiveCStringEquals().
Referenced by operator<<(), and testing::internal::FilePath::RemoveExtension().
{
   const size_t str_len = str.length();
   const size_t suffix_len = suffix.length();
   return (str_len >= suffix_len) &&
          CaseInsensitiveCStringEquals(str.c_str() + str_len - suffix_len,
                                       suffix.c_str());
 }