YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::ShuffleTests
void testing::internal::UnitTestImpl::ShuffleTests ()
Definition at line 4939 of file gtest.cc.
References random(), and testing::internal::ShuffleRange().
Referenced by RunAllTests().
{
   // Shuffles the death test cases.
   ShuffleRange(random(), 0, last_death_test_case_ + 1, &test_case_indices_);
   // Shuffles the non-death test cases.
   ShuffleRange(random(), last_death_test_case_ + 1,
                static_cast<int>(test_cases_.size()), &test_case_indices_);
   // Shuffles the tests inside each test case.
   for (size_t i = 0; i < test_cases_.size(); i++) {
     test_cases_[i]->ShuffleTests(random());
   }
 }