YOUR NAME's CS132 programs: testing::internal::PointeeMatcher::operator Matcher< Pointer >
template<typename InnerMatcher > template<typename Pointer > testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer > () const inline
Definition at line 2056 of file gmock-matchers.h.
References testing::internal::GetRawPointer(), GTEST_DISALLOW_ASSIGN_, GTEST_REMOVE_CONST_, GTEST_REMOVE_REFERENCE_, testing::MakeMatcher(), testing::internal::MatchPrintAndExplain(), testing::Pointee(), and upload::type.
{
     return MakeMatcher(new Impl<Pointer>(matcher_));
   }