YOUR NAME's CS132 programs: testing::UnitTest::listeners
TestEventListeners & testing::UnitTest::listeners ()
Definition at line 4081 of file gtest.cc.
References testing::internal::TraceInfo::file, testing::internal::FormatFileLocation(), testing::Message::GetString(), GTEST_FLAG, GTEST_LOCK_EXCLUDED_, GTEST_NAME_, testing::internal::kStackTraceMarker, testing::TestPartResult::kSuccess, testing::internal::TraceInfo::line, gtest_output_test::message, and testing::internal::TraceInfo::message.
Referenced by testing::TestCase::GetTestInfo(), main(), and testing::internal::UnitTestImpl::RegisterParameterizedTests().
{
   return *impl()->listeners();
 }