YOUR NAME's CS132 programs: testing::MatchResultListener::stream
::std::ostream* testing::MatchResultListener::stream () inline
Definition at line 98 of file gmock-matchers.h.
Referenced by testing::internal::FindPairing(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::gmock_matchers_test::NewEvenMatcherImpl::MatchAndExplain(), testing::gmock_matchers_test::PolymorphicIsEvenImpl::MatchAndExplain(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::ContainerEqMatcher< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl(), testing::internal::MatchPrintAndExplain(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return stream_; }