YOUR NAME's CS132 programs: testing::internal::FilePath::DirectoryExists
bool testing::internal::FilePath::DirectoryExists () const
Definition at line 223 of file gtest-filepath.cc.
References c_str(), testing::internal::posix::IsDir(), IsRootDirectory(), RemoveTrailingPathSeparator(), and testing::internal::posix::Stat().
Referenced by CreateDirectoriesRecursively(), and CreateFolder().
{
   bool result = false;
 #if GTEST_OS_WINDOWS
   // Don't strip off trailing separator if path is a root directory on
   // Windows (like "C:\\").
   const FilePath& path(IsRootDirectory() ? *this :
                                            RemoveTrailingPathSeparator());
 #else
   const FilePath& path(*this);
 #endif
 #if GTEST_OS_WINDOWS_MOBILE
   LPCWSTR unicode = String::AnsiToUtf16(path.c_str());
   const DWORD attributes = GetFileAttributes(unicode);
   delete [] unicode;
   if ((attributes != kInvalidFileAttributes) &&
       (attributes & FILE_ATTRIBUTE_DIRECTORY)) {
     result = true;
   }
 #else
   posix::StatStruct file_stat;
   result = posix::Stat(path.c_str(), &file_stat) == 0 &&
       posix::IsDir(file_stat);
 #endif  // GTEST_OS_WINDOWS_MOBILE
   return result;
 }