YOUR NAME's CS132 programs: upload.SubversionVCS.GetBaseFile
def upload.SubversionVCS.GetBaseFile (self, filename)
Definition at line 898 of file upload.py.
References upload.SubversionVCS._CollapseKeywords(), upload.SubversionVCS.GetBaseFile(), upload.SubversionVCS.GetStatus(), upload.VersionControlSystem.IsImage(), upload.SubversionVCS.ReadFile(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.RunShell(), upload.RunShellWithReturnCode(), upload.StatusUpdate(), and upload.SubversionVCS.svn_base.
   def GetBaseFile(self, filename):
     status = self.GetStatus(filename)
     base_content = None
     new_content = None
     # If a file is copied its status will be "A  +", which signifies
     # "addition-with-history".  See "svn st" for more information.  We need to
     # upload the original file or else diff parsing will fail if the file was
     # edited.
     if status[0] == "A" and status[3] != "+":
       # We'll need to upload the new content if we're adding a binary file
       # since diff's output won't contain it.
       mimetype = RunShell(["svn", "propget", "svn:mime-type", filename],
                           silent_ok=True)
       base_content = ""
       is_binary = mimetype and not mimetype.startswith("text/")
       if is_binary and self.IsImage(filename):
         new_content = self.ReadFile(filename)
     elif (status[0] in ("M", "D", "R") or
           (status[0] == "A" and status[3] == "+") or  # Copied file.
           (status[0] == " " and status[1] == "M")):  # Property change.
       args = []
       if self.options.revision:
         url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
       else:
         # Don't change filename, it's needed later.
         url = filename
         args += ["-r", "BASE"]
       cmd = ["svn"] + args + ["propget", "svn:mime-type", url]
       mimetype, returncode = RunShellWithReturnCode(cmd)
       if returncode:
         # File does not exist in the requested revision.
         # Reset mimetype, it contains an error message.
         mimetype = ""
       get_base = False
       is_binary = mimetype and not mimetype.startswith("text/")
       if status[0] == " ":
         # Empty base content just to force an upload.
         base_content = ""
       elif is_binary:
         if self.IsImage(filename):
           get_base = True
           if status[0] == "M":
             if not self.rev_end:
               new_content = self.ReadFile(filename)
             else:
               url = "%s/%s@%s" % (self.svn_base, filename, self.rev_end)
               new_content = RunShell(["svn", "cat", url],
                                      universal_newlines=True, silent_ok=True)
         else:
           base_content = ""
       else:
         get_base = True
       if get_base:
         if is_binary:
           universal_newlines = False
         else:
           universal_newlines = True
         if self.rev_start:
           # "svn cat -r REV delete_file.txt" doesn't work. cat requires
           # the full URL with "@REV" appended instead of using "-r" option.
           url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           base_content = RunShell(["svn", "cat", url],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         else:
           base_content = RunShell(["svn", "cat", filename],
                                   universal_newlines=universal_newlines,
                                   silent_ok=True)
         if not is_binary:
           args = []
           if self.rev_start:
             url = "%s/%s@%s" % (self.svn_base, filename, self.rev_start)
           else:
             url = filename
             args += ["-r", "BASE"]
           cmd = ["svn"] + args + ["propget", "svn:keywords", url]
           keywords, returncode = RunShellWithReturnCode(cmd)
           if keywords and not returncode:
             base_content = self._CollapseKeywords(base_content, keywords)
     else:
       StatusUpdate("svn status returned unexpected output: %s" % status)
       sys.exit(1)
     return base_content, new_content, is_binary, status[0:5]