YOUR NAME's CS132 programs: gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar
def gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar (self)
Tests that the filter flag overrides the filtering env. variable.
Definition at line 566 of file gtest_filter_unittest.py.
References gtest_filter_unittest.GTestFilterUnitTest.AssertSetEqual(), gtest_filter_unittest.RunAndExtractTestList(), and gtest_filter_unittest.SetEnvVar().
   def testFlagOverridesEnvVar(self):
     """Tests that the filter flag overrides the filtering env. variable."""
     SetEnvVar(FILTER_ENV_VAR, 'Foo*')
     args = ['--%s=%s' % (FILTER_FLAG, '*One')]
     tests_run = RunAndExtractTestList(args)[0]
     SetEnvVar(FILTER_ENV_VAR, None)
     self.AssertSetEqual(tests_run, ['BarTest.TestOne', 'BazTest.TestOne'])