YOUR NAME's CS132 programs: testing::internal::FilePath::ConcatPaths
FilePath testing::internal::FilePath::ConcatPaths (const FilePath & directory, const FilePath & relative_path) static
Definition at line 199 of file gtest-filepath.cc.
References FilePath(), IsEmpty(), RemoveTrailingPathSeparator(), and string().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and MakeFileName().
{
   if (directory.IsEmpty())
     return relative_path;
   const FilePath dir(directory.RemoveTrailingPathSeparator());
   return FilePath(dir.string() + kPathSeparator + relative_path.string());
 }