YOUR NAME's CS132 programs: testing::internal::linked_ptr::get
template<typename T> T* testing::internal::linked_ptr< T >::get () const inline
Definition at line 182 of file gtest-linked_ptr.h.
Referenced by testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator!=(), testing::internal::operator!=(), testing::internal::linked_ptr< const testing::MatcherInterface< const internal::string & > >::operator==(), and testing::internal::operator==().
 { return value_; }