YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::ConfigureXmlOutput
void testing::internal::UnitTestImpl::ConfigureXmlOutput ()
Definition at line 4400 of file gtest.cc.
References testing::TestEventListeners::Append(), testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), testing::internal::UnitTestOptions::GetOutputFormat(), GTEST_FLAG, and listeners().
Referenced by PostFlagParsingInit().
{
   const std::string& output_format = UnitTestOptions::GetOutputFormat();
   if (output_format == "xml") {
     listeners()->SetDefaultXmlGenerator(new XmlUnitTestResultPrinter(
         UnitTestOptions::GetAbsolutePathToOutputFile().c_str()));
   } else if (output_format != "") {
     printf("WARNING: unrecognized output format \"%s\" ignored.\n",
            output_format.c_str());
     fflush(stdout);
   }
 }