YOUR NAME's CS132 programs: testing::internal::FilePath::CreateDirectoriesRecursively
bool testing::internal::FilePath::CreateDirectoriesRecursively () const
Definition at line 308 of file gtest-filepath.cc.
References CreateDirectoriesRecursively(), CreateFolder(), DirectoryExists(), IsDirectory(), RemoveFileName(), and RemoveTrailingPathSeparator().
Referenced by CreateDirectoriesRecursively().
{
   if (!this->IsDirectory()) {
     return false;
   }
   if (pathname_.length() == 0 || this->DirectoryExists()) {
     return true;
   }
   const FilePath parent(this->RemoveTrailingPathSeparator().RemoveFileName());
   return parent.CreateDirectoriesRecursively() && this->CreateFolder();
 }