YOUR NAME's CS132 programs: testing::internal::ExpectationBase::DescribeCallCountTo
void testing::internal::ExpectationBase::DescribeCallCountTo (::std::ostream * os) const
Definition at line 150 of file gmock-spec-builders.cc.
References call_count(), cardinality(), testing::Cardinality::DescribeActualCallCountTo(), testing::Cardinality::DescribeTo(), is_retired(), IsOverSaturated(), IsSatisfied(), and IsSaturated().
Referenced by testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
{
   g_gmock_mutex.AssertHeld();
   // Describes how many times the function is expected to be called.
   *os << "         Expected: to be ";
   cardinality().DescribeTo(os);
   *os << "\n           Actual: ";
   Cardinality::DescribeActualCallCountTo(call_count(), os);
   // Describes the state of the expectation (e.g. is it satisfied?
   // is it active?).
   *os << " - " << (IsOverSaturated() ? "over-saturated" :
                    IsSaturated() ? "saturated" :
                    IsSatisfied() ? "satisfied" : "unsatisfied")
       << " and "
       << (is_retired() ? "retired" : "active");
 }