YOUR NAME's CS132 programs: testing::internal::GTestFlagSaver::~GTestFlagSaver
testing::internal::GTestFlagSaver::~GTestFlagSaver () inline
Definition at line 186 of file gtest-internal-inl.h.
References testing::internal::CodePointToUtf8(), GTEST_API_, testing::internal::GTEST_ATTRIBUTE_UNUSED_, GTEST_FLAG, testing::internal::Int32FromEnvOrDie(), gmock_output_test::output, testing::internal::ShouldRunTestOnShard(), testing::internal::ShouldShard(), testing::internal::WideStringToUtf8(), and testing::internal::WriteToShardStatusFileIfNeeded().
                     {
     GTEST_FLAG(also_run_disabled_tests) = also_run_disabled_tests_;
     GTEST_FLAG(break_on_failure) = break_on_failure_;
     GTEST_FLAG(catch_exceptions) = catch_exceptions_;
     GTEST_FLAG(color) = color_;
     GTEST_FLAG(death_test_style) = death_test_style_;
     GTEST_FLAG(death_test_use_fork) = death_test_use_fork_;
     GTEST_FLAG(filter) = filter_;
     GTEST_FLAG(internal_run_death_test) = internal_run_death_test_;
     GTEST_FLAG(list_tests) = list_tests_;
     GTEST_FLAG(output) = output_;
     GTEST_FLAG(print_time) = print_time_;
     GTEST_FLAG(random_seed) = random_seed_;
     GTEST_FLAG(repeat) = repeat_;
     GTEST_FLAG(shuffle) = shuffle_;
     GTEST_FLAG(stack_trace_depth) = stack_trace_depth_;
     GTEST_FLAG(stream_result_to) = stream_result_to_;
     GTEST_FLAG(throw_on_failure) = throw_on_failure_;
   }