YOUR NAME's CS132 programs: testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked
bool testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked ()
Definition at line 467 of file gmock-spec-builders.cc.
References testing::internal::ExpectationBase::DescribeCallCountTo(), testing::internal::Expect(), testing::internal::ExpectationBase::file(), first_used_file, first_used_line, testing::internal::ExpectationBase::IsOverSaturated(), testing::internal::ExpectationBase::IsSatisfied(), leakable, testing::internal::ExpectationBase::line(), testing::internal::ExpectationBase::MaybeDescribeExtraMatcherTo(), testing::internal::ExpectationBase::source_text(), and untyped_expectations_.
{
   g_gmock_mutex.AssertHeld();
   bool expectations_met = true;
   for (UntypedExpectations::const_iterator it =
            untyped_expectations_.begin();
        it != untyped_expectations_.end(); ++it) {
     ExpectationBase* const untyped_expectation = it->get();
     if (untyped_expectation->IsOverSaturated()) {
       // There was an upper-bound violation.  Since the error was
       // already reported when it occurred, there is no need to do
       // anything here.
       expectations_met = false;
     } else if (!untyped_expectation->IsSatisfied()) {
       expectations_met = false;
       ::std::stringstream ss;
       ss  << "Actual function call count doesn't match "
           << untyped_expectation->source_text() << "...\n";
       // No need to show the source file location of the expectation
       // in the description, as the Expect() call that follows already
       // takes care of it.
       untyped_expectation->MaybeDescribeExtraMatcherTo(&ss);
       untyped_expectation->DescribeCallCountTo(&ss);
       Expect(false, untyped_expectation->file(),
              untyped_expectation->line(), ss.str());
     }
   }
   // Deleting our expectations may trigger other mock objects to be deleted, for
   // example if an action contains a reference counted smart pointer to that
   // mock object, and that is the last reference. So if we delete our
   // expectations within the context of the global mutex we may deadlock when
   // this method is called again. Instead, make a copy of the set of
   // expectations to delete, clear our set within the mutex, and then clear the
   // copied set outside of it.
   UntypedExpectations expectations_to_delete;
   untyped_expectations_.swap(expectations_to_delete);
   g_gmock_mutex.Unlock();
   expectations_to_delete.clear();
   g_gmock_mutex.Lock();
   return expectations_met;
 }