YOUR NAME's CS132 programs: testing::TestCase::test_to_run_count
int testing::TestCase::test_to_run_count () const
Definition at line 2702 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::TEST(), and testing::internal::UnitTestImpl::test_to_run_count().
{
   return CountIf(test_info_list_, ShouldRunTest);
 }