YOUR NAME's CS132 programs: testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith
UntypedActionResultHolderBase * testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith (const void * untyped_args)
Definition at line 339 of file gmock-spec-builders.cc.
References testing::internal::ExpectationBase::DescribeLocationTo(), testing::internal::Expect(), testing::internal::ExpectationBase::file(), testing::internal::kAllow, testing::internal::kInfo, testing::internal::kWarn, testing::internal::kWarning, testing::internal::ExpectationBase::line(), testing::internal::Log(), testing::internal::LogIsVisible(), MockObject(), Name(), testing::internal::UntypedActionResultHolderBase::PrintAsActionResult(), testing::internal::ReportUninterestingCall(), untyped_expectations_, UntypedDescribeUninterestingCall(), UntypedFindMatchingExpectation(), UntypedPerformAction(), UntypedPerformDefaultAction(), and UntypedPrintArgs().
{
   if (untyped_expectations_.size() == 0) {
     // No expectation is set on this mock method - we have an
     // uninteresting call.
     // We must get Google Mock's reaction on uninteresting calls
     // made on this mock object BEFORE performing the action,
     // because the action may DELETE the mock object and make the
     // following expression meaningless.
     const CallReaction reaction =
         Mock::GetReactionOnUninterestingCalls(MockObject());
     // True iff we need to print this call's arguments and return
     // value.  This definition must be kept in sync with
     // the behavior of ReportUninterestingCall().
     const bool need_to_report_uninteresting_call =
         // If the user allows this uninteresting call, we print it
         // only when he wants informational messages.
         reaction == kAllow ? LogIsVisible(kInfo) :
         // If the user wants this to be a warning, we print it only
         // when he wants to see warnings.
         reaction == kWarn ? LogIsVisible(kWarning) :
         // Otherwise, the user wants this to be an error, and we
         // should always print detailed information in the error.
         true;
     if (!need_to_report_uninteresting_call) {
       // Perform the action without printing the call information.
       return this->UntypedPerformDefaultAction(untyped_args, "");
     }
     // Warns about the uninteresting call.
     ::std::stringstream ss;
     this->UntypedDescribeUninterestingCall(untyped_args, &ss);
     // Calculates the function result.
     UntypedActionResultHolderBase* const result =
         this->UntypedPerformDefaultAction(untyped_args, ss.str());
     // Prints the function result.
     if (result != NULL)
       result->PrintAsActionResult(&ss);
     ReportUninterestingCall(reaction, ss.str());
     return result;
   }
   bool is_excessive = false;
   ::std::stringstream ss;
   ::std::stringstream why;
   ::std::stringstream loc;
   const void* untyped_action = NULL;
   // The UntypedFindMatchingExpectation() function acquires and
   // releases g_gmock_mutex.
   const ExpectationBase* const untyped_expectation =
       this->UntypedFindMatchingExpectation(
           untyped_args, &untyped_action, &is_excessive,
           &ss, &why);
   const bool found = untyped_expectation != NULL;
   // True iff we need to print the call's arguments and return value.
   // This definition must be kept in sync with the uses of Expect()
   // and Log() in this function.
   const bool need_to_report_call =
       !found || is_excessive || LogIsVisible(kInfo);
   if (!need_to_report_call) {
     // Perform the action without printing the call information.
     return
         untyped_action == NULL ?
         this->UntypedPerformDefaultAction(untyped_args, "") :
         this->UntypedPerformAction(untyped_action, untyped_args);
   }
   ss << "    Function call: " << Name();
   this->UntypedPrintArgs(untyped_args, &ss);
   // In case the action deletes a piece of the expectation, we
   // generate the message beforehand.
   if (found && !is_excessive) {
     untyped_expectation->DescribeLocationTo(&loc);
   }
   UntypedActionResultHolderBase* const result =
       untyped_action == NULL ?
       this->UntypedPerformDefaultAction(untyped_args, ss.str()) :
       this->UntypedPerformAction(untyped_action, untyped_args);
   if (result != NULL)
     result->PrintAsActionResult(&ss);
   ss << "\n" << why.str();
   if (!found) {
     // No expectation matches this call - reports a failure.
     Expect(false, NULL, -1, ss.str());
   } else if (is_excessive) {
     // We had an upper-bound violation and the failure message is in ss.
     Expect(false, untyped_expectation->file(),
            untyped_expectation->line(), ss.str());
   } else {
     // We had an expected call and the matching expectation is
     // described in ss.
     Log(kInfo, loc.str() + ss.str(), 2);
   }
   return result;
 }