YOUR NAME's CS132 programs: testing::internal::PredicateFormatterFromMatcher::operator()
template<typename M > template<typename T > AssertionResult testing::internal::PredicateFormatterFromMatcher< M >::operator() (const char * value_text, const T & x) const inline
Definition at line 1842 of file gmock-matchers.h.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::internal::MatcherBase< T >::DescribeTo(), GTEST_DISALLOW_ASSIGN_, and testing::internal::MatchPrintAndExplain().
{
     // We convert matcher_ to a Matcher<const T&> *now* instead of
     // when the PredicateFormatterFromMatcher object was constructed,
     // as matcher_ may be polymorphic (e.g. NotNull()) and we won't
     // know which type to instantiate it to until we actually see the
     // type of x here.
     //
     // We write SafeMatcherCast<const T&>(matcher_) instead of
     // Matcher<const T&>(matcher_), as the latter won't compile when
     // matcher_ has type Matcher<T> (e.g. An<int>()).
     // We don't write MatcherCast<const T&> either, as that allows
     // potentially unsafe downcasting of the matcher argument.
     const Matcher<const T&> matcher = SafeMatcherCast<const T&>(matcher_);
     StringMatchResultListener listener;
     if (MatchPrintAndExplain(x, matcher, &listener))
       return AssertionSuccess();
     ::std::stringstream ss;
     ss << "Value of: " << value_text << "\n"
        << "Expected: ";
     matcher.DescribeTo(&ss);
     ss << "\n  Actual: " << listener.str();
     return AssertionFailure() << ss.str();
   }