YOUR NAME's CS132 programs: testing::internal::UnitTestHelper::GetSortedTestCases
static TestCase const** testing::internal::UnitTestHelper::GetSortedTestCases () inline static
Definition at line 57 of file gtest-unittest-api_test.cc.
References testing::UnitTest::GetInstance(), testing::UnitTest::GetTestCase(), and testing::UnitTest::total_test_case_count().
Referenced by testing::internal::FinalSuccessChecker::TearDown(), and testing::internal::TEST().
{
     UnitTest& unit_test = *UnitTest::GetInstance();
     TestCase const** const test_cases =
         new const TestCase*[unit_test.total_test_case_count()];
     for (int i = 0; i < unit_test.total_test_case_count(); ++i)
       test_cases[i] = unit_test.GetTestCase(i);
     std::sort(test_cases,
               test_cases + unit_test.total_test_case_count(),
               LessByName<TestCase>());
     return test_cases;
   }