YOUR NAME's CS132 programs: cpp.ast.AstBuilder.handle_template
def cpp.ast.AstBuilder.handle_template (self)
Definition at line 1422 of file ast.py.
References cpp.ast.AstBuilder._AddBackToken(), cpp.ast.AstBuilder._AddBackTokens(), cpp.ast.AstBuilder._GetClass(), cpp.ast.AstBuilder._GetNextToken(), cpp.ast.AstBuilder._GetTemplatedTypes(), cpp.ast.AstBuilder._GetVarTokensUpTo(), cpp.ast.AstBuilder.GetMethod(), and cpp.ast.AstBuilder.handle_friend().
     def handle_template(self):
         token = self._GetNextToken()
         assert token.token_type == tokenize.SYNTAX, token
         assert token.name == '<', token
         templated_types = self._GetTemplatedTypes()
         # TODO(nnorwitz): for now, just ignore the template params.
         token = self._GetNextToken()
         if token.token_type == tokenize.NAME:
             if token.name == 'class':
                 return self._GetClass(Class, VISIBILITY_PRIVATE, templated_types)
             elif token.name == 'struct':
                 return self._GetClass(Struct, VISIBILITY_PUBLIC, templated_types)
             elif token.name == 'friend':
                 return self.handle_friend()
         self._AddBackToken(token)
         tokens, last = self._GetVarTokensUpTo(tokenize.SYNTAX, '(', ';')
         tokens.append(last)
         self._AddBackTokens(tokens)
         if last.name == '(':
             return self.GetMethod(FUNCTION_NONE, templated_types)
         # Must be a variable definition.
         return None