YOUR NAME's CS132 programs: Interface::StringFromString
virtual char* Interface::StringFromString (char * str) pure virtual
Referenced by Mock::Mock(), TEST(), and ~Interface().