YOUR NAME's CS132 programs: testing::internal::MatcherBase::Matches
template<typename T> bool testing::internal::MatcherBase< T >::Matches (T x) const inline
Definition at line 261 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::AllOfMatches(), testing::gmock_matchers_test::AnyOfMatches(), testing::gmock_matchers_test::MATCHER_P(), testing::internal::MatchPrintAndExplain(), testing::gmock_matchers_test::TEST(), TEST(), testing::gmock_matchers_test::TEST_F(), testing::gmock_matchers_test::FloatingPointTest< RawType >::TestMatches(), and testing::gmock_matchers_test::FloatingPointNearTest< RawType >::TestNearMatches().
{
     DummyMatchResultListener dummy;
     return MatchAndExplain(x, &dummy);
   }