YOUR NAME's CS132 programs: testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter
testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter () virtual
Definition at line 593 of file gtest.cc.
References testing::internal::GetUnitTestImpl(), INTERCEPT_ALL_THREADS, testing::internal::UnitTestImpl::SetGlobalTestPartResultReporter(), and testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread().
{
   internal::UnitTestImpl* const impl = internal::GetUnitTestImpl();
   if (intercept_mode_ == INTERCEPT_ALL_THREADS) {
     impl->SetGlobalTestPartResultReporter(old_reporter_);
   } else {
     impl->SetTestPartResultReporterForCurrentThread(old_reporter_);
   }
 }