YOUR NAME's CS132 programs: gtest_help_test.GTestHelpTest.TestHelpFlag
def gtest_help_test.GTestHelpTest.TestHelpFlag (self, flag)
Verifies correct behavior when help flag is specified.
The right message must be printed and the tests must
skipped when the given flag is specified.
Args:
  flag:  A flag to pass to the binary or None.
Definition at line 101 of file gtest_help_test.py.
References gtest_help_test.RunWithFlag().
Referenced by gtest_help_test.GTestHelpTest.testPrintsHelpWithFullFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithIncorrectFlagStyle(), gtest_help_test.GTestHelpTest.testPrintsHelpWithQuestionFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithShortFlag(), gtest_help_test.GTestHelpTest.testPrintsHelpWithUnrecognizedGoogleTestFlag(), and gtest_help_test.GTestHelpTest.testPrintsHelpWithWindowsStyleQuestionFlag().
   def TestHelpFlag(self, flag):
     """Verifies correct behavior when help flag is specified.
     The right message must be printed and the tests must
     skipped when the given flag is specified.
     Args:
       flag:  A flag to pass to the binary or None.
     """
     exit_code, output = RunWithFlag(flag)
     self.assertEquals(0, exit_code)
     self.assert_(HELP_REGEX.search(output), output)
     if IS_LINUX:
       self.assert_(STREAM_RESULT_TO_FLAG in output, output)
     else:
       self.assert_(STREAM_RESULT_TO_FLAG not in output, output)
     if SUPPORTS_DEATH_TESTS and not IS_WINDOWS:
       self.assert_(DEATH_TEST_STYLE_FLAG in output, output)
     else:
       self.assert_(DEATH_TEST_STYLE_FLAG not in output, output)