YOUR NAME's CS132 programs: testing::TestCase::failed_test_count
int testing::TestCase::failed_test_count () const
Definition at line 2682 of file gtest.cc.
References testing::internal::CountIf().
Referenced by testing::internal::UnitTestImpl::failed_test_count(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), and testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd().
{
   return CountIf(test_info_list_, TestFailed);
 }