YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnTestEnd
void testing::internal::PrettyUnitTestResultPrinter::OnTestEnd (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3130 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestResult::elapsed_time(), testing::TestResult::Failed(), GTEST_FLAG, testing::TestInfo::name(), testing::TestResult::Passed(), testing::internal::PrintFullTestCommentIfPresent(), testing::TestInfo::result(), testing::internal::StreamableToString(), and testing::TestInfo::test_case_name().
{
   if (test_info.result()->Passed()) {
     ColoredPrintf(COLOR_GREEN, "[       OK ] ");
   } else {
     ColoredPrintf(COLOR_RED, "[  FAILED  ] ");
   }
   PrintTestName(test_info.test_case_name(), test_info.name());
   if (test_info.result()->Failed())
     PrintFullTestCommentIfPresent(test_info);
   if (GTEST_FLAG(print_time)) {
     printf(" (%s ms)\n", internal::StreamableToString(
            test_info.result()->elapsed_time()).c_str());
   } else {
     printf("\n");
   }
   fflush(stdout);
 }