YOUR NAME's CS132 programs: testing::UnitTest::current_test_info
const TestInfo * testing::UnitTest::current_test_info () const
Definition at line 4279 of file gtest.cc.
Referenced by testing::CurrentTestInfoTest::SetUpTestCase(), testing::CurrentTestInfoTest::TearDownTestCase(), and testing::TEST_F().
{
   internal::MutexLock lock(&mutex_);
   return impl_->current_test_info();
 }