YOUR NAME's CS132 programs: testing::internal::QuantifierMatcherImpl::MatchAndExplainImpl
template<typename Container > bool testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl (bool all_elements_should_match, Container container, MatchResultListener * listener) const inline
Definition at line 2816 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     StlContainerReference stl_container = View::ConstReference(container);
     size_t i = 0;
     for (typename StlContainer::const_iterator it = stl_container.begin();
          it != stl_container.end(); ++it, ++i) {
       StringMatchResultListener inner_listener;
       const bool matches = inner_matcher_.MatchAndExplain(*it, &inner_listener);
       if (matches != all_elements_should_match) {
         *listener << "whose element #" << i
                   << (matches ? " matches" : " doesn't match");
         PrintIfNotEmpty(inner_listener.str(), listener->stream());
         return !all_elements_should_match;
       }
     }
     return all_elements_should_match;
   }