YOUR NAME's CS132 programs: testing::internal::ArgsMatcherImpl::MatchAndExplain
template<class ArgsTuple , int k0 = -1, int k1 = -1, int k2 = -1, int k3 = -1, int k4 = -1, int k5 = -1, int k6 = -1, int k7 = -1, int k8 = -1, int k9 = -1> virtual bool testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain (ArgsTuple args, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< ArgsTuple >.
Definition at line 223 of file gmock-generated-matchers.h.
References testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::PrintToString(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     const SelectedArgs& selected_args = GetSelectedArgs(args);
     if (!listener->IsInterested())
       return inner_matcher_.Matches(selected_args);
     PrintIndices(listener->stream());
     *listener << "are " << PrintToString(selected_args);
     StringMatchResultListener inner_listener;
     const bool match = inner_matcher_.MatchAndExplain(selected_args,
                                                       &inner_listener);
     PrintIfNotEmpty(inner_listener.str(), listener->stream());
     return match;
   }