YOUR NAME's CS132 programs: gtest_filter_unittest.GTestFilterUnitTest.AdjustForParameterizedTests
def gtest_filter_unittest.GTestFilterUnitTest.AdjustForParameterizedTests (self, tests_to_run)
Adjust tests_to_run in case value parameterized tests are disabled.
Definition at line 251 of file gtest_filter_unittest.py.
References cpp.gmock_class.set.
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled(), and gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding().
   def AdjustForParameterizedTests(self, tests_to_run):
     """Adjust tests_to_run in case value parameterized tests are disabled."""
     global param_tests_present
     if not param_tests_present:
       return list(set(tests_to_run) - set(PARAM_TESTS))
     else:
       return tests_to_run