YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::MockFoo::MockFoo
testing::gmock_generated_function_mockers_test::MockFoo::MockFoo () inline
Definition at line 125 of file gmock-generated-function-mockers_test.cc.
References testing::gmock_generated_function_mockers_test::FooInterface::Binary(), testing::gmock_generated_function_mockers_test::FooInterface::Decimal(), GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_CONST_METHOD0, MOCK_CONST_METHOD1, MOCK_CONST_METHOD1_WITH_CALLTYPE, MOCK_METHOD0, MOCK_METHOD0_WITH_CALLTYPE, MOCK_METHOD1, MOCK_METHOD10, MOCK_METHOD10_WITH_CALLTYPE, MOCK_METHOD1_WITH_CALLTYPE, MOCK_METHOD2, testing::gmock_generated_function_mockers_test::FooInterface::Nullary(), testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentNumber(), testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnArgumentType(), testing::gmock_generated_function_mockers_test::FooInterface::OverloadedOnConstness(), testing::gmock_generated_function_mockers_test::FooInterface::TakesConst(), testing::gmock_generated_function_mockers_test::FooInterface::TakesConstReference(), testing::gmock_generated_function_mockers_test::FooInterface::TakesNonConstReference(), testing::gmock_generated_function_mockers_test::FooInterface::TypeWithComma(), testing::gmock_generated_function_mockers_test::FooInterface::TypeWithHole(), testing::gmock_generated_function_mockers_test::FooInterface::Unary(), and testing::gmock_generated_function_mockers_test::FooInterface::VoidReturning().
 {}