YOUR NAME's CS132 programs: gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput
def gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput (self)
Verifies XML output when a filter is applied.
Runs a test program that executes only some tests and verifies that
non-selected tests do not show up in the XML output.
Definition at line 253 of file gtest_xml_output_unittest.py.
References gtest_xml_output_unittest.GTestXMLOutputUnitTest._GetXmlOutput(), gtest_xml_output_unittest.GTestXMLOutputUnitTest._TestXmlOutput(), gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_test_utils.GetTempDir(), gtest_test_utils.GetTestExecutablePath(), gtest_test_utils.Main(), and gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
   def testFilteredTestXmlOutput(self):
     """Verifies XML output when a filter is applied.
     Runs a test program that executes only some tests and verifies that
     non-selected tests do not show up in the XML output.
     """
     self._TestXmlOutput(GTEST_PROGRAM_NAME, EXPECTED_FILTERED_TEST_XML, 0,
                         extra_args=['%s=SuccessfulTest.*' % GTEST_FILTER_FLAG])