YOUR NAME's CS132 programs: testing::TestInfo::test_case_name
const char* testing::TestInfo::test_case_name () const inline
Definition at line 651 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::AddTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::internal::ReportFailureInUnknownLocation(), and testing::TEST_F().
 { return test_case_name_.c_str(); }