YOUR NAME's CS132 programs: QueueTest::MapTester
void QueueTest::MapTester (const Queue< int > * q) inline protected
Definition at line 96 of file sample3_unittest.cc.
References ASSERT_EQ, Double(), EXPECT_EQ, Queue< E >::Head(), Queue< E >::Map(), QueueNode< E >::next(), and Queue< E >::Size().
Referenced by TEST_F().
{
     // Creates a new queue, where each element is twice as big as the
     // corresponding one in q.
     const Queue<int> * const new_q = q->Map(Double);
     // Verifies that the new queue has the same size as q.
     ASSERT_EQ(q->Size(), new_q->Size());
     // Verifies the relationship between the elements of the two queues.
     for ( const QueueNode<int> * n1 = q->Head(), * n2 = new_q->Head();
           n1 != NULL; n1 = n1->next(), n2 = n2->next() ) {
       EXPECT_EQ(2 * n1->element(), n2->element());
     }
     delete new_q;
   }