YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnTestStart
void testing::internal::PrettyUnitTestResultPrinter::OnTestStart (const TestInfo & test_info) virtual
Implements testing::TestEventListener.
Definition at line 3111 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::ColoredPrintf(), testing::TestInfo::name(), and testing::TestInfo::test_case_name().
{
   ColoredPrintf(COLOR_GREEN,  "[ RUN      ] ");
   PrintTestName(test_info.test_case_name(), test_info.name());
   printf("\n");
   fflush(stdout);
 }