YOUR NAME's CS132 programs: testing::StringMatchResultListener::str
internal::string testing::StringMatchResultListener::str () const inline
Definition at line 189 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::Explain(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::BothOfMatcherImpl< T >::MatchAndExplain(), testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain(), testing::internal::SizeIsMatcher< SizeMatcher >::Impl< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::KeyMatcherImpl< PairType >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::QuantifierMatcherImpl< Container >::MatchAndExplainImpl(), testing::internal::MatchPrintAndExplain(), testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
 { return ss_.str(); }