YOUR NAME's CS132 programs: testing::Cardinality::DescribeTo
void testing::Cardinality::DescribeTo (::std::ostream * os) const inline
Definition at line 115 of file gmock-cardinalities.h.
References testing::AnyNumber(), testing::AtLeast(), testing::AtMost(), testing::Between(), testing::Exactly(), and GTEST_API_.
Referenced by testing::internal::ExpectationBase::CheckActionCountIfNotDone(), and testing::internal::ExpectationBase::DescribeCallCountTo().
 { impl_->DescribeTo(os); }