YOUR NAME's CS132 programs: testing::internal::TuplePrefix::ExplainMatchFailuresTo
template<size_t N> template<typename MatcherTuple , typename ValueTuple > static void testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo (const MatcherTuple & matchers, const ValueTuple & values, ::std::ostream * os) inline static
Definition at line 743 of file gmock-matchers.h.
References testing::internal::PrintIfNotEmpty(), upload::type, testing::internal::UniversalPrint(), and testing::Value().
{
     // First, describes failures in the first N - 1 fields.
     TuplePrefix<N - 1>::ExplainMatchFailuresTo(matchers, values, os);
     // Then describes the failure (if any) in the (N - 1)-th (0-based)
     // field.
     typename tuple_element<N - 1, MatcherTuple>::type matcher =
         get<N - 1>(matchers);
     typedef typename tuple_element<N - 1, ValueTuple>::type Value;
     Value value = get<N - 1>(values);
     StringMatchResultListener listener;
     if (!matcher.MatchAndExplain(value, &listener)) {
       // TODO(wan): include in the message the name of the parameter
       // as used in MOCK_METHOD*() when possible.
       *os << "  Expected arg #" << N - 1 << ": ";
       get<N - 1>(matchers).DescribeTo(os);
       *os << "\n           Actual: ";
       // We remove the reference in type Value to prevent the
       // universal printer from printing the address of value, which
       // isn't interesting to the user most of the time.  The
       // matcher's MatchAndExplain() method handles the case when
       // the address is interesting.
       internal::UniversalPrint(value, os);
       PrintIfNotEmpty(listener.str(), os);
       *os << "\n";
     }
   }