YOUR NAME's CS132 programs: upload.SubversionVCS.GuessBase
def upload.SubversionVCS.GuessBase (self, required)
Wrapper for _GuessBase.
Definition at line 742 of file upload.py.
References upload.ErrorExit(), upload.RunShell(), and upload.SubversionVCS.svn_base.
Referenced by upload.SubversionVCS.GuessBase().
   def GuessBase(self, required):
     """Wrapper for _GuessBase."""
     return self.svn_base