YOUR NAME's CS132 programs: upload.MercurialVCS.GetBaseFile
def upload.MercurialVCS.GetBaseFile (self, filename)
Definition at line 1102 of file upload.py.
References upload.MercurialVCS._GetRelPath(), upload.MercurialVCS.base_rev, upload.VersionControlSystem.IsImage(), and upload.RunShell().
Referenced by upload.MercurialVCS.GetBaseFile().
   def GetBaseFile(self, filename):
     # "hg status" and "hg cat" both take a path relative to the current subdir
     # rather than to the repo root, but "hg diff" has given us the full path
     # to the repo root.
     base_content = ""
     new_content = None
     is_binary = False
     oldrelpath = relpath = self._GetRelPath(filename)
     # "hg status -C" returns two lines for moved/copied files, one otherwise
     out = RunShell(["hg", "status", "-C", "--rev", self.base_rev, relpath])
     out = out.splitlines()
     # HACK: strip error message about missing file/directory if it isn't in
     # the working copy
     if out[0].startswith('%s: ' % relpath):
       out = out[1:]
     if len(out) > 1:
       # Moved/copied => considered as modified, use old filename to
       # retrieve base contents
       oldrelpath = out[1].strip()
       status = "M"
     else:
       status, _ = out[0].split(' ', 1)
     if status != "A":
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True)
       is_binary = "\0" in base_content  # Mercurial's heuristic
     if status != "R":
       new_content = open(relpath, "rb").read()
       is_binary = is_binary or "\0" in new_content
     if is_binary and base_content:
       # Fetch again without converting newlines
       base_content = RunShell(["hg", "cat", "-r", self.base_rev, oldrelpath],
         silent_ok=True, universal_newlines=False)
     if not is_binary or not self.IsImage(relpath):
       new_content = None
     return base_content, new_content, is_binary, status
 # NOTE: The SplitPatch function is duplicated in engine.py, keep them in sync.