YOUR NAME's CS132 programs: testing::internal::String::ShowWideCString
std::string testing::internal::String::ShowWideCString (const wchar_t * wide_c_str) static
Definition at line 1848 of file gtest.cc.
References testing::internal::WideStringToUtf8().
Referenced by testing::Message::operator<<(), and operator<<().
{
   if (wide_c_str == NULL)  return "(null)";
   return internal::WideStringToUtf8(wide_c_str, -1);
 }