YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart
void testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart (const UnitTest & unit_test, int iteration) virtual
Implements testing::TestEventListener.
Definition at line 3056 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_YELLOW, testing::internal::ColoredPrintf(), testing::internal::posix::GetEnv(), GTEST_FLAG, GTEST_NAME_, testing::internal::Int32FromEnvOrDie(), testing::UnitTest::random_seed(), testing::internal::ShouldShard(), testing::UnitTest::test_case_to_run_count(), and testing::UnitTest::test_to_run_count().
{
   if (GTEST_FLAG(repeat) != 1)
     printf("\nRepeating all tests (iteration %d) . . .\n\n", iteration + 1);
   const char* const filter = GTEST_FLAG(filter).c_str();
   // Prints the filter if it's not *.  This reminds the user that some
   // tests may be skipped.
   if (!String::CStringEquals(filter, kUniversalFilter)) {
     ColoredPrintf(COLOR_YELLOW,
                   "Note: %s filter = %s\n", GTEST_NAME_, filter);
   }
   if (internal::ShouldShard(kTestTotalShards, kTestShardIndex, false)) {
     const Int32 shard_index = Int32FromEnvOrDie(kTestShardIndex, -1);
     ColoredPrintf(COLOR_YELLOW,
                   "Note: This is test shard %d of %s.\n",
                   static_cast<int>(shard_index) + 1,
                   internal::posix::GetEnv(kTestTotalShards));
   }
   if (GTEST_FLAG(shuffle)) {
     ColoredPrintf(COLOR_YELLOW,
                   "Note: Randomizing tests' orders with a seed of %d .\n",
                   unit_test.random_seed());
   }
   ColoredPrintf(COLOR_GREEN,  "[==========] ");
   printf("Running %s from %s.\n",
          FormatTestCount(unit_test.test_to_run_count()).c_str(),
          FormatTestCaseCount(unit_test.test_case_to_run_count()).c_str());
   fflush(stdout);
 }