YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::AddTestInfo
void testing::internal::UnitTestImpl::AddTestInfo (Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc, TestInfo * test_info) inline
Definition at line 645 of file gtest-internal-inl.h.
References testing::internal::FilePath::GetCurrentDir(), GTEST_CHECK_, original_working_dir_, testing::TestInfo::test_case_name(), and testing::TestInfo::type_param().
Referenced by testing::internal::MakeAndRegisterTestInfo().
{
     // In order to support thread-safe death tests, we need to
     // remember the original working directory when the test program
     // was first invoked.  We cannot do this in RUN_ALL_TESTS(), as
     // the user may have changed the current directory before calling
     // RUN_ALL_TESTS().  Therefore we capture the current directory in
     // AddTestInfo(), which is called to register a TEST or TEST_F
     // before main() is reached.
     if (original_working_dir_.IsEmpty()) {
       original_working_dir_.Set(FilePath::GetCurrentDir());
       GTEST_CHECK_(!original_working_dir_.IsEmpty())
           << "Failed to get the current working directory.";
     }
     GetTestCase(test_info->test_case_name(),
                 test_info->type_param(),
                 set_up_tc,
                 tear_down_tc)->AddTestInfo(test_info);
   }