YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::FilterTests
int testing::internal::UnitTestImpl::FilterTests (ReactionToSharding shard_tests)
Definition at line 4789 of file gtest.cc.
References testing::internal::UnitTestOptions::FilterMatchesTest(), GTEST_FLAG, HONOR_SHARDING_PROTOCOL, IGNORE_SHARDING_PROTOCOL, testing::internal::Int32FromEnvOrDie(), testing::internal::UnitTestOptions::MatchesFilter(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::should_run(), and testing::internal::ShouldRunTestOnShard().
Referenced by RunAllTests().
{
   const Int32 total_shards = shard_tests == HONOR_SHARDING_PROTOCOL ?
       Int32FromEnvOrDie(kTestTotalShards, -1) : -1;
   const Int32 shard_index = shard_tests == HONOR_SHARDING_PROTOCOL ?
       Int32FromEnvOrDie(kTestShardIndex, -1) : -1;
   // num_runnable_tests are the number of tests that will
   // run across all shards (i.e., match filter and are not disabled).
   // num_selected_tests are the number of tests to be run on
   // this shard.
   int num_runnable_tests = 0;
   int num_selected_tests = 0;
   for (size_t i = 0; i < test_cases_.size(); i++) {
     TestCase* const test_case = test_cases_[i];
     const std::string &test_case_name = test_case->name();
     test_case->set_should_run(false);
     for (size_t j = 0; j < test_case->test_info_list().size(); j++) {
       TestInfo* const test_info = test_case->test_info_list()[j];
       const std::string test_name(test_info->name());
       // A test is disabled if test case name or test name matches
       // kDisableTestFilter.
       const bool is_disabled =
           internal::UnitTestOptions::MatchesFilter(test_case_name,
                                                    kDisableTestFilter) ||
           internal::UnitTestOptions::MatchesFilter(test_name,
                                                    kDisableTestFilter);
       test_info->is_disabled_ = is_disabled;
       const bool matches_filter =
           internal::UnitTestOptions::FilterMatchesTest(test_case_name,
                                                        test_name);
       test_info->matches_filter_ = matches_filter;
       const bool is_runnable =
           (GTEST_FLAG(also_run_disabled_tests) || !is_disabled) &&
           matches_filter;
       const bool is_selected = is_runnable &&
           (shard_tests == IGNORE_SHARDING_PROTOCOL ||
            ShouldRunTestOnShard(total_shards, shard_index,
                                 num_runnable_tests));
       num_runnable_tests += is_runnable;
       num_selected_tests += is_selected;
       test_info->should_run_ = is_selected;
       test_case->set_should_run(test_case->should_run() || is_selected);
     }
   }
   return num_selected_tests;
 }