YOUR NAME's CS132 programs: PerceptionModule::runDetection
int PerceptionModule::runDetection (bool testVideo, bool testImage)
runDetection is the wrapper function to run the object detection pipeline.
Parameters
testVideo - bool to check if the function is being called in test with video as input.
testImage - bool to check if the function is being called in test with image as input.
Returns
0 if function runs successfully and -1 otherwise.
Definition at line 39 of file PerceptionModule.cpp.
References ImageInference::applyNMS(), FrameTransform::cameraToBase(), IOModule::drawBoundingBoxes(), ImageProcessing::gaussianBlur(), ImageInference::getBoxes(), IOModule::getInputPath(), ImageInference::getLabels(), FrameTransform::imageToCamera(), ImageProcessing::medianBlur(), FrameTransform::outputCoords(), IOModule::readImage(), IOModule::readInputDir(), IOModule::readInputType(), IOModule::readOutputDir(), IOModule::returnCameraID(), IOModule::returnInputDir(), IOModule::returnInputType(), ImageInference::runForwardPass(), IOModule::saveTextFile(), IOModule::setDefaultInputs(), IOModule::setDefaultVidInput(), and ImageInference::setModelParams().
Referenced by main(), and TEST().
{
     // Gather all the modules
     ImageInference inferModule;
     ImageProcessing imageProcessModule;
     IOModule ioModule;
     FrameTransform frameTransModule;
     // Read User inputs
     if (testImage) {
         std::istringstream inputType("4");
         ioModule.readInputType(inputType);
     }
     if (testVideo) {
         std::istringstream inputType("5");
         ioModule.readInputType(inputType);
     }
     if (!testVideo && !testImage) {
         ioModule.readInputType(cin);
     }
     if (ioModule.returnInputType() < 4) {
         if (ioModule.returnInputType() == 3) {
             std::istringstream inputDir("../data/");
             ioModule.readInputDir(inputDir);
             ioModule.readOutputDir(cin);
         } else {
             ioModule.readInputDir(cin);
             ioModule.readOutputDir(cin);
         }
     }
     // Initialize YOLOv3 network
     inferModule.setModelParams();
     string savedPath = ioModule.returnInputDir();
     if (ioModule.returnInputType() == 1) {
         // Get the vector of path of each image
         vector<string> pathList = ioModule.getInputPath(savedPath);
         // Read every image and forward pass through inference
         vector<cv::Rect> boxesList;
         vector<string> labelList;
         vector<int> imageList;
         int imageCounter = 0;
         for (auto &imagePath : pathList) {
             Mat image = ioModule.readImage(imagePath, false);
             Mat tempImage = imageProcessModule.gaussianBlur(image);
             tempImage = imageProcessModule.medianBlur(tempImage);
             vector<Mat> finalLayerOut = inferModule.runForwardPass(tempImage);
             inferModule.applyNMS(tempImage, finalLayerOut);
             auto boxCords = inferModule.getBoxes();
             vector<int> labels = inferModule.getLabels();
             if (boxCords.size() > 0) {
                 for (size_t i = 0; i <= boxCords.size(); ++i) {
                     cv::Rect bBox = boxCords[i];
                     boxesList.push_back(bBox);
                     labelList.push_back("person");
                     imageList.push_back(imageCounter);
                     ioModule.drawBoundingBoxes(image, bBox.x, bBox.y,
                                                 bBox.x + bBox.width,
                                                 bBox.y + bBox.height);
                 }
                 if (!testImage) {
                     cv::namedWindow("AcmeViz", CV_WINDOW_AUTOSIZE);
                     cv::imshow("AcmeViz", image);
                     cv::waitKey(0);
                 }
             } else {
                 cout << "No bounding boxes found!\n";
             }
             imageCounter++;
         }
         // Saving files
         frameTransModule.imageToCamera(boxesList);
         frameTransModule.cameraToBase();
         auto boxCoords = frameTransModule.outputCoords(boxesList);
         ioModule.saveTextFile(boxCoords, labelList, imageList);
         cout << "Thank you for using the module!\n";
         return 0;
     }
     if (ioModule.returnInputType() == 4) {
         ioModule.setDefaultInputs();
         savedPath = ioModule.returnInputDir();
         // Get the vector of path of each image
         vector<string> pathList = ioModule.getInputPath(savedPath);
         // Read every image and forward pass through inference
         vector<cv::Rect> boxesList;
         vector<string> labelList;
         vector<int> imageList;
         int imageCounter = 0;
         for (auto &imagePath : pathList) {
             Mat image = ioModule.readImage(imagePath, false);
             Mat tempImage = imageProcessModule.gaussianBlur(image);
             tempImage = imageProcessModule.medianBlur(tempImage);
             vector<Mat> finalLayerOut = inferModule.runForwardPass(tempImage);
             inferModule.applyNMS(tempImage, finalLayerOut);
             auto boxCords = inferModule.getBoxes();
             vector<int> labels = inferModule.getLabels();
             if (boxCords.size() > 0) {
                 for (size_t i = 0; i <= boxCords.size(); ++i) {
                     cv::Rect bBox = boxCords[i];
                     boxesList.push_back(bBox);
                     labelList.push_back("person");
                     imageList.push_back(imageCounter);
                     ioModule.drawBoundingBoxes(image, bBox.x, bBox.y,
                                                 bBox.x + bBox.width,
                                                 bBox.y + bBox.height);
                 }
                 if (!testImage) {
                     cv::namedWindow("AcmeViz", CV_WINDOW_AUTOSIZE);
                     cv::imshow("AcmeViz", image);
                     cv::waitKey(0);
                 }
             } else {
                 cout << "No bounding boxes found!\n";
             }
             imageCounter++;
         }
         // Saving files
         frameTransModule.imageToCamera(boxesList);
         frameTransModule.cameraToBase();
         auto boxCoords = frameTransModule.outputCoords(boxesList);
         ioModule.saveTextFile(boxCoords, labelList, imageList);
         cout << "Thank you for using the module!\n";
         return 0;
     }
     if (ioModule.returnInputType() == 2) {
         capture = cv::VideoCapture(ioModule.returnInputDir());
     }
     if (ioModule.returnInputType() == 3) {
         capture = cv::VideoCapture(ioModule.returnCameraID());
     }
     if (ioModule.returnInputType() == 5) {
         ioModule.setDefaultVidInput();
         capture = cv::VideoCapture(ioModule.returnInputDir());
     }
     if (!capture.isOpened()) {
         std::cout << "Error opening video stream or file!" << std::endl;
         return -1;
     }
     vector<cv::Rect> boxesList;
     vector<string> labelList;
     vector<int> imageList;
     int imageCounter = 0;
     while (capture.read(frame)) {
         if (frame.empty()) {
             break;
         }
         Mat tempImage = imageProcessModule.gaussianBlur(frame);
         tempImage = imageProcessModule.medianBlur(tempImage);
         vector<Mat> finalLayerOut = inferModule.runForwardPass(tempImage);
         inferModule.applyNMS(tempImage, finalLayerOut);
         auto boxCords = inferModule.getBoxes();
         vector<int> labels = inferModule.getLabels();
         if (boxCords.size() > 0) {
             for (size_t i = 0; i <= boxCords.size(); ++i) {
                 cv::Rect bBox = boxCords[i];
                 boxesList.push_back(bBox);
                 labelList.push_back("person");
                 imageList.push_back(imageCounter);
                 ioModule.drawBoundingBoxes(tempImage, bBox.x, bBox.y,
                                             bBox.x + bBox.width,
                                             bBox.y + bBox.height);
             }
             if (!testVideo) {
                 cv::namedWindow("AcmeViz", CV_WINDOW_AUTOSIZE);
                 cv::imshow("AcmeViz", tempImage);
                 char c = static_cast<char>(cv::waitKey(5));
                 if (c == 27) {
                     break;
                 }
             }
         } else {
             cout << "No bounding boxes found!\n";
         }
         imageCounter++;
         frame = 0;
     }
     // Saving files
     frameTransModule.imageToCamera(boxesList);
     frameTransModule.cameraToBase();
     auto boxCoords = frameTransModule.outputCoords(boxesList);
     ioModule.saveTextFile(boxCoords, labelList, imageList);
     cout << "Thank you for using the module!\n";
     return 0;
 }