YOUR NAME's CS132 programs: testing::internal::ExpectationBase::RetireAllPreRequisites
void testing::internal::ExpectationBase::RetireAllPreRequisites () protected
Definition at line 95 of file gmock-spec-builders.cc.
References testing::ExpectationSet::begin(), testing::ExpectationSet::end(), immediate_prerequisites_, is_retired(), Retire(), and RetireAllPreRequisites().
Referenced by RetireAllPreRequisites().
{
   if (is_retired()) {
     // We can take this short-cut as we never retire an expectation
     // until we have retired all its pre-requisites.
     return;
   }
   for (ExpectationSet::const_iterator it = immediate_prerequisites_.begin();
        it != immediate_prerequisites_.end(); ++it) {
     ExpectationBase* const prerequisite = it->expectation_base().get();
     if (!prerequisite->is_retired()) {
       prerequisite->RetireAllPreRequisites();
       prerequisite->Retire();
     }
   }
 }