YOUR NAME's CS132 programs: testing::Test::HasFatalFailure
bool Test::HasFatalFailure () static
Definition at line 2487 of file gtest.cc.
References testing::internal::UnitTestImpl::current_test_result(), testing::internal::GetUnitTestImpl(), and testing::TestResult::HasFatalFailure().
Referenced by testing::internal::HandleExceptionsInMethodIfSupported(), testing::internal::UnitTestImpl::RegisterParameterizedTests(), testing::internal::UnitTestImpl::RunAllTests(), and TryTestSubroutine().
{
   return internal::GetUnitTestImpl()->current_test_result()->HasFatalFailure();
 }