YOUR NAME's CS132 programs: testing::Test::RecordProperty
void Test::RecordProperty (const std::string & key, const std::string & value) static
Definition at line 2237 of file gtest.cc.
References testing::UnitTest::GetInstance().
Referenced by ExternalUtilityThatCallsRecordProperty(), main(), RecordProperty(), PropertyOne::SetUp(), PropertyTwo::SetUp(), PropertyTwo::TearDown(), PropertyOne::TearDown(), and TEST_F().
{
   UnitTest::GetInstance()->RecordProperty(key, value);
 }