YOUR NAME's CS132 programs: testing::TestCase::type_param
const char* testing::TestCase::type_param () const inline
Definition at line 804 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseStart(), testing::internal::PrintFullTestCommentIfPresent(), and testing::internal::TEST().
{
     if (type_param_.get() != NULL)
       return type_param_->c_str();
     return NULL;
   }