YOUR NAME's CS132 programs: testing::internal::FilePath::RemoveTrailingPathSeparator
FilePath testing::internal::FilePath::RemoveTrailingPathSeparator () const
Definition at line 346 of file gtest-filepath.cc.
References upload::dest, FilePath(), IsDirectory(), and testing::internal::kPathSeparator.
Referenced by ConcatPaths(), CreateDirectoriesRecursively(), CreateFolder(), and DirectoryExists().
{
   return IsDirectory()
       ? FilePath(pathname_.substr(0, pathname_.length() - 1))
       : *this;
 }