YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::os_stack_trace_getter
OsStackTraceGetterInterface * testing::internal::UnitTestImpl::os_stack_trace_getter ()
Definition at line 4918 of file gtest.cc.
Referenced by testing::TestCase::GetTestInfo(), testing::internal::HandleExceptionsInMethodIfSupported(), and RegisterParameterizedTests().
{
   if (os_stack_trace_getter_ == NULL) {
 #ifdef GTEST_OS_STACK_TRACE_GETTER_
     os_stack_trace_getter_ = new GTEST_OS_STACK_TRACE_GETTER_;
 #else
     os_stack_trace_getter_ = new OsStackTraceGetter;
 #endif  // GTEST_OS_STACK_TRACE_GETTER_
   }
   return os_stack_trace_getter_;
 }