YOUR NAME's CS132 programs: gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes
def gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes (self, expected_node, actual_node)
Asserts that actual_node (a DOM node object) is equivalent to
expected_node (another DOM node object), in that either both of
them are CDATA nodes and have the same value, or both are DOM
elements and actual_node meets all of the following conditions:
*  It has the same tag name as expected_node.
*  It has the same set of attributes as expected_node, each with
   the same value as the corresponding attribute of expected_node.
   Exceptions are any attribute named "time", which needs only be
   convertible to a floating-point number and any attribute named
   "type_param" which only has to be non-empty.
*  It has an equivalent set of child nodes (including elements and
   CDATA sections) as expected_node.  Note that we ignore the
   order of the children as they are not guaranteed to be in any
   particular order.
Definition at line 51 of file gtest_xml_test_utils.py.
References gtest_xml_test_utils.GTestXMLTestCase._GetChildren(), and gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes().
Referenced by gtest_xml_test_utils.GTestXMLTestCase.AssertEquivalentNodes(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def AssertEquivalentNodes(self, expected_node, actual_node):
     """
     Asserts that actual_node (a DOM node object) is equivalent to
     expected_node (another DOM node object), in that either both of
     them are CDATA nodes and have the same value, or both are DOM
     elements and actual_node meets all of the following conditions:
     *  It has the same tag name as expected_node.
     *  It has the same set of attributes as expected_node, each with
        the same value as the corresponding attribute of expected_node.
        Exceptions are any attribute named "time", which needs only be
        convertible to a floating-point number and any attribute named
        "type_param" which only has to be non-empty.
     *  It has an equivalent set of child nodes (including elements and
        CDATA sections) as expected_node.  Note that we ignore the
        order of the children as they are not guaranteed to be in any
        particular order.
     """
     if expected_node.nodeType == Node.CDATA_SECTION_NODE:
       self.assertEquals(Node.CDATA_SECTION_NODE, actual_node.nodeType)
       self.assertEquals(expected_node.nodeValue, actual_node.nodeValue)
       return
     self.assertEquals(Node.ELEMENT_NODE, actual_node.nodeType)
     self.assertEquals(Node.ELEMENT_NODE, expected_node.nodeType)
     self.assertEquals(expected_node.tagName, actual_node.tagName)
     expected_attributes = expected_node.attributes
     actual_attributes   = actual_node  .attributes
     self.assertEquals(
         expected_attributes.length, actual_attributes.length,
         'attribute numbers differ in element %s:\nExpected: %r\nActual: %r' % (
             actual_node.tagName, expected_attributes.keys(),
             actual_attributes.keys()))
     for i in range(expected_attributes.length):
       expected_attr = expected_attributes.item(i)
       actual_attr   = actual_attributes.get(expected_attr.name)
       self.assert_(
           actual_attr is not None,
           'expected attribute %s not found in element %s' %
           (expected_attr.name, actual_node.tagName))
       self.assertEquals(
           expected_attr.value, actual_attr.value,
           ' values of attribute %s in element %s differ: %s vs %s' %
           (expected_attr.name, actual_node.tagName,
            expected_attr.value, actual_attr.value))
     expected_children = self._GetChildren(expected_node)
     actual_children = self._GetChildren(actual_node)
     self.assertEquals(
         len(expected_children), len(actual_children),
         'number of child elements differ in element ' + actual_node.tagName)
     for child_id, child in expected_children.items():
       self.assert_(child_id in actual_children,
                    '<%s> is not in <%s> (in element %s)' %
                    (child_id, actual_children, actual_node.tagName))
       self.AssertEquivalentNodes(child, actual_children[child_id])