YOUR NAME's CS132 programs: gtest_throw_on_failure_test.ThrowOnFailureTest.RunAndVerify
def gtest_throw_on_failure_test.ThrowOnFailureTest.RunAndVerify (self, env_var_value, flag_value, should_fail)
Runs gtest_throw_on_failure_test_ and verifies that it does
(or does not) exit with a non-zero code.
Args:
  env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                variable; None if the variable should be unset.
  flag_value:       value of the --gtest_break_on_failure flag;
                None if the flag should not be present.
  should_fail:      True iff the program is expected to fail.
Definition at line 83 of file gtest_throw_on_failure_test.py.
References gtest_throw_on_failure_test.Run(), and gtest_throw_on_failure_test.SetEnvVar().
Referenced by gtest_throw_on_failure_test.ThrowOnFailureTest.testDefaultBehavior(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureEnvVar(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlag(), and gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar().
   def RunAndVerify(self, env_var_value, flag_value, should_fail):
     """Runs gtest_throw_on_failure_test_ and verifies that it does
     (or does not) exit with a non-zero code.
     Args:
       env_var_value:    value of the GTEST_BREAK_ON_FAILURE environment
                         variable; None if the variable should be unset.
       flag_value:       value of the --gtest_break_on_failure flag;
                         None if the flag should not be present.
       should_fail:      True iff the program is expected to fail.
     """
     SetEnvVar(THROW_ON_FAILURE, env_var_value)
     if env_var_value is None:
       env_var_value_msg = ' is not set'
     else:
       env_var_value_msg = '=' + env_var_value
     if flag_value is None:
       flag = ''
     elif flag_value == '0':
       flag = '--%s=0' % THROW_ON_FAILURE
     else:
       flag = '--%s' % THROW_ON_FAILURE
     command = [EXE_PATH]
     if flag:
       command.append(flag)
     if should_fail:
       should_or_not = 'should'
     else:
       should_or_not = 'should not'
     failed = not Run(command)
     SetEnvVar(THROW_ON_FAILURE, None)
     msg = ('when %s%s, an assertion failure in "%s" %s cause a non-zero '
            'exit code.' %
            (THROW_ON_FAILURE, env_var_value_msg, ' '.join(command),
             should_or_not))
     self.assert_(failed == should_fail, msg)