YOUR NAME's CS132 programs: cpp.ast.AstBuilder.handle_virtual
def cpp.ast.AstBuilder.handle_virtual (self)
Definition at line 1289 of file ast.py.
References cpp.ast.AstBuilder._GetMethod(), cpp.ast.AstBuilder._GetNextToken(), cpp.ast.AstBuilder._GetTokensUpTo(), and cpp.ast.AstBuilder.GetMethod().
     def handle_virtual(self):
         # What follows must be a method.
         token = token2 = self._GetNextToken()
         if token.name == 'inline':
             # HACK(nnorwitz): handle inline dtors by ignoring 'inline'.
             token2 = self._GetNextToken()
         if token2.token_type == tokenize.SYNTAX and token2.name == '~':
             return self.GetMethod(FUNCTION_VIRTUAL + FUNCTION_DTOR, None)
         assert token.token_type == tokenize.NAME or token.name == '::', token
         return_type_and_name = self._GetTokensUpTo(tokenize.SYNTAX, '(')  # )
         return_type_and_name.insert(0, token)
         if token2 is not token:
             return_type_and_name.insert(1, token2)
         return self._GetMethod(return_type_and_name, FUNCTION_VIRTUAL,
                                None, False)