YOUR NAME's CS132 programs: testing::internal::FilePath::RemoveFileName
FilePath testing::internal::FilePath::RemoveFileName () const
Definition at line 166 of file gtest-filepath.cc.
References c_str(), FilePath(), and testing::internal::kCurrentDirectoryString.
Referenced by CreateDirectoriesRecursively(), and testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd().
{
   const char* const last_sep = FindLastPathSeparator();
   std::string dir;
   if (last_sep) {
     dir = std::string(c_str(), last_sep + 1 - c_str());
   } else {
     dir = kCurrentDirectoryString;
   }
   return FilePath(dir);
 }