YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::RegisterParameterizedTests
void testing::internal::UnitTestImpl::RegisterParameterizedTests ()
Definition at line 2617 of file gtest.cc.
References testing::internal::TestFactoryBase::CreateTest(), testing::UnitTest::GetInstance(), testing::internal::GetTimeInMillis(), testing::internal::GetUnitTestImpl(), testing::internal::HandleExceptionsInMethodIfSupported(), testing::Test::HasFatalFailure(), testing::UnitTest::listeners(), testing::TestEventListener::OnTestEnd(), testing::TestEventListener::OnTestStart(), os_stack_trace_getter(), set_current_test_info(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by PostFlagParsingInit().
{
 #if GTEST_HAS_PARAM_TEST
   if (!parameterized_tests_registered_) {
     parameterized_test_registry_.RegisterTests();
     parameterized_tests_registered_ = true;
   }
 #endif
 }