YOUR NAME's CS132 programs: testing::MatchResultListener::IsInterested
bool testing::MatchResultListener::IsInterested () const inline
Definition at line 104 of file gmock-matchers.h.
Referenced by testing::internal::FindPairing(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::FloatingEqMatcher< FloatType >::Impl< T >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PairMatcherImpl< PairType >::MatchAndExplain(), testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain(), testing::internal::MatchPrintAndExplain(), and testing::internal::UnorderedElementsAreMatcherImplBase::VerifyAllElementsAndMatchersAreMatched().
 { return stream_ != NULL; }