YOUR NAME's CS132 programs: testing::internal::PointwiseMatcher::Impl::MatchAndExplain
template<typename TupleMatcher, typename RhsContainer> template<typename LhsContainer > virtual bool testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain (LhsContainer lhs, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< LhsContainer >.
Definition at line 2749 of file gmock-matchers.h.
References GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and testing::internal::UniversalPrint().
{
       LhsStlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
       const size_t actual_size = lhs_stl_container.size();
       if (actual_size != rhs_.size()) {
         *listener << "which contains " << actual_size << " values";
         return false;
       }
       typename LhsStlContainer::const_iterator left = lhs_stl_container.begin();
       typename RhsStlContainer::const_iterator right = rhs_.begin();
       for (size_t i = 0; i != actual_size; ++i, ++left, ++right) {
         const InnerMatcherArg value_pair(*left, *right);
         if (listener->IsInterested()) {
           StringMatchResultListener inner_listener;
           if (!mono_tuple_matcher_.MatchAndExplain(
                   value_pair, &inner_listener)) {
             *listener << "where the value pair (";
             UniversalPrint(*left, listener->stream());
             *listener << ", ";
             UniversalPrint(*right, listener->stream());
             *listener << ") at index #" << i << " don't match";
             PrintIfNotEmpty(inner_listener.str(), listener->stream());
             return false;
           }
         } else {
           if (!mono_tuple_matcher_.Matches(value_pair))
             return false;
         }
       }
       return true;
     }