YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::PostFlagParsingInit
void testing::internal::UnitTestImpl::PostFlagParsingInit ()
Definition at line 4436 of file gtest.cc.
References testing::TestEventListeners::Append(), ConfigureXmlOutput(), listeners(), and RegisterParameterizedTests().
Referenced by testing::internal::InitGoogleTestImpl(), and RunAllTests().
{
   // Ensures that this function does not execute more than once.
   if (!post_flag_parse_init_performed_) {
     post_flag_parse_init_performed_ = true;
 #if defined(GTEST_CUSTOM_TEST_EVENT_LISTENER_)
     // Register to send notifications about key process state changes.
     listeners()->Append(new GTEST_CUSTOM_TEST_EVENT_LISTENER_());
 #endif  // defined(GTEST_CUSTOM_TEST_EVENT_LISTENER_)
 #if GTEST_HAS_DEATH_TEST
     InitDeathTestSubprocessControlInfo();
     SuppressTestEventsIfInSubprocess();
 #endif  // GTEST_HAS_DEATH_TEST
     // Registers parameterized tests. This makes parameterized tests
     // available to the UnitTest reflection API without running
     // RUN_ALL_TESTS.
     RegisterParameterizedTests();
     // Configures listeners for XML output. This makes it possible for users
     // to shut down the default XML output before invoking RUN_ALL_TESTS.
     ConfigureXmlOutput();
 #if GTEST_CAN_STREAM_RESULTS_
     // Configures listeners for streaming test results to the specified server.
     ConfigureStreamingOutput();
 #endif  // GTEST_CAN_STREAM_RESULTS_
   }
 }