YOUR NAME's CS132 programs: testing::internal::ContainerEqMatcher::MatchAndExplain
template<typename Container > template<typename LhsContainer > bool testing::internal::ContainerEqMatcher< Container >::MatchAndExplain (const LhsContainer & lhs, MatchResultListener * listener) const inline
Definition at line 2547 of file gmock-matchers.h.
References testing::internal::ArrayAwareFind(), GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::stream(), upload::type, and testing::internal::UniversalPrint().
{
     // GTEST_REMOVE_CONST_() is needed to work around an MSVC 8.0 bug
     // that causes LhsContainer to be a const type sometimes.
     typedef internal::StlContainerView<GTEST_REMOVE_CONST_(LhsContainer)>
         LhsView;
     typedef typename LhsView::type LhsStlContainer;
     StlContainerReference lhs_stl_container = LhsView::ConstReference(lhs);
     if (lhs_stl_container == expected_)
       return true;
     ::std::ostream* const os = listener->stream();
     if (os != NULL) {
       // Something is different. Check for extra values first.
       bool printed_header = false;
       for (typename LhsStlContainer::const_iterator it =
                lhs_stl_container.begin();
            it != lhs_stl_container.end(); ++it) {
         if (internal::ArrayAwareFind(expected_.begin(), expected_.end(), *it) ==
             expected_.end()) {
           if (printed_header) {
             *os << ", ";
           } else {
             *os << "which has these unexpected elements: ";
             printed_header = true;
           }
           UniversalPrint(*it, os);
         }
       }
       // Now check for missing values.
       bool printed_header2 = false;
       for (typename StlContainer::const_iterator it = expected_.begin();
            it != expected_.end(); ++it) {
         if (internal::ArrayAwareFind(
                 lhs_stl_container.begin(), lhs_stl_container.end(), *it) ==
             lhs_stl_container.end()) {
           if (printed_header2) {
             *os << ", ";
           } else {
             *os << (printed_header ? ",\nand" : "which")
                 << " doesn't have these expected elements: ";
             printed_header2 = true;
           }
           UniversalPrint(*it, os);
         }
       }
     }
     return false;
   }