YOUR NAME's CS132 programs: testing::internal::GTestLog::~GTestLog
testing::internal::GTestLog::~GTestLog ()
Definition at line 919 of file gtest-port.cc.
References testing::internal::posix::Abort(), testing::internal::CaptureStderr(), testing::internal::CaptureStdout(), testing::internal::posix::FClose(), testing::internal::posix::FOpen(), testing::internal::GetCapturedStderr(), testing::internal::GetCapturedStdout(), GetStream(), GTEST_CHECK_, GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::internal::GTEST_FATAL, GTEST_LOG_, and testing::internal::ReadEntireFile().
                     {
   GetStream() << ::std::endl;
   if (severity_ == GTEST_FATAL) {
     fflush(stderr);
     posix::Abort();
   }
 }