YOUR NAME's CS132 programs: gtest_filter_unittest.GTestFilterUnitTest.AssertSetEqual
def gtest_filter_unittest.GTestFilterUnitTest.AssertSetEqual (self, lhs, rhs)
Asserts that two sets are equal.
Definition at line 233 of file gtest_filter_unittest.py.
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled(), and gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar().
   def AssertSetEqual(self, lhs, rhs):
     """Asserts that two sets are equal."""
     for elem in lhs:
       self.assert_(elem in rhs, '%s in %s' % (elem, rhs))
     for elem in rhs:
       self.assert_(elem in lhs, '%s in %s' % (elem, lhs))