YOUR NAME's CS132 programs: upload.GitVCS.GetBaseFile
def upload.GitVCS.GetBaseFile (self, filename)
Definition at line 1026 of file upload.py.
References upload.GitVCS.base_hashes, upload.ErrorExit(), and upload.RunShellWithReturnCode().
Referenced by upload.GitVCS.GetBaseFile().
   def GetBaseFile(self, filename):
     hash = self.base_hashes[filename]
     base_content = None
     new_content = None
     is_binary = False
     if hash == "0" * 40:  # All-zero hash indicates no base file.
       status = "A"
       base_content = ""
     else:
       status = "M"
       base_content, returncode = RunShellWithReturnCode(["git", "show", hash])
       if returncode:
         ErrorExit("Got error status from 'git show %s'" % hash)
     return (base_content, new_content, is_binary, status)