YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread
void testing::internal::UnitTestImpl::SetTestPartResultReporterForCurrentThread (TestPartResultReporterInterface * reporter)
Definition at line 724 of file gtest.cc.
Referenced by testing::internal::HasNewFatalFailureHelper::HasNewFatalFailureHelper(), testing::ScopedFakeTestPartResultReporter::ScopedFakeTestPartResultReporter(), testing::internal::HasNewFatalFailureHelper::~HasNewFatalFailureHelper(), and testing::ScopedFakeTestPartResultReporter::~ScopedFakeTestPartResultReporter().
{
   per_thread_test_part_result_reporter_.set(reporter);
 }