YOUR NAME's CS132 programs: testing::TestResult::Failed
bool testing::TestResult::Failed () const
Definition at line 2170 of file gtest.cc.
References testing::TestPartResult::failed(), testing::TestPartResult::fatally_failed(), GetTestPartResult(), and total_part_count().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestEnd().
{
   for (int i = 0; i < total_part_count(); ++i) {
     if (GetTestPartResult(i).failed())
       return true;
   }
   return false;
 }