YOUR NAME's CS132 programs: upload.VersionControlSystem.GetBaseFiles
def upload.VersionControlSystem.GetBaseFiles (self, diff)
Helper that calls GetBase file for each file in the patch.
Returns:
  A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
  are retrieved based on lines that start with "Index:" or
  "Property changes on:".
Definition at line 642 of file upload.py.
References upload.VersionControlSystem.GetBaseFile(), upload.VersionControlSystem.GetBaseFiles(), and upload.VersionControlSystem.UploadBaseFiles().
   def GetBaseFiles(self, diff):
     """Helper that calls GetBase file for each file in the patch.
     Returns:
       A dictionary that maps from filename to GetBaseFile's tuple.  Filenames
       are retrieved based on lines that start with "Index:" or
       "Property changes on:".
     """
     files = {}
     for line in diff.splitlines(True):
       if line.startswith('Index:') or line.startswith('Property changes on:'):
         unused, filename = line.split(':', 1)
         # On Windows if a file has property changes its filename uses '\'
         # instead of '/'.
         filename = filename.strip().replace('\\', '/')
         files[filename] = self.GetBaseFile(filename)
     return files