YOUR NAME's CS132 programs: testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart
void testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart (const UnitTest & unit_test) virtual
Implements testing::TestEventListener.
Definition at line 3161 of file gtest.cc.
References testing::internal::COLOR_GREEN, testing::internal::COLOR_RED, testing::internal::ColoredPrintf(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), testing::TestInfo::name(), testing::TestCase::name(), testing::TestResult::Passed(), testing::internal::PrintFullTestCommentIfPresent(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::TestCase::should_run(), testing::UnitTest::total_test_case_count(), and testing::TestCase::total_test_count().
{
   ColoredPrintf(COLOR_GREEN,  "[----------] ");
   printf("Global test environment tear-down\n");
   fflush(stdout);
 }