YOUR NAME's CS132 programs: gtest_list_tests_unittest.GTestListTestsUnitTest.RunAndVerify
def gtest_list_tests_unittest.GTestListTestsUnitTest.RunAndVerify (self, flag_value, expected_output_re, other_flag)
Runs gtest_list_tests_unittest_ and verifies that it prints
the correct tests.
Args:
  flag_value:         value of the --gtest_list_tests flag;
                  None if the flag should not be present.
  expected_output_re: regular expression that matches the expected
                  output after running command;
  other_flag:         a different flag to be passed to command
                  along with gtest_list_tests;
                  None if the flag should not be present.
Definition at line 129 of file gtest_list_tests_unittest.py.
References gtest_list_tests_unittest.Run().
Referenced by gtest_throw_on_failure_test.ThrowOnFailureTest.testDefaultBehavior(), gtest_list_tests_unittest.GTestListTestsUnitTest.testDefaultBehavior(), gtest_list_tests_unittest.GTestListTestsUnitTest.testFlag(), gtest_list_tests_unittest.GTestListTestsUnitTest.testOverrideNonFilterFlags(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureEnvVar(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlag(), gtest_throw_on_failure_test.ThrowOnFailureTest.testThrowOnFailureFlagOverridesEnvVar(), and gtest_list_tests_unittest.GTestListTestsUnitTest.testWithFilterFlags().
   def RunAndVerify(self, flag_value, expected_output_re, other_flag):
     """Runs gtest_list_tests_unittest_ and verifies that it prints
     the correct tests.
     Args:
       flag_value:         value of the --gtest_list_tests flag;
                           None if the flag should not be present.
       expected_output_re: regular expression that matches the expected
                           output after running command;
       other_flag:         a different flag to be passed to command
                           along with gtest_list_tests;
                           None if the flag should not be present.
     """
     if flag_value is None:
       flag = ''
       flag_expression = 'not set'
     elif flag_value == '0':
       flag = '--%s=0' % LIST_TESTS_FLAG
       flag_expression = '0'
     else:
       flag = '--%s' % LIST_TESTS_FLAG
       flag_expression = '1'
     args = [flag]
     if other_flag is not None:
       args += [other_flag]
     output = Run(args)
     if expected_output_re:
       self.assert_(
           expected_output_re.match(output),
           ('when %s is %s, the output of "%s" is "%s",\n'
            'which does not match regex "%s"' %
            (LIST_TESTS_FLAG, flag_expression, ' '.join(args), output,
             expected_output_re.pattern)))
     else:
       self.assert_(
           not EXPECTED_OUTPUT_NO_FILTER_RE.match(output),
           ('when %s is %s, the output of "%s" is "%s"'%
            (LIST_TESTS_FLAG, flag_expression, ' '.join(args), output)))