YOUR NAME's CS132 programs: testing::internal::FilePath::c_str
const char* testing::internal::FilePath::c_str () const inline
Definition at line 78 of file gtest-filepath.h.
Referenced by CreateFolder(), DirectoryExists(), RemoveExtension(), RemoveFileName(), and testing::TEST_F().
 { return pathname_.c_str(); }