YOUR NAME's CS132 programs: upload.AbstractRpcServer.__init__
def upload.AbstractRpcServer.__init__ (self, host, auth_function, host_override = None, extra_headers = {}, save_cookies = False)
Creates a new HttpRpcServer.
Args:
  host: The host to send requests to.
  auth_function: A function that takes no arguments and returns an
(email, password) tuple when called. Will be called if authentication
is required.
  host_override: The host header to send to the server (defaults to host).
  extra_headers: A dict of extra headers to append to every request.
  save_cookies: If True, save the authentication cookies to local disk.
If False, use an in-memory cookiejar instead.  Subclasses must
implement this functionality.  Defaults to False.
Definition at line 128 of file upload.py.
References upload.AbstractRpcServer._CreateRequest(), upload.AbstractRpcServer._GetAuthCookie(), upload.AbstractRpcServer._GetAuthToken(), upload.AbstractRpcServer._GetOpener(), upload.AbstractRpcServer.auth_function, upload.AbstractRpcServer.authenticated, upload.AbstractRpcServer.extra_headers, upload.AbstractRpcServer.host, upload.AbstractRpcServer.host_override, upload.AbstractRpcServer.opener, upload.AbstractRpcServer.save_cookies, and upload.AbstractRpcServer.Send().
                save_cookies=False):
     """Creates a new HttpRpcServer.
     Args:
       host: The host to send requests to.
       auth_function: A function that takes no arguments and returns an
         (email, password) tuple when called. Will be called if authentication
         is required.
       host_override: The host header to send to the server (defaults to host).
       extra_headers: A dict of extra headers to append to every request.
       save_cookies: If True, save the authentication cookies to local disk.
         If False, use an in-memory cookiejar instead.  Subclasses must
         implement this functionality.  Defaults to False.
     """
     self.host = host
     self.host_override = host_override
     self.auth_function = auth_function
     self.authenticated = False
     self.extra_headers = extra_headers
     self.save_cookies = save_cookies
     self.opener = self._GetOpener()
     if self.host_override:
       logging.info("Server: %s; Host: %s", self.host, self.host_override)
     else:
       logging.info("Server: %s", self.host)