YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::ListTestsMatchingFilter
void testing::internal::UnitTestImpl::ListTestsMatchingFilter ()
Definition at line 4865 of file gtest.cc.
References testing::TestInfo::name(), testing::TestCase::name(), testing::TestCase::type_param(), and testing::TestInfo::value_param().
Referenced by RunAllTests().
{
   // Print at most this many characters for each type/value parameter.
   const int kMaxParamLength = 250;
   for (size_t i = 0; i < test_cases_.size(); i++) {
     const TestCase* const test_case = test_cases_[i];
     bool printed_test_case_name = false;
     for (size_t j = 0; j < test_case->test_info_list().size(); j++) {
       const TestInfo* const test_info =
           test_case->test_info_list()[j];
       if (test_info->matches_filter_) {
         if (!printed_test_case_name) {
           printed_test_case_name = true;
           printf("%s.", test_case->name());
           if (test_case->type_param() != NULL) {
             printf("  # %s = ", kTypeParamLabel);
             // We print the type parameter on a single line to make
             // the output easy to parse by a program.
             PrintOnOneLine(test_case->type_param(), kMaxParamLength);
           }
           printf("\n");
         }
         printf("  %s", test_info->name());
         if (test_info->value_param() != NULL) {
           printf("  # %s = ", kValueParamLabel);
           // We print the value parameter on a single line to make the
           // output easy to parse by a program.
           PrintOnOneLine(test_info->value_param(), kMaxParamLength);
         }
         printf("\n");
       }
     }
   }
   fflush(stdout);
 }