YOUR NAME's CS132 programs: testing::CardinalityInterface::ConservativeUpperBound
virtual int testing::CardinalityInterface::ConservativeUpperBound () const inline virtual
Definition at line 66 of file gmock-cardinalities.h.
References DescribeTo(), IsSatisfiedByCallCount(), and IsSaturatedByCallCount().
 { return INT_MAX; }