YOUR NAME's CS132 programs: gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml
def gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml (self, element)
Normalizes Google Test's XML output to eliminate references to transient
information that may change from run to run.
*  The "time" attribute of <testsuites>, <testsuite> and <testcase>
   elements is replaced with a single asterisk, if it contains
   only digit characters.
*  The "timestamp" attribute of <testsuites> elements is replaced with a
   single asterisk, if it contains a valid ISO8601 datetime value.
*  The "type_param" attribute of <testcase> elements is replaced with a
   single asterisk (if it sn non-empty) as it is the type name returned
   by the compiler and is platform dependent.
*  The line info reported in the first line of the "message"
   attribute and CDATA section of <failure> elements is replaced with the
   file's basename and a single asterisk for the line number.
*  The directory names in file paths are removed.
*  The stack traces are removed.
Definition at line 150 of file gtest_xml_test_utils.py.
References gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml().
Referenced by gtest_xml_test_utils.GTestXMLTestCase.NormalizeXml(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
   def NormalizeXml(self, element):
     """
     Normalizes Google Test's XML output to eliminate references to transient
     information that may change from run to run.
     *  The "time" attribute of <testsuites>, <testsuite> and <testcase>
        elements is replaced with a single asterisk, if it contains
        only digit characters.
     *  The "timestamp" attribute of <testsuites> elements is replaced with a
        single asterisk, if it contains a valid ISO8601 datetime value.
     *  The "type_param" attribute of <testcase> elements is replaced with a
        single asterisk (if it sn non-empty) as it is the type name returned
        by the compiler and is platform dependent.
     *  The line info reported in the first line of the "message"
        attribute and CDATA section of <failure> elements is replaced with the
        file's basename and a single asterisk for the line number.
     *  The directory names in file paths are removed.
     *  The stack traces are removed.
     """
     if element.tagName == 'testsuites':
       timestamp = element.getAttributeNode('timestamp')
       timestamp.value = re.sub(r'^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d$',
                                '*', timestamp.value)
     if element.tagName in ('testsuites', 'testsuite', 'testcase'):
       time = element.getAttributeNode('time')
       time.value = re.sub(r'^\d+(\.\d+)?$', '*', time.value)
       type_param = element.getAttributeNode('type_param')
       if type_param and type_param.value:
         type_param.value = '*'
     elif element.tagName == 'failure':
       source_line_pat = r'^.*[/\\](.*:)\d+\n'
       # Replaces the source line information with a normalized form.
       message = element.getAttributeNode('message')
       message.value = re.sub(source_line_pat, '\\1*\n', message.value)
       for child in element.childNodes:
         if child.nodeType == Node.CDATA_SECTION_NODE:
           # Replaces the source line information with a normalized form.
           cdata = re.sub(source_line_pat, '\\1*\n', child.nodeValue)
           # Removes the actual stack trace.
           child.nodeValue = re.sub(r'\nStack trace:\n(.|\n)*',
                                    '', cdata)
     for child in element.childNodes:
       if child.nodeType == Node.ELEMENT_NODE:
         self.NormalizeXml(child)