YOUR NAME's CS132 programs: upload.VersionControlSystem.CheckForUnknownFiles
def upload.VersionControlSystem.CheckForUnknownFiles (self)
Show an "are you sure?" prompt if there are unknown files.
Definition at line 613 of file upload.py.
References upload.VersionControlSystem.CheckForUnknownFiles(), upload.ErrorExit(), and upload.VersionControlSystem.GetUnknownFiles().
   def CheckForUnknownFiles(self):
     """Show an "are you sure?" prompt if there are unknown files."""
     unknown_files = self.GetUnknownFiles()
     if unknown_files:
       print "The following files are not added to version control:"
       for line in unknown_files:
         print line
       prompt = "Are you sure to continue?(y/N) "
       answer = raw_input(prompt).strip()
       if answer != "y":
         ErrorExit("User aborted")