YOUR NAME's CS132 programs: testing::UnitTest::GetTestCase
const TestCase * testing::UnitTest::GetTestCase (int i) const
Definition at line 4063 of file gtest.cc.
Referenced by testing::internal::UnitTestHelper::FindTestCase(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::UnitTestHelper::GetSortedTestCases(), and testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart().
{
   return impl()->GetTestCase(i);
 }