YOUR NAME's CS132 programs: testing::internal::FilePath::RemoveExtension
FilePath testing::internal::FilePath::RemoveExtension (const char * extension) const
Definition at line 124 of file gtest-filepath.cc.
References c_str(), testing::internal::String::EndsWithCaseInsensitive(), and FilePath().
{
   const std::string dot_extension = std::string(".") + extension;
   if (String::EndsWithCaseInsensitive(pathname_, dot_extension)) {
     return FilePath(pathname_.substr(
         0, pathname_.length() - dot_extension.length()));
   }
   return *this;
 }