YOUR NAME's CS132 programs: upload.SubversionVCS.__init__
def upload.SubversionVCS.__init__ (self, options)
Definition at line 724 of file upload.py.
References upload.SubversionVCS.__init__(), upload.SubversionVCS._GuessBase(), upload.ErrorExit(), upload.SubversionVCS.rev_end, upload.SubversionVCS.rev_start, upload.SubversionVCS.svn_base, and upload.SubversionVCS.svnls_cache.
   def __init__(self, options):
     super(SubversionVCS, self).__init__(options)
     if self.options.revision:
       match = re.match(r"(\d+)(:(\d+))?", self.options.revision)
       if not match:
         ErrorExit("Invalid Subversion revision %s." % self.options.revision)
       self.rev_start = match.group(1)
       self.rev_end = match.group(3)
     else:
       self.rev_start = self.rev_end = None
     # Cache output from "svn list -r REVNO dirname".
     # Keys: dirname, Values: 2-tuple (ouput for start rev and end rev).
     self.svnls_cache = {}
     # SVN base URL is required to fetch files deleted in an older revision.
     # Result is cached to not guess it over and over again in GetBaseFile().
     required = self.options.download_base or self.options.revision is not None
     self.svn_base = self._GuessBase(required)