YOUR NAME's CS132 programs: gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled
def gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled (self, gtest_filter, tests_to_run)
Checks that the binary runs correct set of tests for the given filter.
Runs gtest_filter_unittest_ with the given filter, and enables
disabled tests. Verifies that the right set of tests were run.
Args:
  gtest_filter: A filter to apply to the tests.
  tests_to_run: A set of tests expected to run.
Definition at line 328 of file gtest_filter_unittest.py.
References gtest_filter_unittest.GTestFilterUnitTest.AdjustForParameterizedTests(), gtest_filter_unittest.GTestFilterUnitTest.AssertSetEqual(), and gtest_filter_unittest.RunAndExtractTestList().
Referenced by gtest_filter_unittest.GTestFilterUnitTest.testBadFilter(), gtest_filter_unittest.GTestFilterUnitTest.testFilterByTestCase(), gtest_filter_unittest.GTestFilterUnitTest.testFilterDisabledTests(), gtest_filter_unittest.GTestFilterUnitTest.testFullName(), and gtest_filter_unittest.GTestFilterUnitTest.testUniversalFilters().
   def RunAndVerifyAllowingDisabled(self, gtest_filter, tests_to_run):
     """Checks that the binary runs correct set of tests for the given filter.
     Runs gtest_filter_unittest_ with the given filter, and enables
     disabled tests. Verifies that the right set of tests were run.
     Args:
       gtest_filter: A filter to apply to the tests.
       tests_to_run: A set of tests expected to run.
     """
     tests_to_run = self.AdjustForParameterizedTests(tests_to_run)
     # Construct the command line.
     args = ['--%s' % ALSO_RUN_DISABED_TESTS_FLAG]
     if gtest_filter is not None:
       args.append('--%s=%s' % (FILTER_FLAG, gtest_filter))
     tests_run = RunAndExtractTestList(args)[0]
     self.AssertSetEqual(tests_run, tests_to_run)