YOUR NAME's CS132 programs: gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding
def gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding (self, gtest_filter, total_shards, tests_to_run, args = None, check_exit_0 = False)
Checks that binary runs correct tests for the given filter and shard.
Runs all shards of gtest_filter_unittest_ with the given filter, and
verifies that the right set of tests were run. The union of tests run
on each shard should be identical to tests_to_run, without duplicates.
Args:
  gtest_filter: A filter to apply to the tests.
  total_shards: A total number of shards to split test run into.
  tests_to_run: A set of tests expected to run.
  args   :      Arguments to pass to the to the test binary.
  check_exit_0: When set to a true value, make sure that all shards
            return 0.
Definition at line 291 of file gtest_filter_unittest.py.
References gtest_filter_unittest.GTestFilterUnitTest.AdjustForParameterizedTests(), gtest_filter_unittest.GTestFilterUnitTest.AssertPartitionIsValid(), gtest_filter_unittest.RunWithSharding(), and gtest_filter_unittest.SetEnvVar().
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.testDefaultBehaviorWithShards(), gtest_filter_unittest.GTestFilterUnitTest.testEmptyFilter(), gtest_filter_unittest.GTestFilterUnitTest.testFullName(), gtest_filter_unittest.GTestFilterUnitTest.testShardingWorksWithDeathTests(), and gtest_filter_unittest.GTestFilterUnitTest.testUniversalFilters().
                                args=None, check_exit_0=False):
     """Checks that binary runs correct tests for the given filter and shard.
     Runs all shards of gtest_filter_unittest_ with the given filter, and
     verifies that the right set of tests were run. The union of tests run
     on each shard should be identical to tests_to_run, without duplicates.
     Args:
       gtest_filter: A filter to apply to the tests.
       total_shards: A total number of shards to split test run into.
       tests_to_run: A set of tests expected to run.
       args   :      Arguments to pass to the to the test binary.
       check_exit_0: When set to a true value, make sure that all shards
                     return 0.
     """
     tests_to_run = self.AdjustForParameterizedTests(tests_to_run)
     # Windows removes empty variables from the environment when passing it
     # to a new process.  This means it is impossible to pass an empty filter
     # into a process using the environment variable.  However, we can still
     # test the case when the variable is not supplied (i.e., gtest_filter is
     # None).
     # pylint: disable-msg=C6403
     if CAN_TEST_EMPTY_FILTER or gtest_filter != '':
       SetEnvVar(FILTER_ENV_VAR, gtest_filter)
       partition = []
       for i in range(0, total_shards):
         (tests_run, exit_code) = RunWithSharding(total_shards, i, args)
         if check_exit_0:
           self.assertEqual(0, exit_code)
         partition.append(tests_run)
       self.AssertPartitionIsValid(tests_to_run, partition)
       SetEnvVar(FILTER_ENV_VAR, None)
     # pylint: enable-msg=C6403