YOUR NAME's CS132 programs: upload.MercurialVCS.GenerateDiff
def upload.MercurialVCS.GenerateDiff (self, extra_args)
Definition at line 1064 of file upload.py.
References upload.MercurialVCS.base_rev, upload.ErrorExit(), upload.MercurialVCS.GenerateDiff(), and upload.RunShell().
   def GenerateDiff(self, extra_args):
     # If no file specified, restrict to the current subdir
     extra_args = extra_args or ["."]
     cmd = ["hg", "diff", "--git", "-r", self.base_rev] + extra_args
     data = RunShell(cmd, silent_ok=True)
     svndiff = []
     filecount = 0
     for line in data.splitlines():
       m = re.match("diff --git a/(\S+) b/(\S+)", line)
       if m:
         # Modify line to make it look like as it comes from svn diff.
         # With this modification no changes on the server side are required
         # to make upload.py work with Mercurial repos.
         # NOTE: for proper handling of moved/copied files, we have to use
         # the second filename.
         filename = m.group(2)
         svndiff.append("Index: %s" % filename)
         svndiff.append("=" * 67)
         filecount += 1
         logging.info(line)
       else:
         svndiff.append(line)
     if not filecount:
       ErrorExit("No valid patches found in output from hg diff")
     return "\n".join(svndiff) + "\n"