YOUR NAME's CS132 programs: testing::internal::ElementsAreMatcherImpl::MatchAndExplain
template<typename Container > virtual bool testing::internal::ElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 3161 of file gmock-matchers.h.
References count, GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::PrintIfNotEmpty(), testing::StringMatchResultListener::str(), and testing::MatchResultListener::stream().
{
     // To work with stream-like "containers", we must only walk
     // through the elements in one pass.
     const bool listener_interested = listener->IsInterested();
     // explanations[i] is the explanation of the element at index i.
     ::std::vector<internal::string> explanations(count());
     StlContainerReference stl_container = View::ConstReference(container);
     typename StlContainer::const_iterator it = stl_container.begin();
     size_t exam_pos = 0;
     bool mismatch_found = false;  // Have we found a mismatched element yet?
     // Go through the elements and matchers in pairs, until we reach
     // the end of either the elements or the matchers, or until we find a
     // mismatch.
     for (; it != stl_container.end() && exam_pos != count(); ++it, ++exam_pos) {
       bool match;  // Does the current element match the current matcher?
       if (listener_interested) {
         StringMatchResultListener s;
         match = matchers_[exam_pos].MatchAndExplain(*it, &s);
         explanations[exam_pos] = s.str();
       } else {
         match = matchers_[exam_pos].Matches(*it);
       }
       if (!match) {
         mismatch_found = true;
         break;
       }
     }
     // If mismatch_found is true, 'exam_pos' is the index of the mismatch.
     // Find how many elements the actual container has.  We avoid
     // calling size() s.t. this code works for stream-like "containers"
     // that don't define size().
     size_t actual_count = exam_pos;
     for (; it != stl_container.end(); ++it) {
       ++actual_count;
     }
     if (actual_count != count()) {
       // The element count doesn't match.  If the container is empty,
       // there's no need to explain anything as Google Mock already
       // prints the empty container.  Otherwise we just need to show
       // how many elements there actually are.
       if (listener_interested && (actual_count != 0)) {
         *listener << "which has " << Elements(actual_count);
       }
       return false;
     }
     if (mismatch_found) {
       // The element count matches, but the exam_pos-th element doesn't match.
       if (listener_interested) {
         *listener << "whose element #" << exam_pos << " doesn't match";
         PrintIfNotEmpty(explanations[exam_pos], listener->stream());
       }
       return false;
     }
     // Every element matches its expectation.  We need to explain why
     // (the obvious ones can be skipped).
     if (listener_interested) {
       bool reason_printed = false;
       for (size_t i = 0; i != count(); ++i) {
         const internal::string& s = explanations[i];
         if (!s.empty()) {
           if (reason_printed) {
             *listener << ",\nand ";
           }
           *listener << "whose element #" << i << " matches, " << s;
           reason_printed = true;
         }
       }
     }
     return true;
   }