YOUR NAME's CS132 programs: testing::TestResult::HasFatalFailure
bool testing::TestResult::HasFatalFailure () const
Definition at line 2184 of file gtest.cc.
References testing::internal::CountIf(), and testing::TestPartResult::nonfatally_failed().
Referenced by testing::Test::HasFatalFailure().
{
   return CountIf(test_part_results_, TestPartFatallyFailed) > 0;
 }