YOUR NAME's CS132 programs: testing::internal::UnitTestImpl::GetTestCase
TestCase * testing::internal::UnitTestImpl::GetTestCase (const char * test_case_name, const char * type_param, Test::SetUpTestCaseFunc set_up_tc, Test::TearDownTestCaseFunc tear_down_tc)
Definition at line 4502 of file gtest.cc.
References testing::internal::UnitTestOptions::MatchesFilter(), testing::Environment::SetUp(), testing::Environment::TearDown(), and gmock_test_utils::TestCase.
{
   // Can we find a TestCase with the given name?
   const std::vector<TestCase*>::const_iterator test_case =
       std::find_if(test_cases_.begin(), test_cases_.end(),
                    TestCaseNameIs(test_case_name));
   if (test_case != test_cases_.end())
     return *test_case;
   // No.  Let's create one.
   TestCase* const new_test_case =
       new TestCase(test_case_name, type_param, set_up_tc, tear_down_tc);
   // Is this a death test case?
   if (internal::UnitTestOptions::MatchesFilter(test_case_name,
                                                kDeathTestCaseFilter)) {
     // Yes.  Inserts the test case after the last death test case
     // defined so far.  This only works when the test cases haven't
     // been shuffled.  Otherwise we may end up running a death test
     // after a non-death test.
     ++last_death_test_case_;
     test_cases_.insert(test_cases_.begin() + last_death_test_case_,
                        new_test_case);
   } else {
     // No.  Appends to the end of the list.
     test_cases_.push_back(new_test_case);
   }
   test_case_indices_.push_back(static_cast<int>(test_case_indices_.size()));
   return new_test_case;
 }