YOUR NAME's CS132 programs: testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd
void testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd (const UnitTest & unit_test, int iteration) virtual
Reimplemented from testing::EmptyTestEventListener.
Definition at line 3432 of file gtest.cc.
References testing::internal::posix::FOpen(), testing::internal::String::FormatByte(), testing::Message::GetString(), gmock_output_test::output, versiongenerate::output_dir, testing::internal::FilePath::RemoveFileName(), and testing::internal::StringStreamToString().
{
   FILE* xmlout = NULL;
   FilePath output_file(output_file_);
   FilePath output_dir(output_file.RemoveFileName());
   if (output_dir.CreateDirectoriesRecursively()) {
     xmlout = posix::FOpen(output_file_.c_str(), "w");
   }
   if (xmlout == NULL) {
     // TODO(wan): report the reason of the failure.
     //
     // We don't do it for now as:
     //
     //   1. There is no urgent need for it.
     //   2. It's a bit involved to make the errno variable thread-safe on
     //      all three operating systems (Linux, Windows, and Mac OS).
     //   3. To interpret the meaning of errno in a thread-safe way,
     //      we need the strerror_r() function, which is not available on
     //      Windows.
     fprintf(stderr,
             "Unable to open file \"%s\"\n",
             output_file_.c_str());
     fflush(stderr);
     exit(EXIT_FAILURE);
   }
   std::stringstream stream;
   PrintXmlUnitTest(&stream, unit_test);
   fprintf(xmlout, "%s", StringStreamToString(&stream).c_str());
   fclose(xmlout);
 }