YOUR NAME's CS132 programs: testing::TestInfo::name
const char* testing::TestInfo::name () const inline
Definition at line 654 of file gtest.h.
Referenced by testing::internal::UnitTestImpl::FilterTests(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::TestInfoTest::GetTestInfo(), testing::internal::UnitTestImpl::ListTestsMatchingFilter(), testing::internal::MakeAndRegisterTestInfo(), testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestStart(), testing::internal::ReportFailureInUnknownLocation(), testing::TEST_F(), and testing::internal::TestResultAccessor::test_part_results().
 { return name_.c_str(); }