YOUR NAME's CS132 programs: testing::Action::Perform
template<typename F> Result testing::Action< F >::Perform (const ArgumentTuple & args) const inline
Definition at line 387 of file gmock-actions.h.
Referenced by testing::internal::ActionResultHolder< T >::PerformAction(), testing::internal::ActionResultHolder< void >::PerformAction(), testing::gmock_generated_actions_test::TEST(), and testing::gmock_more_actions_test::TEST().
{
     internal::Assert(
         !IsDoDefault(), __FILE__, __LINE__,
         "You are using DoDefault() inside a composite action like "
         "DoAll() or WithArgs().  This is not supported for technical "
         "reasons.  Please instead spell out the default action, or "
         "assign the default action to an Action variable and use "
         "the variable in various places.");
     return impl_->Perform(args);
   }