YOUR NAME's CS132 programs: testing::TestProperty::key
const char* testing::TestProperty::key () const inline
Definition at line 496 of file gtest.h.
Referenced by testing::TestResult::GetTestProperty(), testing::internal::TestPropertyKeyIs::operator()(), operator<<(), and testing::ValidateTestPropertyName().
{
     return key_.c_str();
   }