YOUR NAME's CS132 programs: Mock::MOCK_METHOD0
Mock::MOCK_METHOD0 (DoThis , void())
Referenced by testing::gmock_nice_strict_test::MockFoo::Delete(), Mock(), and testing::gmock_nice_strict_test::MockBar::str().