YOUR NAME's CS132 programs: testing::internal::UnorderedElementsAreMatcherImpl::MatchAndExplain
template<typename Container > virtual bool testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain (Container container, MatchResultListener * listener) const inline virtual
Implements testing::MatcherInterface< Container >.
Definition at line 3376 of file gmock-matchers.h.
References testing::internal::FindPairing(), GTEST_DISALLOW_ASSIGN_, testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::LhsSize(), testing::Matches(), testing::PrintToString(), and testing::internal::MatchMatrix::SetEdge().
{
     StlContainerReference stl_container = View::ConstReference(container);
     ::std::vector<string> element_printouts;
     MatchMatrix matrix = AnalyzeElements(stl_container.begin(),
                                          stl_container.end(),
                                          &element_printouts,
                                          listener);
     const size_t actual_count = matrix.LhsSize();
     if (actual_count == 0 && matchers_.empty()) {
       return true;
     }
     if (actual_count != matchers_.size()) {
       // The element count doesn't match.  If the container is empty,
       // there's no need to explain anything as Google Mock already
       // prints the empty container. Otherwise we just need to show
       // how many elements there actually are.
       if (actual_count != 0 && listener->IsInterested()) {
         *listener << "which has " << Elements(actual_count);
       }
       return false;
     }
     return VerifyAllElementsAndMatchersAreMatched(element_printouts,
                                                   matrix, listener) &&
            FindPairing(matrix, listener);
   }