YOUR NAME's CS132 programs: testing::gmock_nice_strict_test::MockBar::str
const string& testing::gmock_nice_strict_test::MockBar::str () const inline
Definition at line 100 of file gmock-nice-strict_test.cc.
References testing::internal::CaptureStdout(), testing::gmock_nice_strict_test::Foo::DoThat(), testing::gmock_nice_strict_test::Foo::DoThis(), EXPECT_EQ, EXPECT_THAT, testing::internal::GetCapturedStdout(), GMOCK_FLAG, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::HasSubstr(), testing::Invoke(), Mock::MOCK_METHOD0(), MOCK_METHOD2, ON_CALL, and testing::gmock_nice_strict_test::TEST().
 { return str_; }