YOUR NAME's CS132 programs: main
int main (int argc, char ** argv)
Definition at line 281 of file gmock_output_test_.cc.
References GMOCK_FLAG, testing::InitGoogleMock(), RUN_ALL_TESTS(), and TestCatchesLeakedMocksInAdHocTests().
{
   testing::InitGoogleMock(&argc, argv);
   // Ensures that the tests pass no matter what value of
   // --gmock_catch_leaked_mocks and --gmock_verbose the user specifies.
   testing::GMOCK_FLAG(catch_leaked_mocks) = true;
   testing::GMOCK_FLAG(verbose) = "warning";
   TestCatchesLeakedMocksInAdHocTests();
   return RUN_ALL_TESTS();
 }