YOUR NAME's CS132 programs: TEST
TEST (LinkTest , TestMatcherContainerEq)
Definition at line 596 of file gmock_link_test.h.
References testing::ContainerEq(), ON_CALL, testing::Return(), and Interface::VoidFromVector().
{
   Mock mock;
   std::vector<int> v;
   ON_CALL(mock, VoidFromVector(ContainerEq(v))).WillByDefault(Return());
 }