YOUR NAME's CS132 programs: TEST
TEST (LinkTest , TestMatchersStringEquality)
Definition at line 572 of file gmock_link_test.h.
References ON_CALL, testing::Return(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), testing::StrNe(), and Interface::VoidFromString().
{
   Mock mock;
   ON_CALL(mock, VoidFromString(StrEq("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrNe("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrCaseEq("a"))).WillByDefault(Return());
   ON_CALL(mock, VoidFromString(StrCaseNe("a"))).WillByDefault(Return());
 }