YOUR NAME's CS132 programs: TEST
TEST (LinkTest , TestMatchersFloatingPoint)
Definition at line 537 of file gmock_link_test.h.
References testing::DoubleEq(), testing::FloatEq(), testing::NanSensitiveDoubleEq(), testing::NanSensitiveFloatEq(), ON_CALL, testing::Return(), Interface::VoidFromDouble(), and Interface::VoidFromFloat().
{
   Mock mock;
   float a = 0;
   ON_CALL(mock, VoidFromFloat(FloatEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromDouble(DoubleEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromFloat(NanSensitiveFloatEq(a))).WillByDefault(Return());
   ON_CALL(mock, VoidFromDouble(NanSensitiveDoubleEq(a)))
       .WillByDefault(Return());
 }