YOUR NAME's CS132 programs: TEST
TEST (LinkTest , TestWithArg)
Definition at line 353 of file gmock_link_test.h.
References testing::_, EXPECT_CALL, testing::Invoke(), InvokeHelper::StaticVoidFromString(), and Interface::VoidFromString().
{
   Mock mock;
   EXPECT_CALL(mock, VoidFromString(_))
       .WillOnce(WithArg<0>(Invoke(&InvokeHelper::StaticVoidFromString)));
   mock.VoidFromString(NULL);
 }