YOUR NAME's CS132 programs: TEST
TEST (LinkTest , TestMatcherProperty)
Definition at line 615 of file gmock_link_test.h.
References testing::Eq(), EXPECT_TRUE, FieldHelper::field(), testing::internal::MatcherBase< T >::Matches(), and testing::Property().
{
   FieldHelper helper(0);
   Matcher<const FieldHelper&> m = Property(&FieldHelper::field, Eq(0));
   EXPECT_TRUE(m.Matches(helper));
   Matcher<const FieldHelper*> m2 = Property(&FieldHelper::field, Eq(0));
   EXPECT_TRUE(m2.Matches(&helper));
 }