YOUR NAME's CS132 programs: TEST
TEST (AssertionResultTest , CanStreamOstreamManipulators)
Definition at line 5122 of file gtest_unittest.cc.
References testing::AssertionSuccess(), EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::AssertionResult::message(), and testing::internal::TEST().
{
   AssertionResult r = AssertionSuccess();
   r << "Data" << std::endl << std::flush << std::ends << "Will be visible";
   EXPECT_STREQ("Data\n\\0Will be visible", r.message());
 }