YOUR NAME's CS132 programs: TEST
TEST (EventListenerTest , default_result_printer)
Definition at line 7185 of file gtest_unittest.cc.
References testing::TestEventListeners::default_result_printer(), EXPECT_EQ, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter().
{
   int on_start_counter = 0;
   bool is_destroyed = false;
   TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
   TestEventListeners listeners;
   TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, listener);
   EXPECT_EQ(listener, listeners.default_result_printer());
   TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
       *UnitTest::GetInstance());
   EXPECT_EQ(1, on_start_counter);
   // Replacing default_result_printer with something else should remove it
   // from the list and destroy it.
   TestEventListenersAccessor::SetDefaultResultPrinter(&listeners, NULL);
   EXPECT_TRUE(listeners.default_result_printer() == NULL);
   EXPECT_TRUE(is_destroyed);
   // After broadcasting an event the counter is still the same, indicating
   // the listener is not in the list anymore.
   TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
       *UnitTest::GetInstance());
   EXPECT_EQ(1, on_start_counter);
 }