YOUR NAME's CS132 programs: TEST
TEST (EventListenerTest , SuppressEventForwarding)
Definition at line 7159 of file gtest_unittest.cc.
References testing::TestEventListeners::Append(), ASSERT_FALSE, ASSERT_TRUE, testing::internal::TestEventListenersAccessor::EventForwardingEnabled(), EXPECT_EQ, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), testing::TestEventListener::OnTestProgramStart(), and testing::internal::TestEventListenersAccessor::SuppressEventForwarding().
{
   int on_start_counter = 0;
   TestListener* listener = new TestListener(&on_start_counter, NULL);
   TestEventListeners listeners;
   listeners.Append(listener);
   ASSERT_TRUE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
   TestEventListenersAccessor::SuppressEventForwarding(&listeners);
   ASSERT_FALSE(TestEventListenersAccessor::EventForwardingEnabled(listeners));
   TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
       *UnitTest::GetInstance());
   EXPECT_EQ(0, on_start_counter);
 }