YOUR NAME's CS132 programs: TEST
TEST (TestEventListenersTest , Append)
Definition at line 7043 of file gtest_unittest.cc.
References testing::TestEventListeners::Append(), EXPECT_EQ, EXPECT_TRUE, testing::UnitTest::GetInstance(), testing::internal::TestEventListenersAccessor::GetRepeater(), and testing::TestEventListener::OnTestProgramStart().
{
   int on_start_counter = 0;
   bool is_destroyed = false;
   TestListener* listener = new TestListener(&on_start_counter, &is_destroyed);
   {
     TestEventListeners listeners;
     listeners.Append(listener);
     TestEventListenersAccessor::GetRepeater(&listeners)->OnTestProgramStart(
         *UnitTest::GetInstance());
     EXPECT_EQ(1, on_start_counter);
   }
   EXPECT_TRUE(is_destroyed);
 }