YOUR NAME's CS132 programs: operator<<
::std::ostream& operator<< (::std::ostream & os, const TestingVector & vector)
Definition at line 305 of file gtest_unittest.cc.
References ADD_FAILURE, ASSERT_PRED1, ASSERT_TRUE, testing::internal::String::CaseInsensitiveWideCStringEquals(), testing::internal::TestResultAccessor::ClearTestPartResults(), testing::internal::CodePointToUtf8(), testing::internal::CountIf(), testing::internal::String::EndsWithCaseInsensitive(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_FALSE, EXPECT_FATAL_FAILURE, EXPECT_FATAL_FAILURE_ON_ALL_THREADS, EXPECT_LE, EXPECT_LT, EXPECT_NE, EXPECT_PRED3, EXPECT_STREQ, EXPECT_TRUE, FAIL, testing::TestPartResult::fatally_failed(), testing::internal::ForEach(), testing::internal::FormatEpochTimeInMillisAsIso8601(), testing::internal::FormatTimeInMillisAsSeconds(), testing::internal::Random::Generate(), testing::internal::GetElementOr(), testing::internal::GetNextRandomSeed(), testing::internal::GetRandomSeedFromFlag(), testing::TestPartResultArray::GetTestPartResult(), testing::internal::GetTestTypeId(), testing::internal::GetUnitTestImpl(), GTEST_DISABLE_MSC_WARNINGS_POP_, GTEST_DISABLE_MSC_WARNINGS_PUSH_, GTEST_IS_NULL_LITERAL_, testing::ScopedFakeTestPartResultReporter::INTERCEPT_ALL_THREADS, testing::ScopedFakeTestPartResultReporter::INTERCEPT_ONLY_CURRENT_THREAD, testing::gmock_matchers_test::IsPositive(), testing::TestProperty::key(), testing::internal::kMaxRandomSeed, testing::internal::Random::kMaxRange, testing::internal::kTestTypeIdInGoogleTest, testing::TestPartResult::nonfatally_failed(), testing::internal::Random::Reseed(), testing::internal::String::ShowWideCString(), testing::internal::Shuffle(), testing::internal::ShuffleRange(), testing::TestPartResultArray::size(), testing::internal::TEST(), testing::internal::TEST_F(), testing::TestProperty::value(), and testing::internal::WideStringToUtf8().
{
   os << "{ ";
   for (size_t i = 0; i < vector.size(); i++) {
     os << vector[i] << " ";
   }
   os << "}";
   return os;
 }