YOUR NAME's CS132 programs: RunAllTests
int RunAllTests ()
Definition at line 344 of file gtest_output_test_.cc.
References AdHocTest(), and RUN_ALL_TESTS().
Referenced by main(), and testing::internal::UnitTestImpl::set_current_test_info().
                   {
   AdHocTest();
   return RUN_ALL_TESTS();
 }