YOUR NAME's CS132 programs: PredFormatFunction3
template<typename T1 , typename T2 , typename T3 > testing::AssertionResult PredFormatFunction3 (const char * e1, const char * e2, const char * e3, const T1 & v1, const T2 & v2, const T3 & v3)
Definition at line 919 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction3().
Referenced by PredFormatFunctor3::operator()(), and TEST_F().
{
   if (PredFunction3(v1, v2, v3))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2 << " + " << e3
       << " is expected to be positive, but evaluates to "
       << v1 + v2 + v3 << ".";
 }