YOUR NAME's CS132 programs: TEST
TEST (TestEventListenersTest , DestructionWorks)
Definition at line 7017 of file gtest_unittest.cc.
References testing::TestEventListeners::Append(), EXPECT_TRUE, testing::internal::TestEventListenersAccessor::SetDefaultResultPrinter(), and testing::internal::TestEventListenersAccessor::SetDefaultXmlGenerator().
{
   bool default_result_printer_is_destroyed = false;
   bool default_xml_printer_is_destroyed = false;
   bool extra_listener_is_destroyed = false;
   TestListener* default_result_printer = new TestListener(
       NULL, &default_result_printer_is_destroyed);
   TestListener* default_xml_printer = new TestListener(
       NULL, &default_xml_printer_is_destroyed);
   TestListener* extra_listener = new TestListener(
       NULL, &extra_listener_is_destroyed);
   {
     TestEventListeners listeners;
     TestEventListenersAccessor::SetDefaultResultPrinter(&listeners,
                                                         default_result_printer);
     TestEventListenersAccessor::SetDefaultXmlGenerator(&listeners,
                                                        default_xml_printer);
     listeners.Append(extra_listener);
   }
   EXPECT_TRUE(default_result_printer_is_destroyed);
   EXPECT_TRUE(default_xml_printer_is_destroyed);
   EXPECT_TRUE(extra_listener_is_destroyed);
 }