YOUR NAME's CS132 programs: TEST_P
TEST_P (ValueParamTest , AnotherTestThatHasValueParamAttribute)
Definition at line 147 of file gtest_xml_output_unittest_.cc.
References INSTANTIATE_TEST_CASE_P(), INSTANTIATE_TYPED_TEST_CASE_P(), REGISTER_TYPED_TEST_CASE_P(), testing::Test::Test(), TYPED_TEST(), TYPED_TEST_CASE(), TYPED_TEST_CASE_P(), and TYPED_TEST_P().
 {}