YOUR NAME's CS132 programs: TEST_F
TEST_F (EXPECT_PRED3Test , FunctorOnUserTypeFailure)
Definition at line 1079 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED3, ASSERT_PRED_FORMAT3, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED3, EXPECT_PRED_FORMAT3, PredFormatFunction3(), PredFunction3Bool(), PredFunction3Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED3(PredFunctor3(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++));
     finished_ = true;
   }, "");
 }