YOUR NAME's CS132 programs: main
int main (int argc, char ** argv)
Definition at line 1036 of file gtest-param-test_test.cc.
References testing::AddGlobalTestEnvironment(), testing::InitGoogleTest(), and RUN_ALL_TESTS().
{
 #if GTEST_HAS_PARAM_TEST
   // Used in TestGenerationTest test case.
   AddGlobalTestEnvironment(TestGenerationTest::Environment::Instance());
   // Used in GeneratorEvaluationTest test case. Tests that the updated value
   // will be picked up for instantiating tests in GeneratorEvaluationTest.
   GeneratorEvaluationTest::set_param_value(1);
 #endif  // GTEST_HAS_PARAM_TEST
   ::testing::InitGoogleTest(&argc, argv);
 #if GTEST_HAS_PARAM_TEST
   // Used in GeneratorEvaluationTest test case. Tests that value updated
   // here will NOT be used for instantiating tests in
   // GeneratorEvaluationTest.
   GeneratorEvaluationTest::set_param_value(2);
 #endif  // GTEST_HAS_PARAM_TEST
   return RUN_ALL_TESTS();
 }