YOUR NAME's CS132 programs: PredFormatFunction2
template<typename T1 , typename T2 > testing::AssertionResult PredFormatFunction2 (const char * e1, const char * e2, const T1 & v1, const T2 & v2)
Definition at line 489 of file gtest_pred_impl_unittest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and PredFunction2().
Referenced by PredFormatFunctor2::operator()(), and TEST_F().
{
   if (PredFunction2(v1, v2))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << e1 << " + " << e2
       << " is expected to be positive, but evaluates to "
       << v1 + v2 << ".";
 }