YOUR NAME's CS132 programs: main
int main (int argc, char ** argv)
Definition at line 305 of file gtest_catch_exceptions_test_.cc.
References testing::InitGoogleTest(), RUN_ALL_TESTS(), and TerminateHandler().
{
 #if GTEST_HAS_EXCEPTIONS
   std::set_terminate(&TerminateHandler);
 #endif
   testing::InitGoogleTest(&argc, argv);
   return RUN_ALL_TESTS();
 }