YOUR NAME's CS132 programs: TEST_F
TEST_F (EXPECT_PRED5Test , FunctorOnUserTypeFailure)
Definition at line 2097 of file gtest_pred_impl_unittest.cc.
References ASSERT_PRED5, ASSERT_PRED_FORMAT5, Bool::Bool(), EXPECT_FATAL_FAILURE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED5, EXPECT_PRED_FORMAT5, PredFormatFunction5(), PredFunction5Bool(), PredFunction5Int(), and TEST_F().
{
   EXPECT_NONFATAL_FAILURE({  // NOLINT
     EXPECT_PRED5(PredFunctor5(),
                  Bool(n1_++),
                  Bool(n2_++),
                  Bool(n3_++),
                  Bool(n4_++),
                  Bool(n5_++));
     finished_ = true;
   }, "");
 }