YOUR NAME's CS132 programs: testing::internal::GetCurrentOsStackTraceExceptTop
std::string testing::internal::GetCurrentOsStackTraceExceptTop (UnitTest * unit_test, int skip_count)
Definition at line 4973 of file gtest.cc.
References testing::internal::UnitTestImpl::CurrentOsStackTraceExceptTop(), and GetUnitTestImpl().
Referenced by Log(), and TEST().
{
   // We pass skip_count + 1 to skip this wrapper function in addition
   // to what the user really wants to skip.
   return GetUnitTestImpl()->CurrentOsStackTraceExceptTop(skip_count + 1);
 }