YOUR NAME's CS132 programs: testing::gmock_more_actions_test::TEST
testing::gmock_more_actions_test::TEST (SetArrayArgumentTest , SetsTheNthArray)
Definition at line 621 of file gmock-more-actions_test.cc.
References EXPECT_EQ, std::tr1::make_tuple(), testing::gtest_printers_test::MyFunction(), and testing::Action< F >::Perform().
{
   typedef void MyFunction(bool, int*, char*);
   int numbers[] = { 1, 2, 3 };
   Action<MyFunction> a = SetArrayArgument<1>(numbers, numbers + 3);
   int n[4] = {};
   int* pn = n;
   char ch[4] = {};
   char* pch = ch;
   a.Perform(make_tuple(true, pn, pch));
   EXPECT_EQ(1, n[0]);
   EXPECT_EQ(2, n[1]);
   EXPECT_EQ(3, n[2]);
   EXPECT_EQ(0, n[3]);
   EXPECT_EQ('\0', ch[0]);
   EXPECT_EQ('\0', ch[1]);
   EXPECT_EQ('\0', ch[2]);
   EXPECT_EQ('\0', ch[3]);
   // Tests first and last are iterators.
   std::string letters = "abc";
   a = SetArrayArgument<2>(letters.begin(), letters.end());
   std::fill_n(n, 4, 0);
   std::fill_n(ch, 4, '\0');
   a.Perform(make_tuple(true, pn, pch));
   EXPECT_EQ(0, n[0]);
   EXPECT_EQ(0, n[1]);
   EXPECT_EQ(0, n[2]);
   EXPECT_EQ(0, n[3]);
   EXPECT_EQ('a', ch[0]);
   EXPECT_EQ('b', ch[1]);
   EXPECT_EQ('c', ch[2]);
   EXPECT_EQ('\0', ch[3]);
 }