YOUR NAME's CS132 programs: testing::InitGoogleMock
GTEST_API_ void testing::InitGoogleMock (int * argc, char ** argv)
Definition at line 173 of file gmock.cc.
References testing::internal::InitGoogleMockImpl().
Referenced by main(), and TestInitGoogleMock().
{
   internal::InitGoogleMockImpl(argc, argv);
 }