YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , WorksForLhsNativeArray)
Definition at line 5577 of file gmock-matchers_test.cc.
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), and testing::UnorderedPointwise().
{
   const int lhs[] = {1, 2, 3};
   vector<int> rhs;
   rhs.push_back(4);
   rhs.push_back(6);
   rhs.push_back(2);
   EXPECT_THAT(lhs, UnorderedPointwise(Lt(), rhs));
   EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs)));
 }