YOUR NAME's CS132 programs: testing::internal::WideStringToUtf8
std::string testing::internal::WideStringToUtf8 (const wchar_t * str, int num_chars)
Definition at line 1823 of file gtest.cc.
References CodePointToUtf8(), CreateCodePointFromUtf16SurrogatePair(), IsUtf16SurrogatePair(), and StringStreamToString().
Referenced by operator<<(), testing::internal::String::ShowWideCString(), and testing::internal::GTestFlagSaver::~GTestFlagSaver().
{
   if (num_chars == -1)
     num_chars = static_cast<int>(wcslen(str));
   ::std::stringstream stream;
   for (int i = 0; i < num_chars; ++i) {
     UInt32 unicode_code_point;
     if (str[i] == L'\0') {
       break;
     } else if (i + 1 < num_chars && IsUtf16SurrogatePair(str[i], str[i + 1])) {
       unicode_code_point = CreateCodePointFromUtf16SurrogatePair(str[i],
                                                                  str[i + 1]);
       i++;
     } else {
       unicode_code_point = static_cast<UInt32>(str[i]);
     }
     stream << CodePointToUtf8(unicode_code_point);
   }
   return StringStreamToString(&stream);
 }