YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , DescribesSelf)
Definition at line 5537 of file gmock-matchers_test.cc.
References Describe(), DescribeNegation(), EXPECT_EQ, IsHalfOf(), and testing::UnorderedPointwise().
{
   vector<int> rhs;
   rhs.push_back(1);
   rhs.push_back(2);
   rhs.push_back(3);
   const Matcher<const vector<int>&> m = UnorderedPointwise(IsHalfOf(), rhs);
   EXPECT_EQ(
       "has 3 elements and there exists some permutation of elements such "
       "that:\n"
       " - element #0 and 1 are a pair where the first is half of the second, "
       "and\n"
       " - element #1 and 2 are a pair where the first is half of the second, "
       "and\n"
       " - element #2 and 3 are a pair where the first is half of the second",
       Describe(m));
   EXPECT_EQ(
       "doesn't have 3 elements, or there exists no permutation of elements "
       "such that:\n"
       " - element #0 and 1 are a pair where the first is half of the second, "
       "and\n"
       " - element #1 and 2 are a pair where the first is half of the second, "
       "and\n"
       " - element #2 and 3 are a pair where the first is half of the second",
       DescribeNegation(m));
 }