YOUR NAME's CS132 programs: testing::internal::CountIf
template<class Container , typename Predicate > int testing::internal::CountIf (const Container & c, Predicate predicate) inline
Definition at line 283 of file gtest-internal-inl.h.
References count.
Referenced by testing::TestCase::disabled_test_count(), testing::internal::UnitTestImpl::failed_test_case_count(), testing::TestCase::failed_test_count(), testing::TestResult::HasFatalFailure(), testing::TestResult::HasNonfatalFailure(), operator<<(), testing::TestCase::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::internal::UnitTestImpl::successful_test_case_count(), testing::TestCase::successful_test_count(), testing::internal::UnitTestImpl::test_case_to_run_count(), and testing::TestCase::test_to_run_count().
{
   // Implemented as an explicit loop since std::count_if() in libCstd on
   // Solaris has a non-standard signature.
   int count = 0;
   for (typename Container::const_iterator it = c.begin(); it != c.end(); ++it) {
     if (predicate(*it))
       ++count;
   }
   return count;
 }