YOUR NAME's CS132 programs: testing::internal::EqFailure
AssertionResult testing::internal::EqFailure (const char * expected_expression, const char * actual_expression, const std::string & expected_value, const std::string & actual_value, bool ignoring_case)
Definition at line 1312 of file gtest.cc.
References testing::AssertionFailure(), and testing::internal::edit_distance::CreateUnifiedDiff().
Referenced by CmpHelperEQ(), CmpHelperEQFailure(), CmpHelperFloatingPointEQ(), CmpHelperSTRCASEEQ(), and CmpHelperSTREQ().
{
   Message msg;
   msg << "      Expected: " << lhs_expression;
   if (lhs_value != lhs_expression) {
     msg << "\n      Which is: " << lhs_value;
   }
   msg << "\nTo be equal to: " << rhs_expression;
   if (rhs_value != rhs_expression) {
     msg << "\n      Which is: " << rhs_value;
   }
   if (ignoring_case) {
     msg << "\nIgnoring case";
   }
   if (!lhs_value.empty() && !rhs_value.empty()) {
     const std::vector<std::string> lhs_lines =
         SplitEscapedString(lhs_value);
     const std::vector<std::string> rhs_lines =
         SplitEscapedString(rhs_value);
     if (lhs_lines.size() > 1 || rhs_lines.size() > 1) {
       msg << "\nWith diff:\n"
           << edit_distance::CreateUnifiedDiff(lhs_lines, rhs_lines);
     }
   }
   return AssertionFailure() << msg;
 }