YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (ApiTest , TestCaseDisabledAccessorsWork)
Definition at line 210 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, ASSERT_TRUE, testing::TestCase::disabled_test_count(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::internal::UnitTestHelper::FindTestCase(), testing::TestCase::GetTestInfo(), IsNull(), testing::TestCase::name(), testing::TestCase::should_run(), testing::TestCase::test_to_run_count(), testing::TestCase::total_test_count(), and testing::TestCase::type_param().
{
   const TestCase* test_case = UnitTestHelper::FindTestCase("DISABLED_Test");
   ASSERT_TRUE(test_case != NULL);
   EXPECT_STREQ("DISABLED_Test", test_case->name());
   EXPECT_TRUE(IsNull(test_case->type_param()));
   EXPECT_FALSE(test_case->should_run());
   EXPECT_EQ(1, test_case->disabled_test_count());
   EXPECT_EQ(0, test_case->test_to_run_count());
   ASSERT_EQ(1, test_case->total_test_count());
   const TestInfo* const test_info = test_case->GetTestInfo(0);
   EXPECT_STREQ("Dummy2", test_info->name());
   EXPECT_STREQ("DISABLED_Test", test_info->test_case_name());
   EXPECT_TRUE(IsNull(test_info->value_param()));
   EXPECT_TRUE(IsNull(test_info->type_param()));
   EXPECT_FALSE(test_info->should_run());
 }