YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (BipartiteNonSquareTest , SimpleBacktracking)
Definition at line 5135 of file gmock-matchers_test.cc.
References testing::AnyOf(), testing::internal::MatchMatrix::DebugString(), testing::ElementsAre(), EXPECT_THAT, FindBacktrackingMaxBPM(), GTEST_ARRAY_SIZE_, testing::Pair(), and testing::internal::MatchMatrix::SetEdge().
{
   //   .......
   // 0:-----\ :
   // 1:---\ | :
   // 2:---\ | :
   // 3:-\ | | :
   //  :.......:
   //    0 1 2
   MatchMatrix g(4, 3);
   static const int kEdges[][2] = {{0, 2}, {1, 1}, {2, 1}, {3, 0}};
   for (size_t i = 0; i < GTEST_ARRAY_SIZE_(kEdges); ++i) {
     g.SetEdge(kEdges[i][0], kEdges[i][1], true);
   }
   EXPECT_THAT(FindBacktrackingMaxBPM(g),
               ElementsAre(Pair(3, 0),
                           Pair(AnyOf(1, 2), 1),
                           Pair(0, 2))) << g.DebugString();
 }