YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PropertyForPointerTest , WorksForPointerToNonConst)
Definition at line 3727 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), testing::Property(), testing::gmock_matchers_test::AClass::set_s(), and testing::StartsWith().
{
   Matcher<AClass*> m = Property(&AClass::s, StartsWith("hi"));
   AClass a;
   a.set_s("hill");
   EXPECT_TRUE(m.Matches(&a));
   a.set_s("hole");
   EXPECT_FALSE(m.Matches(&a));
 }