YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , WorksWithUncopyable)
Definition at line 4798 of file gmock-matchers_test.cc.
References EXPECT_THAT, testing::gmock_matchers_test::Uncopyable::set_value(), testing::Truly(), testing::UnorderedElementsAre(), and ValueIsPositive().
{
   Uncopyable objs[2];
   objs[0].set_value(-3);
   objs[1].set_value(1);
   EXPECT_THAT(objs,
               UnorderedElementsAre(Truly(ValueIsPositive), UncopyableIs(-3)));
 }