YOUR NAME's CS132 programs: testing::operator<<
std::ostream& testing::operator<< (std::ostream & os, const Message & sb) inline
Definition at line 232 of file gtest-message.h.
References testing::Message::GetString().
Referenced by testing::TestPartResult::fatally_failed(), testing::Message::Message(), testing::Message::operator<<(), and TEST().
{
   return os << sb.GetString();
 }