YOUR NAME's CS132 programs: testing::internal::PrintTo
template<typename T1 , typename T2 > void testing::internal::PrintTo (const ::std::pair< T1, T2 > & value, ::std::ostream * os)
Definition at line 676 of file gtest-printers.h.
References GTEST_DISABLE_MSC_WARNINGS_PUSH_, and testing::gtest_printers_test::Print().
Referenced by testing::internal::UniversalPrinter< T >::Print(), PrintRawArrayTo(), and PrintTo().
{
   *os << '(';
   // We cannot use UniversalPrint(value.first, os) here, as T1 may be
   // a reference type.  The same for printing value.second.
   UniversalPrinter<T1>::Print(value.first, os);
   *os << ", ";
   UniversalPrinter<T2>::Print(value.second, os);
   *os << ')';
 }