YOUR NAME's CS132 programs: testing::PrintToString
template<typename T > ::std::string testing::PrintToString (const T & value)
Definition at line 980 of file gtest-printers.h.
References testing::internal::UniversalTersePrinter< T >::Print().
Referenced by testing::internal::CmpHelperSTRCASEEQ(), testing::internal::CmpHelperSTREQ(), testing::internal::CmpHelperSTRNE(), testing::internal::FormatForComparison< ToPrint, OtherOperand >::Format(), testing::internal::ArgsMatcherImpl< ArgsTuple, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::MatchAndExplain(), testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain(), and testing::gmock_matchers_test::TEST_P().
{
   ::std::stringstream ss;
   internal::UniversalTersePrinter<T>::Print(value, &ss);
   return ss.str();
 }