YOUR NAME's CS132 programs: gtest_shuffle_test.GetTestsForAllIterations
def gtest_shuffle_test.GetTestsForAllIterations (extra_env, args)
Runs the test program and returns a list of test lists.
Args:
  extra_env: a map from environment variables to their values
  args: command line flags to pass to gtest_shuffle_test_
Returns:
  A list where the i-th element is the list of tests run in the i-th
  test iteration.
Definition at line 87 of file gtest_shuffle_test.py.
References RunAndReturnOutput().
Referenced by CalculateTestLists(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleGeneratesNewOrderInEachIteration(), gtest_shuffle_test.GTestShuffleUnitTest.testShuffleRestoresOrderAfterEachIteration(), and gtest_shuffle_test.GTestShuffleUnitTest.testShuffleShardedTestsPreservesPartition().
 def GetTestsForAllIterations(extra_env, args):
   """Runs the test program and returns a list of test lists.
   Args:
     extra_env: a map from environment variables to their values
     args: command line flags to pass to gtest_shuffle_test_
   Returns:
     A list where the i-th element is the list of tests run in the i-th
     test iteration.
   """
   test_iterations = []
   for line in RunAndReturnOutput(extra_env, args).split('\n'):
     if line.startswith('----'):
       tests = []
       test_iterations.append(tests)
     elif line.strip():
       tests.append(line.strip())  # 'TestCaseName.TestName'
   return test_iterations