YOUR NAME's CS132 programs: testing::internal::ShouldUseColor
bool testing::internal::ShouldUseColor (bool stdout_is_tty)
Definition at line 2916 of file gtest.cc.
References CaseInsensitiveCStringEquals(), testing::internal::posix::GetEnv(), and GTEST_FLAG.
Referenced by ColoredPrintf(), main(), and TEST().
{
   const char* const gtest_color = GTEST_FLAG(color).c_str();
   if (String::CaseInsensitiveCStringEquals(gtest_color, "auto")) {
 #if GTEST_OS_WINDOWS
     // On Windows the TERM variable is usually not set, but the
     // console there does support colors.
     return stdout_is_tty;
 #else
     // On non-Windows platforms, we rely on the TERM variable.
     const char* const term = posix::GetEnv("TERM");
     const bool term_supports_color =
         String::CStringEquals(term, "xterm") ||
         String::CStringEquals(term, "xterm-color") ||
         String::CStringEquals(term, "xterm-256color") ||
         String::CStringEquals(term, "screen") ||
         String::CStringEquals(term, "screen-256color") ||
         String::CStringEquals(term, "tmux") ||
         String::CStringEquals(term, "tmux-256color") ||
         String::CStringEquals(term, "rxvt-unicode") ||
         String::CStringEquals(term, "rxvt-unicode-256color") ||
         String::CStringEquals(term, "linux") ||
         String::CStringEquals(term, "cygwin");
     return stdout_is_tty && term_supports_color;
 #endif  // GTEST_OS_WINDOWS
   }
   return String::CaseInsensitiveCStringEquals(gtest_color, "yes") ||
       String::CaseInsensitiveCStringEquals(gtest_color, "true") ||
       String::CaseInsensitiveCStringEquals(gtest_color, "t") ||
       String::CStringEquals(gtest_color, "1");
   // We take "yes", "true", "t", and "1" as meaning "yes".  If the
   // value is neither one of these nor "auto", we treat it as "no" to
   // be conservative.
 }