YOUR NAME's CS132 programs: testing::internal::CmpHelperEQ
template<typename T1 , typename T2 > AssertionResult testing::internal::CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1387 of file gtest.h.
References testing::AssertionSuccess(), CmpHelperEQFailure(), GTEST_API_, GTEST_DISABLE_MSC_WARNINGS_POP_, and GTEST_DISABLE_MSC_WARNINGS_PUSH_.
Referenced by testing::internal::EqHelper< lhs_is_null_literal >::Compare(), and testing::internal::EqHelper< true >::Compare().
{
 GTEST_DISABLE_MSC_WARNINGS_PUSH_(4389 /* signed/unsigned mismatch */)
   if (lhs == rhs) {
     return AssertionSuccess();
   }
 GTEST_DISABLE_MSC_WARNINGS_POP_()
   return CmpHelperEQFailure(lhs_expression, rhs_expression, lhs, rhs);
 }