YOUR NAME's CS132 programs: testing::ContainsRegex
PolymorphicMatcher<internal::MatchesRegexMatcher> testing::ContainsRegex (const internal::RE * regex) inline
Definition at line 4016 of file gmock-matchers.h.
References MakePolymorphicMatcher().
Referenced by ContainsRegex(), testing::internal::ExpectationTester::SetCallCount(), TEST(), and testing::gmock_matchers_test::TEST().
{
   return MakePolymorphicMatcher(internal::MatchesRegexMatcher(regex, false));
 }