YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PointeeTest , WorksWithConstPropagatingPointers)
Definition at line 3304 of file gmock-matchers_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, testing::Lt(), testing::internal::MatcherBase< T >::Matches(), and testing::Pointee().
{
   const Matcher< ConstPropagatingPtr<int> > m = Pointee(Lt(5));
   int three = 3;
   const ConstPropagatingPtr<int> co(&three);
   ConstPropagatingPtr<int> o(&three);
   EXPECT_TRUE(m.Matches(o));
   EXPECT_TRUE(m.Matches(co));
   *o = 6;
   EXPECT_FALSE(m.Matches(o));
   EXPECT_FALSE(m.Matches(ConstPropagatingPtr<int>()));
 }