YOUR NAME's CS132 programs: gtest_env_var_test.SetEnvVar
def gtest_env_var_test.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 55 of file gtest_env_var_test.py.
Referenced by gtest_env_var_test.GTestEnvVarTest.testEnvVarAffectsFlag(), TestFlag(), gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def SetEnvVar(env_var, value):
   """Sets the env variable to 'value'; unsets it when 'value' is None."""
   if value is not None:
     environ[env_var] = value
   elif env_var in environ:
     del environ[env_var]