YOUR NAME's CS132 programs: gtest_filter_unittest.InvokeWithModifiedEnv
def gtest_filter_unittest.InvokeWithModifiedEnv (extra_env, function, args, kwargs)
Runs the given function and arguments in a modified environment.
Definition at line 207 of file gtest_filter_unittest.py.
Referenced by RunWithSharding(), gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreated(), and gtest_filter_unittest.GTestFilterUnitTest.testShardStatusFileIsCreatedWithListTests().
 def InvokeWithModifiedEnv(extra_env, function, *args, **kwargs):
   """Runs the given function and arguments in a modified environment."""
   try:
     original_env = environ.copy()
     environ.update(extra_env)
     return function(*args, **kwargs)
   finally:
     environ.clear()
     environ.update(original_env)