YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PolymorphicMatcherTest , CanAccessMutableImpl)
Definition at line 5283 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::DivisibleByImpl::divider(), EXPECT_EQ, testing::PolymorphicMatcher< Impl >::mutable_impl(), and testing::gmock_matchers_test::DivisibleByImpl::set_divider().
{
   PolymorphicMatcher<DivisibleByImpl> m(DivisibleByImpl(42));
   DivisibleByImpl& impl = m.mutable_impl();
   EXPECT_EQ(42, impl.divider());
   impl.set_divider(0);
   EXPECT_EQ(0, m.mutable_impl().divider());
 }