YOUR NAME's CS132 programs: testing::MakePolymorphicAction
template<typename Impl > PolymorphicAction<Impl> testing::MakePolymorphicAction (const Impl & impl) inline
Definition at line 475 of file gmock-actions.h.
Referenced by Assign(), Invoke(), InvokeWithoutArgs(), Return(), ReturnNull(), SetArgPointee(), SetArgumentPointee(), and SetErrnoAndReturn().
{
   return PolymorphicAction<Impl>(impl);
 }