YOUR NAME's CS132 programs: testing::Args
template<typename InnerMatcher > internal::ArgsMatcher<InnerMatcher> testing::Args (const InnerMatcher & matcher) inline
Definition at line 481 of file gmock-generated-matchers.h.
Referenced by ElementsAre(), ExplainMatchResult(), testing::internal::BothOfMatcherImpl< T >::MatchAndExplain(), testing::internal::EitherOfMatcherImpl< T >::MatchAndExplain(), and UnorderedElementsAre().
{
   return internal::ArgsMatcher<InnerMatcher>(matcher);
 }