YOUR NAME's CS132 programs: testing::internal::MakeAndRegisterTestInfo
TestInfo * testing::internal::MakeAndRegisterTestInfo (const char * test_case_name, const char * name, const char * type_param, const char * value_param, CodeLocation code_location, TypeId fixture_class_id, SetUpTestCaseFunc set_up_tc, TearDownTestCaseFunc tear_down_tc, TestFactoryBase * factory)
Definition at line 2543 of file gtest.cc.
References testing::internal::UnitTestImpl::AddTestInfo(), testing::internal::CodeLocation::file, FormatFileLocation(), testing::Message::GetString(), GetUnitTestImpl(), testing::internal::CodeLocation::line, testing::TestInfo::name(), and testing::Test::TestInfo.
{
   TestInfo* const test_info =
       new TestInfo(test_case_name, name, type_param, value_param,
                    code_location, fixture_class_id, factory);
   GetUnitTestImpl()->AddTestInfo(set_up_tc, tear_down_tc, test_info);
   return test_info;
 }