YOUR NAME's CS132 programs: testing::internal::IsNull
AssertionResult testing::internal::IsNull (const char * str)
Definition at line 140 of file gtest-unittest-api_test.cc.
References testing::AssertionFailure(), and testing::AssertionSuccess().
Referenced by testing::gmock_matchers_test::MATCHER_P(), testing::internal::FinalSuccessChecker::TearDown(), TEST(), and testing::gmock_matchers_test::TEST().
{
   if (str != NULL) {
     return testing::AssertionFailure() << "argument is " << str;
   }
   return AssertionSuccess();
 }