YOUR NAME's CS132 programs: testing::internal::FormatEpochTimeInMillisAsIso8601
std::string testing::internal::FormatEpochTimeInMillisAsIso8601 (TimeInMillis ms)
Definition at line 3574 of file gtest.cc.
References testing::TestCase::ad_hoc_test_result(), testing::UnitTest::ad_hoc_test_result(), testing::TestResult::elapsed_time(), testing::TestCase::elapsed_time(), testing::UnitTest::elapsed_time(), testing::TestPartResult::failed(), testing::TestCase::failed_test_count(), testing::UnitTest::failed_test_count(), testing::TestPartResult::file_name(), testing::internal::String::FormatByte(), FormatCompilerIndependentFileLocation(), testing::internal::String::FormatIntWidth2(), FormatTimeInMillisAsSeconds(), testing::Message::GetString(), testing::UnitTest::GetTestCase(), testing::TestCase::GetTestInfo(), testing::TestResult::GetTestPartResult(), testing::TestResult::GetTestProperty(), GTEST_CHECK_, GTEST_FLAG, GTEST_LOG_, testing::TestInfo::is_reportable(), testing::TestPartResult::line_number(), testing::TestPartResult::message(), testing::TestInfo::name(), testing::TestCase::name(), testing::UnitTest::random_seed(), testing::TestCase::reportable_disabled_test_count(), testing::UnitTest::reportable_disabled_test_count(), testing::TestCase::reportable_test_count(), testing::UnitTest::reportable_test_count(), testing::TestInfo::result(), testing::TestInfo::should_run(), testing::UnitTest::start_timestamp(), StreamableToString(), testing::TestPartResult::summary(), testing::TestResult::test_property_count(), testing::TestResult::total_part_count(), testing::UnitTest::total_test_case_count(), testing::TestCase::total_test_count(), testing::TestInfo::type_param(), and testing::TestInfo::value_param().
Referenced by operator<<().
{
   struct tm time_struct;
   if (!PortableLocaltime(static_cast<time_t>(ms / 1000), &time_struct))
     return "";
   // YYYY-MM-DDThh:mm:ss
   return StreamableToString(time_struct.tm_year + 1900) + "-" +
       String::FormatIntWidth2(time_struct.tm_mon + 1) + "-" +
       String::FormatIntWidth2(time_struct.tm_mday) + "T" +
       String::FormatIntWidth2(time_struct.tm_hour) + ":" +
       String::FormatIntWidth2(time_struct.tm_min) + ":" +
       String::FormatIntWidth2(time_struct.tm_sec);
 }