YOUR NAME's CS132 programs: testing::internal::FormatFileLocation
GTEST_API_::std::string testing::internal::FormatFileLocation (const char * file, int line)
Definition at line 880 of file gtest-port.cc.
References StreamableToString().
Referenced by testing::internal::ExpectationBase::DescribeLocationTo(), testing::TestCase::GetTestInfo(), testing::internal::GTestLog::GTestLog(), testing::UnitTest::listeners(), MakeAndRegisterTestInfo(), testing::internal::RE::PartialMatch(), testing::internal::ExpectationTester::SetCallCount(), and TEST().
{
   const std::string file_name(file == NULL ? kUnknownFile : file);
   if (line < 0) {
     return file_name + ":";
   }
 #ifdef _MSC_VER
   return file_name + "(" + StreamableToString(line) + "):";
 #else
   return file_name + ":" + StreamableToString(line) + ":";
 #endif  // _MSC_VER
 }