YOUR NAME's CS132 programs: upload.GuessVCS
def upload.GuessVCS (options)
Helper to guess the version control system.
This examines the current directory, guesses which VersionControlSystem
we're using, and returns an instance of the appropriate class.  Exit with an
error if we can't figure it out.
Returns:
  A VersionControlSystem instance. Exits if the VCS can't be guessed.
Definition at line 1209 of file upload.py.
References ErrorExit(), and RunShellWithReturnCode().
Referenced by upload.MercurialVCS.GetBaseFile(), and RealMain().
 def GuessVCS(options):
   """Helper to guess the version control system.
   This examines the current directory, guesses which VersionControlSystem
   we're using, and returns an instance of the appropriate class.  Exit with an
   error if we can't figure it out.
   Returns:
     A VersionControlSystem instance. Exits if the VCS can't be guessed.
   """
   # Mercurial has a command to get the base directory of a repository
   # Try running it, but don't die if we don't have hg installed.
   # NOTE: we try Mercurial first as it can sit on top of an SVN working copy.
   try:
     out, returncode = RunShellWithReturnCode(["hg", "root"])
     if returncode == 0:
       return MercurialVCS(options, out.strip())
   except OSError, (errno, message):
     if errno != 2:  # ENOENT -- they don't have hg installed.
       raise
   # Subversion has a .svn in all working directories.
   if os.path.isdir('.svn'):
     logging.info("Guessed VCS = Subversion")
     return SubversionVCS(options)
   # Git has a command to test if you're in a git tree.
   # Try running it, but don't die if we don't have git installed.
   try:
     out, returncode = RunShellWithReturnCode(["git", "rev-parse",
                                               "--is-inside-work-tree"])
     if returncode == 0:
       return GitVCS(options)
   except OSError, (errno, message):
     if errno != 2:  # ENOENT -- they don't have git installed.
       raise
   ErrorExit(("Could not guess version control system. "
              "Are you in a working copy directory?"))