YOUR NAME's CS132 programs: testing::gmock_more_actions_test::TEST
testing::gmock_more_actions_test::TEST (InvokeMethodTest , Binary)
Definition at line 380 of file gmock-more-actions_test.cc.
References testing::gmock_more_actions_test::Foo::Binary(), EXPECT_EQ, testing::gmock_matchers_test::foo, testing::Invoke(), and testing::Action< F >::Perform().
{
   Foo foo;
   Action<string(const string&, char)> a = Invoke(&foo, &Foo::Binary);
   string s("Hell");
   EXPECT_EQ("Hello", a.Perform(
       tuple<const string&, char>(s, 'o')));
 }