YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AllArgsTest , WorksInWithClause)
Definition at line 2606 of file gmock-matchers_test.cc.
References testing::_, testing::AllArgs(), EXPECT_CALL, EXPECT_EQ, testing::Gt(), testing::Lt(), ON_CALL, and testing::Return().
{
   AllArgsHelper helper;
   ON_CALL(helper, Helper(_, _))
       .With(AllArgs(Lt()))
       .WillByDefault(Return(1));
   EXPECT_CALL(helper, Helper(_, _));
   EXPECT_CALL(helper, Helper(_, _))
       .With(AllArgs(Gt()))
       .WillOnce(Return(2));
   EXPECT_EQ(1, helper.Helper('\1', 2));
   EXPECT_EQ(2, helper.Helper('a', 1));
 }