YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageImperfectMatchOnly)
Definition at line 4946 of file gmock-matchers_test.cc.
References testing::AnyOf(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
{
   // A situation where all elements and matchers have a match
   // associated with them, but the max matching is not perfect.
   std::vector<string> v;
   v.push_back("a");
   v.push_back("b");
   v.push_back("c");
   StringMatchResultListener listener;
   EXPECT_FALSE(ExplainMatchResult(
       UnorderedElementsAre("a", "a", AnyOf("b", "c")), v, &listener))
       << listener.str();
   string prefix =
       "where no permutation of the elements can satisfy all matchers, "
       "and the closest match is 2 of 3 matchers with the "
       "pairings:\n";
   // We have to be a bit loose here, because there are 4 valid max matches.
   EXPECT_THAT(
       listener.str(),
       AnyOf(prefix + "{\n  " + EMString(0, 0) +
                      ",\n  " + EMString(1, 2) + "\n}",
             prefix + "{\n  " + EMString(0, 1) +
                      ",\n  " + EMString(1, 2) + "\n}",
             prefix + "{\n  " + EMString(0, 0) +
                      ",\n  " + EMString(2, 2) + "\n}",
             prefix + "{\n  " + EMString(0, 1) +
                      ",\n  " + EMString(2, 2) + "\n}"));
 }