YOUR NAME's CS132 programs: testing::TYPED_TEST
testing::TYPED_TEST (CodeLocationForTYPEDTEST , Verify)
Definition at line 5370 of file gtest_unittest.cc.
References VERIFY_CODE_LOCATION.
Referenced by testing::internal::UnitTestHelper::GetSortedTests(), testing::internal::TEST(), and testing::gmock_matchers_test::TEST().
{
   VERIFY_CODE_LOCATION;
 }