YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AllOfTest , CanDescribeNegation)
Definition at line 2154 of file gmock-matchers_test.cc.
References testing::AllOf(), DescribeNegation(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), and testing::Ne().
{
   Matcher<int> m;
   m = AllOf(Le(2), Ge(1));
   EXPECT_EQ("(isn't <= 2) or "
             "(isn't >= 1)",
             DescribeNegation(m));
   m = AllOf(Gt(0), Ne(1), Ne(2));
   EXPECT_EQ("(isn't > 0) or "
             "((is equal to 1) or "
             "(is equal to 2))",
             DescribeNegation(m));
   m = AllOf(Gt(0), Ne(1), Ne(2), Ne(3));
   EXPECT_EQ("((isn't > 0) or "
             "(is equal to 1)) or "
             "((is equal to 2) or "
             "(is equal to 3))",
             DescribeNegation(m));
   m = AllOf(Ge(0), Lt(10), Ne(3), Ne(5), Ne(7));
   EXPECT_EQ("((isn't >= 0) or "
             "(isn't < 10)) or "
             "((is equal to 3) or "
             "((is equal to 5) or "
             "(is equal to 7)))",
             DescribeNegation(m));
 }