YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (ApiTest , UnitTestImmutableAccessorsWork)
Definition at line 114 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, testing::UnitTest::disabled_test_count(), EXPECT_EQ, EXPECT_STREQ, testing::UnitTest::GetInstance(), testing::internal::UnitTestHelper::GetSortedTestCases(), testing::UnitTest::test_case_to_run_count(), testing::UnitTest::test_to_run_count(), testing::UnitTest::total_test_case_count(), and testing::UnitTest::total_test_count().
{
   UnitTest* unit_test = UnitTest::GetInstance();
   ASSERT_EQ(2 + kTypedTestCases, unit_test->total_test_case_count());
   EXPECT_EQ(1 + kTypedTestCases, unit_test->test_case_to_run_count());
   EXPECT_EQ(2, unit_test->disabled_test_count());
   EXPECT_EQ(5 + kTypedTests, unit_test->total_test_count());
   EXPECT_EQ(3 + kTypedTests, unit_test->test_to_run_count());
   const TestCase** const test_cases = UnitTestHelper::GetSortedTestCases();
   EXPECT_STREQ("ApiTest", test_cases[0]->name());
   EXPECT_STREQ("DISABLED_Test", test_cases[1]->name());
 #if GTEST_HAS_TYPED_TEST
   EXPECT_STREQ("TestCaseWithCommentTest/0", test_cases[2]->name());
 #endif  // GTEST_HAS_TYPED_TEST
   delete[] test_cases;
   // The following lines initiate actions to verify certain methods in
   // FinalSuccessChecker::TearDown.
   // Records a test property to verify TestResult::GetTestProperty().
   RecordProperty("key", "value");
 }