YOUR NAME's CS132 programs: pump.FindFirst
def pump.FindFirst (lines, token_table, cursor)
Finds the first occurrence of any string in strings in lines.
Definition at line 186 of file pump.py.
References FindFirstInLine(), and MakeToken().
Referenced by TokenizeLines().
 def FindFirst(lines, token_table, cursor):
   """Finds the first occurrence of any string in strings in lines."""
   start = cursor.Clone()
   cur_line_number = cursor.line
   for line in lines[start.line:]:
     if cur_line_number == start.line:
       line = line[start.column:]
     m = FindFirstInLine(line, token_table)
     if m:
       # We found a regex in line.
       (start_column, length, token_type) = m
       if cur_line_number == start.line:
         start_column += start.column
       found_start = Cursor(cur_line_number, start_column)
       found_end = found_start + length
       return MakeToken(lines, found_start, found_end, token_type)
     cur_line_number += 1
   # We failed to find str in lines
   return None