YOUR NAME's CS132 programs: gen_gtest_pred_impl.OneTo
def gen_gtest_pred_impl.OneTo (n)
Returns the list [1, 2, 3, ..., n].
Definition at line 183 of file gen_gtest_pred_impl.py.
Referenced by GenerateHeader(), GenerateUnitTest(), Iter(), and TestsForArity().
 def OneTo(n):
   """Returns the list [1, 2, 3, ..., n]."""
   return range(1, n + 1)