YOUR NAME's CS132 programs: testing::Between
GTEST_API_ Cardinality testing::Between (int min, int max)
Definition at line 149 of file gmock-cardinalities.cc.
Referenced by AtLeast(), AtMost(), testing::Cardinality::DescribeTo(), Exactly(), and testing::internal::ExpectationTester::SetCallCount().
{
   return Cardinality(new BetweenCardinalityImpl(min, max));
 }