YOUR NAME's CS132 programs: testing::internal::CmpHelperSTREQ
AssertionResult testing::internal::CmpHelperSTREQ (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
Definition at line 1869 of file gtest.cc.
References testing::AssertionSuccess(), EqFailure(), and testing::PrintToString().
{
   if (String::WideCStringEquals(lhs, rhs)) {
     return AssertionSuccess();
   }
   return EqFailure(lhs_expression,
                    rhs_expression,
                    PrintToString(lhs),
                    PrintToString(rhs),
                    false);
 }