YOUR NAME's CS132 programs: testing::Not
template<typename InnerMatcher > internal::NotMatcher<InnerMatcher> testing::Not (InnerMatcher m) inline
Definition at line 4107 of file gmock-matchers.h.
Referenced by testing::gmock_matchers_test::MATCHER_P(), testing::gmock_matchers_test::TEST(), TEST(), and testing::gmock_matchers_test::TEST_F().
{
   return internal::NotMatcher<InnerMatcher>(m);
 }