YOUR NAME's CS132 programs: gtest_env_var_test.AssertEq
def gtest_env_var_test.AssertEq (expected, actual)
Definition at line 48 of file gtest_env_var_test.py.
Referenced by TestFlag(), gtest_env_var_test.GTestEnvVarTest.testXmlOutputFile(), and gtest_env_var_test.GTestEnvVarTest.testXmlOutputFileOverride().
 def AssertEq(expected, actual):
   if expected != actual:
     print('Expected: %s' % (expected,))
     print('  Actual: %s' % (actual,))
     raise AssertionError