YOUR NAME's CS132 programs: testing::internal::ShouldShard
bool testing::internal::ShouldShard (const char * total_shards_str, const char * shard_index_str, bool in_subprocess_for_death_test)
Definition at line 4715 of file gtest.cc.
References COLOR_RED, ColoredPrintf(), testing::Message::GetString(), and Int32FromEnvOrDie().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::GTestFlagSaver::~GTestFlagSaver().
{
   if (in_subprocess_for_death_test) {
     return false;
   }
   const Int32 total_shards = Int32FromEnvOrDie(total_shards_env, -1);
   const Int32 shard_index = Int32FromEnvOrDie(shard_index_env, -1);
   if (total_shards == -1 && shard_index == -1) {
     return false;
   } else if (total_shards == -1 && shard_index != -1) {
     const Message msg = Message()
       << "Invalid environment variables: you have "
       << kTestShardIndex << " = " << shard_index
       << ", but have left " << kTestTotalShards << " unset.\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   } else if (total_shards != -1 && shard_index == -1) {
     const Message msg = Message()
       << "Invalid environment variables: you have "
       << kTestTotalShards << " = " << total_shards
       << ", but have left " << kTestShardIndex << " unset.\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   } else if (shard_index < 0 || shard_index >= total_shards) {
     const Message msg = Message()
       << "Invalid environment variables: we require 0 <= "
       << kTestShardIndex << " < " << kTestTotalShards
       << ", but you have " << kTestShardIndex << "=" << shard_index
       << ", " << kTestTotalShards << "=" << total_shards << ".\n";
     ColoredPrintf(COLOR_RED, msg.GetString().c_str());
     fflush(stdout);
     exit(EXIT_FAILURE);
   }
   return total_shards > 1;
 }