YOUR NAME's CS132 programs: testing::internal::CmpHelperEQ
AssertionResult testing::internal::CmpHelperEQ (const char * lhs_expression, const char * rhs_expression, BiggestInt lhs, BiggestInt rhs)
Definition at line 1437 of file gtest.cc.
References testing::AssertionSuccess(), EqFailure(), and FormatForComparisonFailureMessage().
{
   if (lhs == rhs) {
     return AssertionSuccess();
   }
   return EqFailure(lhs_expression,
                    rhs_expression,
                    FormatForComparisonFailureMessage(lhs, rhs),
                    FormatForComparisonFailureMessage(rhs, lhs),
                    false);
 }