YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (EachTest , MatchesVectorWhenAllElementsMatch)
Definition at line 5358 of file gmock-matchers_test.cc.
References testing::Each(), EXPECT_THAT, testing::Lt(), and testing::Not().
{
   vector<int> some_vector;
   EXPECT_THAT(some_vector, Each(1));
   some_vector.push_back(3);
   EXPECT_THAT(some_vector, Not(Each(1)));
   EXPECT_THAT(some_vector, Each(3));
   some_vector.push_back(1);
   some_vector.push_back(2);
   EXPECT_THAT(some_vector, Not(Each(3)));
   EXPECT_THAT(some_vector, Each(Lt(3.5)));
   vector<string> another_vector;
   another_vector.push_back("fee");
   EXPECT_THAT(another_vector, Each(string("fee")));
   another_vector.push_back("fie");
   another_vector.push_back("foe");
   another_vector.push_back("fum");
   EXPECT_THAT(another_vector, Not(Each(string("fee"))));
 }