YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForNativeArrayAsTuple)
Definition at line 4333 of file gmock-matchers_test.cc.
References testing::ContainerEq(), EXPECT_THAT, std::tr1::make_tuple(), and testing::Not().
{
   const int a1[] = {1, 2, 3};
   const int a2[] = {1, 2, 3};
   const int b[] = {1, 2, 3, 4};
   const int* const p1 = a1;
   EXPECT_THAT(make_tuple(p1, 3), ContainerEq(a2));
   EXPECT_THAT(make_tuple(p1, 3), Not(ContainerEq(b)));
   const int c[] = {1, 3, 2};
   EXPECT_THAT(make_tuple(p1, 3), Not(ContainerEq(c)));
 }