YOUR NAME's CS132 programs: upload.main
def upload.main ()
Definition at line 1377 of file upload.py.
References RealMain(), and StatusUpdate().
Referenced by upload.MercurialVCS.GetBaseFile().
 def main():
   try:
     RealMain(sys.argv)
   except KeyboardInterrupt:
     print
     StatusUpdate("Interrupted.")
     sys.exit(1)