YOUR NAME's CS132 programs: testing::internal::TransformTupleValues
template<typename Tuple , typename Func , typename OutIter > OutIter testing::internal::TransformTupleValues (Func f, const Tuple & t, OutIter out)
Definition at line 853 of file gmock-matchers.h.
References gtest_break_on_failure_unittest::Run().
Referenced by testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), and testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container >().
{
   return TransformTupleValuesHelper<Tuple, Func, OutIter>::Run(f, t, out);
 }