YOUR NAME's CS132 programs: testing::internal::CmpHelperSTRCASENE
AssertionResult testing::internal::CmpHelperSTRCASENE (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
Definition at line 1533 of file gtest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and CaseInsensitiveCStringEquals().
{
   if (!String::CaseInsensitiveCStringEquals(s1, s2)) {
     return AssertionSuccess();
   } else {
     return AssertionFailure()
         << "Expected: (" << s1_expression << ") != ("
         << s2_expression << ") (ignoring case), actual: \""
         << s1 << "\" vs \"" << s2 << "\"";
   }
 }