YOUR NAME's CS132 programs: testing::gmock_generated_actions_test::TEST
testing::gmock_generated_actions_test::TEST (WithArgsTest , RepeatedArguments)
Definition at line 391 of file gmock-generated-actions_test.cc.
References EXPECT_EQ, testing::Invoke(), std::tr1::make_tuple(), testing::Action< F >::Perform(), and SumOf4().
{
   Action<int(bool, int m, int n)> a =  // NOLINT
       WithArgs<1, 1, 1, 1>(Invoke(SumOf4));
   EXPECT_EQ(4, a.Perform(make_tuple(false, 1, 10)));
 }