YOUR NAME's CS132 programs: gtest_filter_unittest.SetEnvVar
def gtest_filter_unittest.SetEnvVar (env_var, value)
Sets the env variable to 'value'; unsets it when 'value' is None.
Definition at line 172 of file gtest_filter_unittest.py.
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyWithSharding(), and gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar().
 def SetEnvVar(env_var, value):
   """Sets the env variable to 'value'; unsets it when 'value' is None."""
   if value is not None:
     environ[env_var] = value
   elif env_var in environ:
     del environ[env_var]