YOUR NAME's CS132 programs: testing::internal::ArrayAwareFind
template<typename Iter , typename Element > Iter testing::internal::ArrayAwareFind (Iter begin, Iter end, const Element & elem)
Definition at line 983 of file gtest-internal.h.
References ArrayEq(), CopyArray(), and gen_gtest_pred_impl::Iter().
Referenced by testing::internal::ContainerEqMatcher< Container >::MatchAndExplain(), and TEST().
{
   for (Iter it = begin; it != end; ++it) {
     if (internal::ArrayEq(*it, elem))
       return it;
   }
   return end;
 }