YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ContainsRegexTest , CanDescribeSelf)
Definition at line 1538 of file gmock-matchers_test.cc.
References testing::ContainsRegex(), Describe(), testing::EndsWith(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, testing::HasSubstr(), testing::internal::MatcherBase< T >::Matches(), testing::StartsWith(), testing::StrCaseEq(), testing::StrCaseNe(), testing::StrEq(), testing::StrNe(), and testing::internal::TEST().
{
   Matcher<const std::string> m1 = ContainsRegex("Hi.*");
   EXPECT_EQ("contains regular expression \"Hi.*\"", Describe(m1));
   Matcher<const char*> m2 = ContainsRegex(new RE("a.*"));
   EXPECT_EQ("contains regular expression \"a.*\"", Describe(m2));
 }