YOUR NAME's CS132 programs: testing::gmock_more_actions_test::TEST
testing::gmock_more_actions_test::TEST (DeleteArgActionTest , TenArgs)
Definition at line 588 of file gmock-more-actions_test.cc.
References CharPtr(), EXPECT_FALSE, EXPECT_THROW, EXPECT_TRUE, std::tr1::make_tuple(), testing::Action< F >::Perform(), and TEST().
{
   bool is_deleted = false;
   DeletionTester* t = new DeletionTester(&is_deleted);
   const Action<void(bool, int, int, const char*, bool,
                     int, int, int, int, DeletionTester*)> a1 = DeleteArg<9>();
   EXPECT_FALSE(is_deleted);
   a1.Perform(make_tuple(true, 5, 6, CharPtr("hi"), false, 7, 8, 9, 10, t));
   EXPECT_TRUE(is_deleted);
 }