YOUR NAME's CS132 programs: testing::internal::CmpHelperFloatingPointEQ
template<typename RawType > AssertionResult testing::internal::CmpHelperFloatingPointEQ (const char * lhs_expression, const char * rhs_expression, RawType lhs_value, RawType rhs_value)
Definition at line 1631 of file gtest.h.
References testing::AssertionSuccess(), DoubleNearPredFormat(), EqFailure(), GTEST_API_, and StringStreamToString().
{
   const FloatingPoint<RawType> lhs(lhs_value), rhs(rhs_value);
   if (lhs.AlmostEquals(rhs)) {
     return AssertionSuccess();
   }
   ::std::stringstream lhs_ss;
   lhs_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
          << lhs_value;
   ::std::stringstream rhs_ss;
   rhs_ss << std::setprecision(std::numeric_limits<RawType>::digits10 + 2)
          << rhs_value;
   return EqFailure(lhs_expression,
                    rhs_expression,
                    StringStreamToString(&lhs_ss),
                    StringStreamToString(&rhs_ss),
                    false);
 }