YOUR NAME's CS132 programs: testing::internal::posix::GetEnv
const char* testing::internal::posix::GetEnv (const char * name) inline
Definition at line 2393 of file gtest-port.h.
References Abort(), and GTEST_DISABLE_MSC_WARNINGS_POP_.
Referenced by testing::internal::BoolFromGTestEnv(), testing::internal::Int32FromEnvOrDie(), testing::internal::Int32FromGTestEnv(), main(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationStart(), testing::UnitTest::Run(), testing::internal::ShouldUseColor(), testing::internal::StringFromGTestEnv(), testing::internal::TempDir(), and testing::internal::WriteToShardStatusFileIfNeeded().
{
 #if GTEST_OS_WINDOWS_MOBILE || GTEST_OS_WINDOWS_PHONE | GTEST_OS_WINDOWS_RT
   // We are on Windows CE, which has no environment variables.
   static_cast<void>(name);  // To prevent 'unused argument' warning.
   return NULL;
 #elif defined(__BORLANDC__) || defined(__SunOS_5_8) || defined(__SunOS_5_9)
   // Environment variables which we programmatically clear will be set to the
   // empty string rather than unset (NULL).  Handle that case.
   const char* const env = getenv(name);
   return (env != NULL && env[0] != '\0') ? env : NULL;
 #else
   return getenv(name);
 #endif
 }