YOUR NAME's CS132 programs: testing::internal::ReportFailureInUnknownLocation
void testing::internal::ReportFailureInUnknownLocation (TestPartResult::Type result_type, const std::string & message)
Definition at line 2250 of file gtest.cc.
References ADD_FAILURE, testing::internal::UnitTestImpl::current_test_case(), testing::internal::UnitTestImpl::current_test_info(), testing::UnitTest::GetInstance(), testing::Message::GetString(), GetTestTypeId(), GetUnitTestImpl(), gtest_output_test::message, testing::TestInfo::name(), and testing::TestInfo::test_case_name().
Referenced by HandleExceptionsInMethodIfSupported(), and HandleSehExceptionsInMethodIfSupported().
{
   // This function is a friend of UnitTest and as such has access to
   // AddTestPartResult.
   UnitTest::GetInstance()->AddTestPartResult(
       result_type,
       NULL,  // No info about the source file where the exception occurred.
       -1,    // We have no info on which line caused the exception.
       message,
       "");   // No stack trace, either.
 }