YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailMessageUnmatchedMatcherAndElement)
Definition at line 4921 of file gmock-matchers_test.cc.
References testing::Eq(), EXPECT_FALSE, EXPECT_THAT, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAre().
{
   std::vector<int> v;
   v.push_back(2);
   v.push_back(3);
   StringMatchResultListener listener;
   EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAre(1, 2),
                                   v, &listener)) << listener.str();
   EXPECT_THAT(
       listener.str(),
       Eq("where"
          " the following matchers don't match any elements:\n"
          "matcher #0: is equal to 1\n"
          "and"
          " where"
          " the following elements don't match any matchers:\n"
          "element #1: 3"));
 }