YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForTwoDimensionalNativeArray)
Definition at line 4319 of file gmock-matchers_test.cc.
References testing::ContainerEq(), testing::ElementsAre(), EXPECT_THAT, and testing::Not().
{
   const char a1[][3] = {"hi", "lo"};
   const char a2[][3] = {"hi", "lo"};
   const char b[][3] = {"lo", "hi"};
   // Tests using ContainerEq() in the first dimension.
   EXPECT_THAT(a1, ContainerEq(a2));
   EXPECT_THAT(a1, Not(ContainerEq(b)));
   // Tests using ContainerEq() in the second dimension.
   EXPECT_THAT(a1, ElementsAre(ContainerEq(a2[0]), ContainerEq(a2[1])));
   EXPECT_THAT(a1, ElementsAre(Not(ContainerEq(b[0])), ContainerEq(a2[1])));
 }