YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST_F
testing::gmock_generated_function_mockers_test::TEST_F (FunctionMockerTest , MocksUnaryFunction)
Definition at line 207 of file gmock-generated-function-mockers_test.cc.
References testing::Eq(), EXPECT_CALL, EXPECT_FALSE, EXPECT_TRUE, testing::Return(), and testing::gmock_generated_function_mockers_test::FooInterface::Unary().
{
   EXPECT_CALL(mock_foo_, Unary(Eq(2)))
       .Times(2)
       .WillOnce(Return(true));
   EXPECT_TRUE(foo_->Unary(2));
   EXPECT_FALSE(foo_->Unary(2));
 }