YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ElementsAreTest , WorksWithUncopyable)
Definition at line 4683 of file gmock-matchers_test.cc.
References testing::ElementsAre(), EXPECT_THAT, testing::gmock_matchers_test::Uncopyable::set_value(), testing::Truly(), and ValueIsPositive().
{
   Uncopyable objs[2];
   objs[0].set_value(-3);
   objs[1].set_value(1);
   EXPECT_THAT(objs, ElementsAre(UncopyableIs(-3), Truly(ValueIsPositive)));
 }