YOUR NAME's CS132 programs: gen_gtest_pred_impl.Iter
def gen_gtest_pred_impl.Iter (n, format, sep = '')
Given a positive integer n, a format string that contains 0 or
more '%s' format specs, and optionally a separator string, returns
the join of n strings, each formatted with the format string on an
iterator ranged from 1 to n.
Example:
Iter(3, 'v%s', sep=', ') returns 'v1, v2, v3'.
Definition at line 189 of file gen_gtest_pred_impl.py.
References OneTo().
Referenced by testing::internal.ArrayAwareFind(), testing::internal.FindMaxBipartiteMatching(), ImplementationForArity(), and TestsForArity().
 def Iter(n, format, sep=''):
   """Given a positive integer n, a format string that contains 0 or
   more '%s' format specs, and optionally a separator string, returns
   the join of n strings, each formatted with the format string on an
   iterator ranged from 1 to n.
   Example:
   Iter(3, 'v%s', sep=', ') returns 'v1, v2, v3'.
   """
   # How many '%s' specs are in format?
   spec_count = len(format.split('%s')) - 1
   return sep.join([format % (spec_count * (i,)) for i in OneTo(n)])