YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (SizeIsTest , ExplainsResult)
Definition at line 4143 of file gmock-matchers_test.cc.
References testing::AnyOf(), testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), GreaterThan(), testing::Lt(), testing::internal::MatcherBase< T >::Matches(), testing::SizeIs(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
{
   Matcher<vector<int> > m1 = SizeIs(2);
   Matcher<vector<int> > m2 = SizeIs(Lt(2u));
   Matcher<vector<int> > m3 = SizeIs(AnyOf(0, 3));
   Matcher<vector<int> > m4 = SizeIs(GreaterThan(1));
   vector<int> container;
   EXPECT_EQ("whose size 0 doesn't match", Explain(m1, container));
   EXPECT_EQ("whose size 0 matches", Explain(m2, container));
   EXPECT_EQ("whose size 0 matches", Explain(m3, container));
   EXPECT_EQ("whose size 0 doesn't match, which is 1 less than 1",
             Explain(m4, container));
   container.push_back(0);
   container.push_back(0);
   EXPECT_EQ("whose size 2 matches", Explain(m1, container));
   EXPECT_EQ("whose size 2 doesn't match", Explain(m2, container));
   EXPECT_EQ("whose size 2 doesn't match", Explain(m3, container));
   EXPECT_EQ("whose size 2 matches, which is 1 more than 1",
             Explain(m4, container));
 }