YOUR NAME's CS132 programs: testing::internal::PrintTo
template<typename T > void testing::internal::PrintTo (const ReferenceWrapper< T > & ref, ::std::ostream * os)
Definition at line 964 of file gmock-actions.h.
References testing::internal::UniversalPrinter< T >::Print().
Referenced by testing::internal::edit_distance::CalculateOptimalEdits(), and testing::internal::ExpectationTester::SetCallCount().
{
   T& value = ref;
   UniversalPrinter<T&>::Print(value, os);
 }