YOUR NAME's CS132 programs: testing::internal::ForEach
template<class Container , typename Functor > void testing::internal::ForEach (const Container & c, Functor functor)
Definition at line 296 of file gtest-internal-inl.h.
Referenced by testing::internal::UnitTestImpl::ClearNonAdHocTestResult(), testing::TestCase::GetTestInfo(), operator<<(), testing::internal::UnitTestImpl::RunAllTests(), testing::TestCase::~TestCase(), testing::internal::TestEventRepeater::~TestEventRepeater(), and testing::internal::UnitTestImpl::~UnitTestImpl().
{
   std::for_each(c.begin(), c.end(), functor);
 }