YOUR NAME's CS132 programs: testing::operator<<
std::ostream & testing::operator<< (std::ostream & os, const TestPartResult & result)
Definition at line 58 of file gtest-test-part.cc.
References testing::TestPartResult::file_name(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::kSuccess, testing::TestPartResult::line_number(), testing::TestPartResult::message(), and testing::TestPartResult::type().
{
   return os
       << result.file_name() << ":" << result.line_number() << ": "
       << (result.type() == TestPartResult::kSuccess ? "Success" :
           result.type() == TestPartResult::kFatalFailure ? "Fatal failure" :
           "Non-fatal failure") << ":\n"
       << result.message() << std::endl;
 }