YOUR NAME's CS132 programs: gtest_uninitialized_test.TestExitCodeAndOutput
def gtest_uninitialized_test.TestExitCodeAndOutput (command)
Runs the given command and verifies its exit code and output.
Definition at line 54 of file gtest_uninitialized_test.py.
References Assert(), and AssertEq().
Referenced by gtest_uninitialized_test.GTestUninitializedTest.testExitCodeAndOutput().
 def TestExitCodeAndOutput(command):
   """Runs the given command and verifies its exit code and output."""
   # Verifies that 'command' exits with code 1.
   p = gtest_test_utils.Subprocess(command)
   Assert(p.exited)
   AssertEq(1, p.exit_code)
   Assert('InitGoogleTest' in p.output)