YOUR NAME's CS132 programs: testing::TEST
testing::TEST (SuccessfulAssertionTest , ASSERT_STR)
Definition at line 4219 of file gtest_unittest.cc.
References ADD_FAILURE, ADD_FAILURE_AT, ASSERT_DOUBLE_EQ, ASSERT_EQ, ASSERT_FALSE, ASSERT_FLOAT_EQ, ASSERT_GE, ASSERT_GT, ASSERT_LE, ASSERT_LT, ASSERT_NE, ASSERT_NEAR, ASSERT_STRCASEEQ, ASSERT_STRCASENE, ASSERT_STREQ, ASSERT_STRNE, ASSERT_TRUE, testing::gmock_generated_actions_test::Char(), count, EXPECT_ANY_THROW, EXPECT_DOUBLE_EQ, EXPECT_EQ, EXPECT_FALSE, EXPECT_FATAL_FAILURE, EXPECT_FLOAT_EQ, EXPECT_GE, EXPECT_GT, EXPECT_LE, EXPECT_LT, EXPECT_NE, EXPECT_NEAR, EXPECT_NO_THROW, EXPECT_NONFATAL_FAILURE, EXPECT_STRCASEEQ, EXPECT_STRCASENE, EXPECT_STREQ, EXPECT_STRNE, EXPECT_THROW, EXPECT_TRUE, FAIL, testing::gmock_matchers_test::foo, FRIEND_TEST, testing::internal::GetUnitTestImpl(), testing::internal::operator!=(), testing::internal::operator==(), testing::internal::StreamableToString(), SUCCEED, testing::internal::TEST(), and testing::internal::TEST_F().
{
   ASSERT_STREQ("", "");
   EXPECT_EQ(0, GetUnitTestImpl()->current_test_result()->total_part_count());
 }