YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (FieldTest , CanExplainMatchResult)
Definition at line 3492 of file gmock-matchers_test.cc.
References EXPECT_EQ, Explain(), testing::Field(), testing::Ge(), GreaterThan(), OfType(), and testing::gmock_matchers_test::AStruct::x.
{
   Matcher<const AStruct&> m = Field(&AStruct::x, Ge(0));
   AStruct a;
   a.x = 1;
   EXPECT_EQ("whose given field is 1" + OfType("int"), Explain(m, a));
   m = Field(&AStruct::x, GreaterThan(0));
   EXPECT_EQ(
       "whose given field is 1" + OfType("int") + ", which is 1 more than 0",
       Explain(m, a));
 }