YOUR NAME's CS132 programs: testing::internal::GetTestTypeId
TypeId testing::internal::GetTestTypeId ()
Definition at line 620 of file gtest.cc.
Referenced by GetTypeId(), operator<<(), and ReportFailureInUnknownLocation().
{
   return GetTypeId<Test>();
 }