YOUR NAME's CS132 programs: std::tr1::make_tuple
tuple std::tr1::make_tuple () inline
Definition at line 675 of file gtest-tuple.h.
Referenced by testing::gmock_generated_actions_test::TEST(), testing::gmock_more_actions_test::TEST(), testing::gtest_printers_test::TEST(), testing::gmock_matchers_test::TEST(), testing::internal::FunctionMocker< R(A1)>::With(), testing::internal::FunctionMocker< R(A1, A2)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8)>::With(), testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9)>::With(), and testing::internal::FunctionMocker< R(A1, A2, A3, A4, A5, A6, A7, A8, A9, A10)>::With().
 { return tuple<>(); }