YOUR NAME's CS132 programs: pump.MakeToken
def pump.MakeToken (lines, start, end, token_type)
Creates a new instance of Token.
Definition at line 237 of file pump.py.
References SubString().
Referenced by FindFirst(), ParseExpTokenInParens(), ParseToken(), and TokenizeLines().
 def MakeToken(lines, start, end, token_type):
   """Creates a new instance of Token."""
   return Token(start, end, SubString(lines, start, end), token_type)