YOUR NAME's CS132 programs: testing::internal::ShuffleRange
template<typename E > void testing::internal::ShuffleRange (internal::Random * random, int begin, int end, std::vector< E > * v)
Definition at line 312 of file gtest-internal-inl.h.
References testing::internal::Random::Generate(), and GTEST_CHECK_.
Referenced by operator<<(), Shuffle(), and testing::internal::UnitTestImpl::ShuffleTests().
{
   const int size = static_cast<int>(v->size());
   GTEST_CHECK_(0 <= begin && begin <= size)
       << "Invalid shuffle range start " << begin << ": must be in range [0, "
       << size << "].";
   GTEST_CHECK_(begin <= end && end <= size)
       << "Invalid shuffle range finish " << end << ": must be in range ["
       << begin << ", " << size << "].";
   // Fisher-Yates shuffle, from
   // http://en.wikipedia.org/wiki/Fisher-Yates_shuffle
   for (int range_width = end - begin; range_width >= 2; range_width--) {
     const int last_in_range = begin + range_width - 1;
     const int selected = begin + random->Generate(range_width);
     std::swap((*v)[selected], (*v)[last_in_range]);
   }
 }