YOUR NAME's CS132 programs: gen_gtest_pred_impl.TestsForArity
def gen_gtest_pred_impl.TestsForArity (n)
Returns the tests for n-ary predicate assertions.
Definition at line 411 of file gen_gtest_pred_impl.py.
References Arity(), Iter(), OneTo(), and Title().
Referenced by GenerateUnitTest().
 def TestsForArity(n):
   """Returns the tests for n-ary predicate assertions."""
   # A map that defines the values used in the template for the tests.
   DEFS = {
     'n' : n,
     'es' : Iter(n, 'e%s', sep=', '),
     'vs' : Iter(n, 'v%s', sep=', '),
     'vts' : Iter(n, '#v%s', sep=', '),
     'tvs' : Iter(n, 'T%s v%s', sep=', '),
     'int_vs' : Iter(n, 'int v%s', sep=', '),
     'Bool_vs' : Iter(n, 'Bool v%s', sep=', '),
     'types' : Iter(n, 'typename T%s', sep=', '),
     'v_sum' : Iter(n, 'v%s', sep=' + '),
     'arity' : Arity(n),
     'Arity' : Title(Arity(n)),
     }
   tests = (
 """// Sample functions/functors for testing %(arity)s predicate assertions.
 // A %(arity)s predicate function.
 template <%(types)s>
 bool PredFunction%(n)s(%(tvs)s) {
   return %(v_sum)s > 0;
 }
 // The following two functions are needed to circumvent a bug in
 // gcc 2.95.3, which sometimes has problem with the above template
 // function.
 bool PredFunction%(n)sInt(%(int_vs)s) {
   return %(v_sum)s > 0;
 }
 bool PredFunction%(n)sBool(%(Bool_vs)s) {
   return %(v_sum)s > 0;
 }
 """ % DEFS)
   tests += """
 // A %(arity)s predicate functor.
 struct PredFunctor%(n)s {
   template <%(types)s>
   bool operator()(""" % DEFS
   tests += Iter(n, 'const T%s& v%s', sep=""",
                   """)
   tests += """) {
     return %(v_sum)s > 0;
   }
 };
 """ % DEFS
   tests += """
 // A %(arity)s predicate-formatter function.
 template <%(types)s>
 testing::AssertionResult PredFormatFunction%(n)s(""" % DEFS
   tests += Iter(n, 'const char* e%s', sep=""",
                                              """)
   tests += Iter(n, """,
                                              const T%s& v%s""")
   tests += """) {
   if (PredFunction%(n)s(%(vs)s))
     return testing::AssertionSuccess();
   return testing::AssertionFailure()
       << """ % DEFS
   tests += Iter(n, 'e%s', sep=' << " + " << ')
   tests += """
       << " is expected to be positive, but evaluates to "
       << %(v_sum)s << ".";
 }
 """ % DEFS
   tests += """
 // A %(arity)s predicate-formatter functor.
 struct PredFormatFunctor%(n)s {
   template <%(types)s>
   testing::AssertionResult operator()(""" % DEFS
   tests += Iter(n, 'const char* e%s', sep=""",
                                       """)
   tests += Iter(n, """,
                                       const T%s& v%s""")
   tests += """) const {
     return PredFormatFunction%(n)s(%(es)s, %(vs)s);
   }
 };
 """ % DEFS
   tests += """
 // Tests for {EXPECT|ASSERT}_PRED_FORMAT%(n)s.
 class Predicate%(n)sTest : public testing::Test {
  protected:
   virtual void SetUp() {
     expected_to_finish_ = true;
     finished_ = false;""" % DEFS
   tests += """
     """ + Iter(n, 'n%s_ = ') + """0;
   }
 """
   tests += """
   virtual void TearDown() {
     // Verifies that each of the predicate's arguments was evaluated
     // exactly once."""
   tests += ''.join(["""
     EXPECT_EQ(1, n%s_) <<
         "The predicate assertion didn't evaluate argument %s "
         "exactly once.";""" % (i, i + 1) for i in OneTo(n)])
   tests += """
     // Verifies that the control flow in the test function is expected.
     if (expected_to_finish_ && !finished_) {
       FAIL() << "The predicate assertion unexpactedly aborted the test.";
     } else if (!expected_to_finish_ && finished_) {
       FAIL() << "The failed predicate assertion didn't abort the test "
                 "as expected.";
     }
   }
   // true iff the test function is expected to run to finish.
   static bool expected_to_finish_;
   // true iff the test function did run to finish.
   static bool finished_;
 """ % DEFS
   tests += Iter(n, """
   static int n%s_;""")
   tests += """
 };
 bool Predicate%(n)sTest::expected_to_finish_;
 bool Predicate%(n)sTest::finished_;
 """ % DEFS
   tests += Iter(n, """int Predicate%%(n)sTest::n%s_;
 """) % DEFS
   tests += """
 typedef Predicate%(n)sTest EXPECT_PRED_FORMAT%(n)sTest;
 typedef Predicate%(n)sTest ASSERT_PRED_FORMAT%(n)sTest;
 typedef Predicate%(n)sTest EXPECT_PRED%(n)sTest;
 typedef Predicate%(n)sTest ASSERT_PRED%(n)sTest;
 """ % DEFS
   def GenTest(use_format, use_assert, expect_failure,
               use_functor, use_user_type):
     """Returns the test for a predicate assertion macro.
     Args:
       use_format:     true iff the assertion is a *_PRED_FORMAT*.
       use_assert:     true iff the assertion is a ASSERT_*.
       expect_failure: true iff the assertion is expected to fail.
       use_functor:    true iff the first argument of the assertion is
                       a functor (as opposed to a function)
       use_user_type:  true iff the predicate functor/function takes
                       argument(s) of a user-defined type.
     Example:
       GenTest(1, 0, 0, 1, 0) returns a test that tests the behavior
       of a successful EXPECT_PRED_FORMATn() that takes a functor
       whose arguments have built-in types."""
     if use_assert:
       assrt = 'ASSERT'  # 'assert' is reserved, so we cannot use
                         # that identifier here.
     else:
       assrt = 'EXPECT'
     assertion = assrt + '_PRED'
     if use_format:
       pred_format = 'PredFormat'
       assertion += '_FORMAT'
     else:
       pred_format = 'Pred'
     assertion += '%(n)s' % DEFS
     if use_functor:
       pred_format_type = 'functor'
       pred_format += 'Functor%(n)s()'
     else:
       pred_format_type = 'function'
       pred_format += 'Function%(n)s'
       if not use_format:
         if use_user_type:
           pred_format += 'Bool'
         else:
           pred_format += 'Int'
     test_name = pred_format_type.title()
     if use_user_type:
       arg_type = 'user-defined type (Bool)'
       test_name += 'OnUserType'
       if expect_failure:
         arg = 'Bool(n%s_++)'
       else:
         arg = 'Bool(++n%s_)'
     else:
       arg_type = 'built-in type (int)'
       test_name += 'OnBuiltInType'
       if expect_failure:
         arg = 'n%s_++'
       else:
         arg = '++n%s_'
     if expect_failure:
       successful_or_failed = 'failed'
       expected_or_not = 'expected.'
       test_name +=  'Failure'
     else:
       successful_or_failed = 'successful'
       expected_or_not = 'UNEXPECTED!'
       test_name +=  'Success'
     # A map that defines the values used in the test template.
     defs = DEFS.copy()
     defs.update({
       'assert' : assrt,
       'assertion' : assertion,
       'test_name' : test_name,
       'pf_type' : pred_format_type,
       'pf' : pred_format,
       'arg_type' : arg_type,
       'arg' : arg,
       'successful' : successful_or_failed,
       'expected' : expected_or_not,
       })
     test = """
 // Tests a %(successful)s %(assertion)s where the
 // predicate-formatter is a %(pf_type)s on a %(arg_type)s.
 TEST_F(%(assertion)sTest, %(test_name)s) {""" % defs
     indent = (len(assertion) + 3)*' '
     extra_indent = ''
     if expect_failure:
       extra_indent = '  '
       if use_assert:
         test += """
   expected_to_finish_ = false;
   EXPECT_FATAL_FAILURE({  // NOLINT"""
       else:
         test += """
   EXPECT_NONFATAL_FAILURE({  // NOLINT"""
     test += '\n' + extra_indent + """  %(assertion)s(%(pf)s""" % defs
     test = test % defs
     test += Iter(n, ',\n' + indent + extra_indent + '%(arg)s' % defs)
     test += ');\n' + extra_indent + '  finished_ = true;\n'
     if expect_failure:
       test += '  }, "");\n'
     test += '}\n'
     return test
   # Generates tests for all 2**6 = 64 combinations.
   tests += ''.join([GenTest(use_format, use_assert, expect_failure,
                             use_functor, use_user_type)
                     for use_format in [0, 1]
                     for use_assert in [0, 1]
                     for expect_failure in [0, 1]
                     for use_functor in [0, 1]
                     for use_user_type in [0, 1]
                     ])
   return tests