YOUR NAME's CS132 programs: fuse_gmock_files.FuseGMock
def fuse_gmock_files.FuseGMock (gmock_root, output_dir)
Fuses gtest.h, gmock.h, and gmock-gtest-all.h.
Definition at line 215 of file fuse_gmock_files.py.
References FuseGMockGTestAllCc(), FuseGMockH(), GetGTestRootDir(), ValidateGMockRootDir(), and ValidateOutputDir().
Referenced by main().
 def FuseGMock(gmock_root, output_dir):
   """Fuses gtest.h, gmock.h, and gmock-gtest-all.h."""
   ValidateGMockRootDir(gmock_root)
   ValidateOutputDir(output_dir)
   gtest.FuseGTestH(GetGTestRootDir(gmock_root), output_dir)
   FuseGMockH(gmock_root, output_dir)
   FuseGMockGTestAllCc(gmock_root, output_dir)