YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (ThreadLocalTest , PointerAndConstPointerReturnSameValue)
Definition at line 1012 of file gtest-port_test.cc.
References ASSERT_EQ, ASSERT_FALSE, testing::internal::Mutex::AssertHeld(), EXPECT_DEATH_IF_SUPPORTED, EXPECT_EQ, EXPECT_STREQ, EXPECT_TRUE, testing::internal::ThreadLocal< T >::get(), GTEST_CHECK_, GTEST_CHECK_POSIX_SUCCESS_, GTEST_DISALLOW_ASSIGN_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::internal::ThreadLocal< T >::pointer(), testing::internal::scoped_ptr< T >::reset(), testing::internal::ThreadLocal< T >::set(), and TEST().
{
   ThreadLocal<std::string> thread_local_string;
   const ThreadLocal<std::string>& const_thread_local_string =
       thread_local_string;
   EXPECT_EQ(thread_local_string.pointer(), const_thread_local_string.pointer());
   thread_local_string.set("foo");
   EXPECT_EQ(thread_local_string.pointer(), const_thread_local_string.pointer());
 }