YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_P
testing::gmock_matchers_test::TEST_P (BipartiteRandomTest , LargerNets)
Definition at line 5186 of file gmock-matchers_test.cc.
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), GTEST_FLAG, GTEST_FLAG_PREFIX_, testing::INSTANTIATE_TEST_CASE_P(), and testing::internal::MatchMatrix::Randomize().
{
   int nodes = GetParam().first;
   int iters = GetParam().second;
   MatchMatrix graph(nodes, nodes);
   testing::internal::Int32 seed = GTEST_FLAG(random_seed);
   if (seed == 0) {
     seed = static_cast<testing::internal::Int32>(time(NULL));
   }
   for (; iters > 0; --iters, ++seed) {
     srand(static_cast<int>(seed));
     graph.Randomize();
     EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(),
               internal::FindMaxBipartiteMatching(graph).size())
         << " graph: " << graph.DebugString()
         << "\nTo reproduce the failure, rerun the test with the flag"
            " --" << GTEST_FLAG_PREFIX_ << "random_seed=" << seed;
   }
 }