YOUR NAME's CS132 programs: testing::MakeMatcher
template<typename T > Matcher<T> testing::MakeMatcher (const MatcherInterface< T > * impl) inline
Definition at line 484 of file gmock-matchers.h.
Referenced by A(), testing::gmock_matchers_test::GreaterThan(), testing::internal::PairMatchBase< Le2Matcher, AnyLe >::operator Matcher< ::testing::tuple< T1, T2 > >(), testing::internal::ArgsMatcher< InnerMatcher, k0, k1, k2, k3, k4, k5, k6, k7, k8, k9 >::operator Matcher< ArgsTuple >(), testing::internal::PairMatchBase< Le2Matcher, AnyLe >::operator Matcher< const ::testing::tuple< T1, T2 > & >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< const FloatType & >(), testing::internal::SizeIsMatcher< SizeMatcher >::operator Matcher< Container >(), testing::internal::BeginEndDistanceIsMatcher< DistanceMatcher >::operator Matcher< Container >(), testing::internal::ContainsMatcher< M >::operator Matcher< Container >(), testing::internal::EachMatcher< M >::operator Matcher< Container >(), testing::internal::UnorderedElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), testing::internal::ElementsAreMatcher< MatcherTuple >::operator Matcher< Container >(), testing::internal::UnorderedElementsAreArrayMatcher< T >::operator Matcher< Container >(), testing::internal::ElementsAreArrayMatcher< T >::operator Matcher< Container >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType & >(), testing::internal::FloatingEqMatcher< FloatType >::operator Matcher< FloatType >(), testing::internal::ComparisonBase< LtMatcher< Rhs >, Rhs, AnyLt >::operator Matcher< Lhs >(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::operator Matcher< LhsContainer >(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::operator Matcher< LhsContainer >(), testing::internal::KeyMatcher< M >::operator Matcher< PairType >(), testing::internal::PairMatcher< FirstMatcher, SecondMatcher >::operator Matcher< PairType >(), testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer >(), testing::internal::RefMatcher< T & >::operator Matcher< Super & >(), testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator Matcher< T >(), and testing::gmock_matchers_test::TEST().
{
   return Matcher<T>(impl);
 }