YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PointwiseTest , AcceptsCorrectContent)
Definition at line 5516 of file gmock-matchers_test.cc.
References EXPECT_EQ, EXPECT_THAT, Explain(), IsHalfOf(), and testing::Pointwise().
{
   const double lhs[3] = {1, 2, 3};
   const int rhs[3] = {2, 4, 6};
   EXPECT_THAT(lhs, Pointwise(IsHalfOf(), rhs));
   EXPECT_EQ("", Explain(Pointwise(IsHalfOf(), rhs), lhs));
 }