YOUR NAME's CS132 programs: testing::gmock_generated_actions_test::TEST
testing::gmock_generated_actions_test::TEST (WithArgsTest , ReversedArgumentOrder)
Definition at line 398 of file gmock-generated-actions_test.cc.
References Binary(), CharPtr(), EXPECT_EQ, testing::Invoke(), std::tr1::make_tuple(), testing::Action< F >::Perform(), and Short().
{
   Action<const char*(short n, const char* input)> a =  // NOLINT
       WithArgs<1, 0>(Invoke(Binary));
   const char s[] = "Hello";
   EXPECT_EQ(s + 2, a.Perform(make_tuple(Short(2), CharPtr(s))));
 }