YOUR NAME's CS132 programs: testing::internal::ReportUninterestingCall
void testing::internal::ReportUninterestingCall (CallReaction reaction, const string & msg)
Definition at line 247 of file gmock-spec-builders.cc.
References Expect(), GMOCK_FLAG, kAllow, kInfo, kInfoVerbosity, kWarn, kWarning, and Log().
Referenced by testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith().
{
   // Include a stack trace only if --gmock_verbose=info is specified.
   const int stack_frames_to_skip =
       GMOCK_FLAG(verbose) == kInfoVerbosity ? 3 : -1;
   switch (reaction) {
     case kAllow:
       Log(kInfo, msg, stack_frames_to_skip);
       break;
     case kWarn:
       Log(kWarning,
           msg +
           "\nNOTE: You can safely ignore the above warning unless this "
           "call should not happen.  Do not suppress it by blindly adding "
           "an EXPECT_CALL() if you don't mean to enforce the call.  "
           "See https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#"
           "knowing-when-to-expect for details.\n",
           stack_frames_to_skip);
       break;
     default:  // FAIL
       Expect(false, NULL, -1, msg);
   }
 }