YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , WorksForMaps)
Definition at line 4292 of file gmock-matchers_test.cc.
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), and testing::internal::MatcherBase< T >::Matches().
{
   map<int, std::string> my_map;
   my_map[0] = "a";
   my_map[1] = "b";
   map<int, std::string> test_map;
   test_map[0] = "aa";
   test_map[1] = "b";
   const Matcher<const map<int, std::string>&> m = ContainerEq(my_map);
   EXPECT_TRUE(m.Matches(my_map));
   EXPECT_FALSE(m.Matches(test_map));
   EXPECT_EQ("which has these unexpected elements: (0, \"aa\"),\n"
             "and doesn't have these expected elements: (0, \"a\")",
             Explain(m, test_map));
 }