YOUR NAME's CS132 programs: testing::Ref
template<typename T > internal::RefMatcher<T&> testing::Ref (T & x) inline
Definition at line 3809 of file gmock-matchers.h.
Referenced by TEST(), testing::gmock_matchers_test::TEST(), TEST_F(), and testing::gmock_generated_function_mockers_test::TEST_F().
                                         {  // NOLINT
   return internal::RefMatcher<T&>(x);
 }