YOUR NAME's CS132 programs: testing::StrEq
PolymorphicMatcher<internal::StrEqualityMatcher<internal::string> > testing::StrEq (const internal::string & str) inline
Definition at line 3955 of file gmock-matchers.h.
References MakePolymorphicMatcher().
Referenced by ContainsRegex(), TEST(), and testing::gmock_matchers_test::TEST().
{
   return MakePolymorphicMatcher(internal::StrEqualityMatcher<internal::string>(
       str, true, true));
 }