YOUR NAME's CS132 programs: gtest_shuffle_test.CalculateTestLists
def gtest_shuffle_test.CalculateTestLists ()
Calculates the list of tests run under different flags.
Definition at line 130 of file gtest_shuffle_test.py.
References AlsoRunDisabledTestsFlag(), FilterFlag(), GetTestsForAllIterations(), RandomSeedFlag(), and ShuffleFlag().
Referenced by gtest_shuffle_test.GTestShuffleUnitTest.setUp().
 def CalculateTestLists():
   """Calculates the list of tests run under different flags."""
   if not ALL_TESTS:
     ALL_TESTS.extend(
         GetTestsForAllIterations({}, [AlsoRunDisabledTestsFlag()])[0])
   if not ACTIVE_TESTS:
     ACTIVE_TESTS.extend(GetTestsForAllIterations({}, [])[0])
   if not FILTERED_TESTS:
     FILTERED_TESTS.extend(
         GetTestsForAllIterations({}, [FilterFlag(TEST_FILTER)])[0])
   if not SHARDED_TESTS:
     SHARDED_TESTS.extend(
         GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                   SHARD_INDEX_ENV_VAR: '1'},
                                  [])[0])
   if not SHUFFLED_ALL_TESTS:
     SHUFFLED_ALL_TESTS.extend(GetTestsForAllIterations(
         {}, [AlsoRunDisabledTestsFlag(), ShuffleFlag(), RandomSeedFlag(1)])[0])
   if not SHUFFLED_ACTIVE_TESTS:
     SHUFFLED_ACTIVE_TESTS.extend(GetTestsForAllIterations(
         {}, [ShuffleFlag(), RandomSeedFlag(1)])[0])
   if not SHUFFLED_FILTERED_TESTS:
     SHUFFLED_FILTERED_TESTS.extend(GetTestsForAllIterations(
         {}, [ShuffleFlag(), RandomSeedFlag(1), FilterFlag(TEST_FILTER)])[0])
   if not SHUFFLED_SHARDED_TESTS:
     SHUFFLED_SHARDED_TESTS.extend(
         GetTestsForAllIterations({TOTAL_SHARDS_ENV_VAR: '3',
                                   SHARD_INDEX_ENV_VAR: '1'},
                                  [ShuffleFlag(), RandomSeedFlag(1)])[0])