YOUR NAME's CS132 programs: testing::internal::LogWithLocation
GTEST_API_ void testing::internal::LogWithLocation (testing::internal::LogSeverity severity, const char * file, int line, const string & message)
Definition at line 59 of file gmock-spec-builders.cc.
References Log().
Referenced by testing::internal::MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::InternalDefaultActionSetAt(), and testing::internal::MockSpec< R(A1, A2, A3, A4, A5, A6, A7, A8, A9) >::InternalExpectedAt().
{
   ::std::ostringstream s;
   s << file << ":" << line << ": " << message << ::std::endl;
   Log(severity, s.str(), 0);
 }