YOUR NAME's CS132 programs: testing::internal::HandleExceptionsInMethodIfSupported
template<class T , typename Result > Result testing::internal::HandleExceptionsInMethodIfSupported (T * object, Result(T::*)() method, const char * location)
Definition at line 2410 of file gtest.cc.
References GetUnitTestImpl(), HandleSehExceptionsInMethodIfSupported(), testing::Test::HasFatalFailure(), testing::TestPartResult::kFatalFailure, testing::internal::UnitTestImpl::os_stack_trace_getter(), ReportFailureInUnknownLocation(), testing::Test::SetUp(), testing::Test::TearDown(), and testing::internal::OsStackTraceGetterInterface::UponLeavingGTest().
Referenced by testing::TestCase::GetTestInfo(), testing::internal::UnitTestImpl::RegisterParameterizedTests(), and testing::UnitTest::Run().
{
   // NOTE: The user code can affect the way in which Google Test handles
   // exceptions by setting GTEST_FLAG(catch_exceptions), but only before
   // RUN_ALL_TESTS() starts. It is technically possible to check the flag
   // after the exception is caught and either report or re-throw the
   // exception based on the flag's value:
   //
   // try {
   //   // Perform the test method.
   // } catch (...) {
   //   if (GTEST_FLAG(catch_exceptions))
   //     // Report the exception as failure.
   //   else
   //     throw;  // Re-throws the original exception.
   // }
   //
   // However, the purpose of this flag is to allow the program to drop into
   // the debugger when the exception is thrown. On most platforms, once the
   // control enters the catch block, the exception origin information is
   // lost and the debugger will stop the program at the point of the
   // re-throw in this function -- instead of at the point of the original
   // throw statement in the code under test.  For this reason, we perform
   // the check early, sacrificing the ability to affect Google Test's
   // exception handling in the method where the exception is thrown.
   if (internal::GetUnitTestImpl()->catch_exceptions()) {
 #if GTEST_HAS_EXCEPTIONS
     try {
       return HandleSehExceptionsInMethodIfSupported(object, method, location);
     } catch (const internal::GoogleTestFailureException&) {  // NOLINT
       // This exception type can only be thrown by a failed Google
       // Test assertion with the intention of letting another testing
       // framework catch it.  Therefore we just re-throw it.
       throw;
     } catch (const std::exception& e) {  // NOLINT
       internal::ReportFailureInUnknownLocation(
           TestPartResult::kFatalFailure,
           FormatCxxExceptionMessage(e.what(), location));
     } catch (...) {  // NOLINT
       internal::ReportFailureInUnknownLocation(
           TestPartResult::kFatalFailure,
           FormatCxxExceptionMessage(NULL, location));
     }
     return static_cast<Result>(0);
 #else
     return HandleSehExceptionsInMethodIfSupported(object, method, location);
 #endif  // GTEST_HAS_EXCEPTIONS
   } else {
     return (object->*method)();
   }
 }