YOUR NAME's CS132 programs: pump.ParseElseNode
def pump.ParseElseNode (tokens)
Definition at line 475 of file pump.py.
References ParseCodeNode(), ParseExpNode(), PeekToken(), and PopToken().
Referenced by ParseAtomicCodeNode().
 def ParseElseNode(tokens):
   def Pop(token_type=None):
     return PopToken(tokens, token_type)
   next = PeekToken(tokens)
   if not next:
     return None
   if next.token_type == '$else':
     Pop('$else')
     Pop('[[')
     code_node = ParseCodeNode(tokens)
     Pop(']]')
     return code_node
   elif next.token_type == '$elif':
     Pop('$elif')
     exp = Pop('code')
     Pop('[[')
     code_node = ParseCodeNode(tokens)
     Pop(']]')
     inner_else_node = ParseElseNode(tokens)
     return CodeNode([IfNode(ParseExpNode(exp), code_node, inner_else_node)])
   elif not next.value.strip():
     Pop('code')
     return ParseElseNode(tokens)
   else:
     return None