YOUR NAME's CS132 programs: testing::internal::FindPairing
GTEST_API_ bool testing::internal::FindPairing (const MatchMatrix & matrix, MatchResultListener * listener)
Definition at line 328 of file gmock-matchers.cc.
References FindMaxBipartiteMatching(), testing::MatchResultListener::IsInterested(), testing::internal::MatchMatrix::RhsSize(), and testing::MatchResultListener::stream().
Referenced by testing::internal::UnorderedElementsAreMatcherImpl< Container >::MatchAndExplain().
{
   ElementMatcherPairs matches = FindMaxBipartiteMatching(matrix);
   size_t max_flow = matches.size();
   bool result = (max_flow == matrix.RhsSize());
   if (!result) {
     if (listener->IsInterested()) {
       *listener << "where no permutation of the elements can "
                    "satisfy all matchers, and the closest match is "
                 << max_flow << " of " << matrix.RhsSize()
                 << " matchers with the pairings:\n";
       LogElementMatcherPairVec(matches, listener->stream());
     }
     return false;
   }
   if (matches.size() > 1) {
     if (listener->IsInterested()) {
       const char *sep = "where:\n";
       for (size_t mi = 0; mi < matches.size(); ++mi) {
         *listener << sep << " - element #" << matches[mi].first
                   << " is matched by matcher #" << matches[mi].second;
         sep = ",\n";
       }
     }
   }
   return true;
 }