YOUR NAME's CS132 programs: testing::internal::MatchPrintAndExplain
template<typename Value , typename T > bool testing::internal::MatchPrintAndExplain (Value & value, const Matcher< T > & matcher, MatchResultListener * listener)
Definition at line 701 of file gmock-matchers.h.
References testing::MatchResultListener::IsInterested(), IsReadableTypeName(), testing::internal::MatcherBase< T >::MatchAndExplain(), testing::internal::MatcherBase< T >::Matches(), PrintIfNotEmpty(), testing::StringMatchResultListener::str(), testing::MatchResultListener::stream(), and UniversalPrint().
Referenced by testing::internal::WhenDynamicCastToMatcher< To >::MatchAndExplain(), testing::internal::WhenDynamicCastToMatcher< To & >::MatchAndExplain(), testing::internal::FieldMatcher< Class, FieldType >::MatchAndExplain(), testing::internal::PropertyMatcher< Class, PropertyType >::MatchAndExplain(), testing::internal::PointeeMatcher< InnerMatcher >::operator Matcher< Pointer >(), testing::internal::ResultOfMatcher< Callable >::operator Matcher< T >(), and testing::internal::PredicateFormatterFromMatcher< M >::operator()().
{
   if (!listener->IsInterested()) {
     // If the listener is not interested, we do not need to construct the
     // inner explanation.
     return matcher.Matches(value);
   }
   StringMatchResultListener inner_listener;
   const bool match = matcher.MatchAndExplain(value, &inner_listener);
   UniversalPrint(value, listener->stream());
 #if GTEST_HAS_RTTI
   const string& type_name = GetTypeName<Value>();
   if (IsReadableTypeName(type_name))
     *listener->stream() << " (of type " << type_name << ")";
 #endif
   PrintIfNotEmpty(inner_listener.str(), listener->stream());
   return match;
 }