YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_P
testing::gmock_matchers_test::TEST_P (BipartiteNonSquareTest , Exhaustive)
Definition at line 5155 of file gmock-matchers_test.cc.
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), testing::INSTANTIATE_TEST_CASE_P(), testing::internal::MatchMatrix::NextGraph(), and testing::PrintToString().
{
   size_t nlhs = GetParam().first;
   size_t nrhs = GetParam().second;
   MatchMatrix graph(nlhs, nrhs);
   do {
     EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(),
               internal::FindMaxBipartiteMatching(graph).size())
         << "graph: " << graph.DebugString()
         << "\nbacktracking: "
         << PrintToString(FindBacktrackingMaxBPM(graph))
         << "\nmax flow: "
         << PrintToString(internal::FindMaxBipartiteMatching(graph));
   } while (graph.NextGraph());
 }