YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (ThreadLocalTest , GetAndPointerReturnSameValue)
Definition at line 1002 of file gtest-port_test.cc.
References EXPECT_EQ, testing::internal::ThreadLocal< T >::get(), testing::internal::ThreadLocal< T >::pointer(), and testing::internal::ThreadLocal< T >::set().
{
   ThreadLocal<std::string> thread_local_string;
   EXPECT_EQ(thread_local_string.pointer(), &(thread_local_string.get()));
   // Verifies the condition still holds after calling set.
   thread_local_string.set("foo");
   EXPECT_EQ(thread_local_string.pointer(), &(thread_local_string.get()));
 }