YOUR NAME's CS132 programs: testing::gtest_printers_test::TEST
testing::gtest_printers_test::TEST (PrintReferenceTest , HandlesMemberFunctionPointer)
Definition at line 1217 of file gtest-printers_test.cc.
References EXPECT_TRUE, HasPrefix(), Print(), and PrintByRef().
{
   int (Foo::*p)(char ch) = &Foo::MyMethod;
   EXPECT_TRUE(HasPrefix(
       PrintByRef(p),
       "@" + PrintPointer(reinterpret_cast<const void*>(&p)) + " " +
           Print(sizeof(p)) + "-byte object "));
   char (Foo::*p2)(int n) = &Foo::MyVirtualMethod;
   EXPECT_TRUE(HasPrefix(
       PrintByRef(p2),
       "@" + PrintPointer(reinterpret_cast<const void*>(&p2)) + " " +
           Print(sizeof(p2)) + "-byte object "));
 }