YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (IsXDigitTest , WorksForNarrowAscii)
Definition at line 64 of file gtest-port_test.cc.
References EXPECT_FALSE, EXPECT_TRUE, and IsXDigit().
Referenced by testing::gmock_matchers_test::MATCHER_P(), operator<<(), testing::internal::ExpectationTester::SetCallCount(), TEST(), testing::gmock_matchers_test::TEST(), testing::TEST(), and TEST().
{
   EXPECT_TRUE(IsXDigit('0'));
   EXPECT_TRUE(IsXDigit('9'));
   EXPECT_TRUE(IsXDigit('A'));
   EXPECT_TRUE(IsXDigit('F'));
   EXPECT_TRUE(IsXDigit('a'));
   EXPECT_TRUE(IsXDigit('f'));
   EXPECT_FALSE(IsXDigit('-'));
   EXPECT_FALSE(IsXDigit('g'));
   EXPECT_FALSE(IsXDigit('G'));
 }