YOUR NAME's CS132 programs: pump.ParseCodeNode
def pump.ParseCodeNode (tokens)
Definition at line 564 of file pump.py.
References ParseAtomicCodeNode().
Referenced by ParseAtomicCodeNode(), ParseElseNode(), and ParseToAST().
 def ParseCodeNode(tokens):
   atomic_code_list = []
   while True:
     if not tokens:
       break
     atomic_code_node = ParseAtomicCodeNode(tokens)
     if atomic_code_node:
       atomic_code_list.append(atomic_code_node)
     else:
       break
   return CodeNode(atomic_code_list)