YOUR NAME's CS132 programs: testing::internal::InitGoogleTestImpl
template<typename CharType > void testing::internal::InitGoogleTestImpl (int * argc, CharType ** argv)
Definition at line 5344 of file gtest.cc.
References g_argvs, GetUnitTestImpl(), ParseGoogleTestFlagsOnly(), testing::internal::UnitTestImpl::PostFlagParsingInit(), and StreamableToString().
Referenced by testing::InitGoogleTest().
{
   // We don't want to run the initialization code twice.
   if (GTestIsInitialized()) return;
   if (*argc <= 0) return;
   g_argvs.clear();
   for (int i = 0; i != *argc; i++) {
     g_argvs.push_back(StreamableToString(argv[i]));
   }
   ParseGoogleTestFlagsOnly(argc, argv);
   GetUnitTestImpl()->PostFlagParsingInit();
 }