YOUR NAME's CS132 programs: testing::internal::AlwaysFalse
bool testing::internal::AlwaysFalse () inline
Definition at line 736 of file gtest-internal.h.
References AlwaysTrue().
Referenced by ColoredPrintf(), TEST(), and TEST().
 { return !AlwaysTrue(); }