YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (MatcherTest , MatchAndExplain)
Definition at line 356 of file gmock-matchers_test.cc.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, GreaterThan(), testing::internal::MatcherBase< T >::MatchAndExplain(), and testing::StringMatchResultListener::str().
{
   Matcher<int> m = GreaterThan(0);
   StringMatchResultListener listener1;
   EXPECT_TRUE(m.MatchAndExplain(42, &listener1));
   EXPECT_EQ("which is 42 more than 0", listener1.str());
   StringMatchResultListener listener2;
   EXPECT_FALSE(m.MatchAndExplain(-9, &listener2));
   EXPECT_EQ("which is 9 less than 0", listener2.str());
 }