YOUR NAME's CS132 programs: testing::gmock_more_actions_test::TEST
testing::gmock_more_actions_test::TEST (InvokeTest , FunctionWithCompatibleType)
Definition at line 358 of file gmock-more-actions_test.cc.
References Char(), EXPECT_EQ, testing::Invoke(), std::tr1::make_tuple(), testing::Action< F >::Perform(), Short(), and SumOf4().
{
   Action<long(int, short, char, bool)> a = Invoke(SumOf4);  // NOLINT
   EXPECT_EQ(4321, a.Perform(make_tuple(4000, Short(300), Char(20), true)));
 }