YOUR NAME's CS132 programs: gtest_test_utils.GetTestExecutablePath
def gtest_test_utils.GetTestExecutablePath (executable_name, build_dir = None)
Returns the absolute path of the test binary given its name.
The function will print a message and abort the program if the resulting file
doesn't exist.
Args:
  executable_name: name of the test binary that the test script runs.
  build_dir:       directory where to look for executables, by default
                   the result of GetBuildDir().
Returns:
  The absolute path of the test binary.
Definition at line 156 of file gtest_test_utils.py.
References GetBuildDir().
Referenced by gmock_test_utils.GetTestExecutablePath(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testDefaultOutputFile(), gtest_xml_output_unittest.GTestXMLOutputUnitTest.testFilteredTestXmlOutput(), and gtest_xml_outfiles_test.GTestXMLOutFilesTest.testOutfile2().
 def GetTestExecutablePath(executable_name, build_dir=None):
   """Returns the absolute path of the test binary given its name.
   The function will print a message and abort the program if the resulting file
   doesn't exist.
   Args:
     executable_name: name of the test binary that the test script runs.
     build_dir:       directory where to look for executables, by default
                      the result of GetBuildDir().
   Returns:
     The absolute path of the test binary.
   """
   path = os.path.abspath(os.path.join(build_dir or GetBuildDir(),
                                       executable_name))
   if (IS_WINDOWS or IS_CYGWIN) and not path.endswith('.exe'):
     path += '.exe'
   if not os.path.exists(path):
     message = (
         'Unable to find the test binary "%s". Please make sure to provide\n'
         'a path to the binary via the --build_dir flag or the BUILD_DIR\n'
         'environment variable.' % path)
     sys.stdout.write(message)
     sys.exit(1)
   return path