YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AllOfTest , MatchesWhenAllMatch)
Definition at line 2057 of file gmock-matchers_test.cc.
References testing::AllOf(), AllOfMatches(), Describe(), testing::EndsWith(), EXPECT_FALSE, EXPECT_THAT, EXPECT_TRUE, testing::Ge(), testing::Gt(), testing::Le(), testing::Lt(), testing::internal::MatcherBase< T >::Matches(), testing::Ne(), and testing::internal::TEST().
{
   Matcher<int> m;
   m = AllOf(Le(2), Ge(1));
   EXPECT_TRUE(m.Matches(1));
   EXPECT_TRUE(m.Matches(2));
   EXPECT_FALSE(m.Matches(0));
   EXPECT_FALSE(m.Matches(3));
   m = AllOf(Gt(0), Ne(1), Ne(2));
   EXPECT_TRUE(m.Matches(3));
   EXPECT_FALSE(m.Matches(2));
   EXPECT_FALSE(m.Matches(1));
   EXPECT_FALSE(m.Matches(0));
   m = AllOf(Gt(0), Ne(1), Ne(2), Ne(3));
   EXPECT_TRUE(m.Matches(4));
   EXPECT_FALSE(m.Matches(3));
   EXPECT_FALSE(m.Matches(2));
   EXPECT_FALSE(m.Matches(1));
   EXPECT_FALSE(m.Matches(0));
   m = AllOf(Ge(0), Lt(10), Ne(3), Ne(5), Ne(7));
   EXPECT_TRUE(m.Matches(0));
   EXPECT_TRUE(m.Matches(1));
   EXPECT_FALSE(m.Matches(3));
   // The following tests for varying number of sub-matchers. Due to the way
   // the sub-matchers are handled it is enough to test every sub-matcher once
   // with sub-matchers using the same matcher type. Varying matcher types are
   // checked for above.
   AllOfMatches(2, AllOf(Ne(1), Ne(2)));
   AllOfMatches(3, AllOf(Ne(1), Ne(2), Ne(3)));
   AllOfMatches(4, AllOf(Ne(1), Ne(2), Ne(3), Ne(4)));
   AllOfMatches(5, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5)));
   AllOfMatches(6, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6)));
   AllOfMatches(7, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7)));
   AllOfMatches(8, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7),
                         Ne(8)));
   AllOfMatches(9, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7),
                         Ne(8), Ne(9)));
   AllOfMatches(10, AllOf(Ne(1), Ne(2), Ne(3), Ne(4), Ne(5), Ne(6), Ne(7), Ne(8),
                          Ne(9), Ne(10)));
 }