YOUR NAME's CS132 programs: testing::gtest_printers_test::Print
template<typename T > string testing::gtest_printers_test::Print (const T & value)
Definition at line 235 of file gtest-printers_test.cc.
Referenced by testing::internal::MatchesRegexMatcher::DescribeNegationTo(), testing::internal::MatchesRegexMatcher::DescribeTo(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeTo(), testing::internal::RefMatcher< T & >::operator Matcher< Super & >(), testing::internal::UniversalTersePrinter< T[N]>::Print(), testing::internal::UniversalTersePrinter< char * >::Print(), testing::internal::UniversalTersePrinter< wchar_t * >::Print(), PrintArrayHelper(), PrintByRef(), testing::internal::PrintTo(), TEST(), testing::internal::UniversalPrint(), and testing::internal::UniversalTersePrint().
{
   ::std::stringstream ss;
   UniversalPrinter<T>::Print(value, &ss);
   return ss.str();
 }