YOUR NAME's CS132 programs: testing::ContainsRegex
PolymorphicMatcher<internal::MatchesRegexMatcher> testing::ContainsRegex (const internal::string & regex) inline
Definition at line 4020 of file gmock-matchers.h.
References ContainsRegex(), EndsWith(), HasSubstr(), MakePolymorphicMatcher(), StartsWith(), StrCaseEq(), StrCaseNe(), StrEq(), and StrNe().
{
   return ContainsRegex(new internal::RE(regex));
 }