YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PointeeTest , CanExplainMatchResult)
Definition at line 3339 of file gmock-matchers_test.cc.
References EXPECT_EQ, Explain(), GreaterThan(), OfType(), testing::Pointee(), and testing::StartsWith().
{
   const Matcher<const string*> m = Pointee(StartsWith("Hi"));
   EXPECT_EQ("", Explain(m, static_cast<const string*>(NULL)));
   const Matcher<long*> m2 = Pointee(GreaterThan(1));  // NOLINT
   long n = 3;  // NOLINT
   EXPECT_EQ("which points to 3" + OfType("long") + ", which is 2 more than 1",
             Explain(m2, &n));
 }