YOUR NAME's CS132 programs: gtest_color_test.UsesColor
def gtest_color_test.UsesColor (term, color_env_var, color_flag)
Runs gtest_color_test_ and returns its exit code.
Definition at line 56 of file gtest_color_test.py.
References SetEnvVar().
Referenced by gtest_color_test.GTestColorTest.testAliasesOfYesAndNo(), gtest_color_test.GTestColorTest.testEnvVarAndFlag(), gtest_color_test.GTestColorTest.testEnvVarOnly(), gtest_color_test.GTestColorTest.testFlagOnly(), and gtest_color_test.GTestColorTest.testNoEnvVarNoFlag().
 def UsesColor(term, color_env_var, color_flag):
   """Runs gtest_color_test_ and returns its exit code."""
   SetEnvVar('TERM', term)
   SetEnvVar(COLOR_ENV_VAR, color_env_var)
   if color_flag is None:
     args = []
   else:
     args = ['--%s=%s' % (COLOR_FLAG, color_flag)]
   p = gtest_test_utils.Subprocess([COMMAND] + args)
   return not p.exited or p.exit_code