YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ResultOfTest , CanExplainMatchResult)
Definition at line 3824 of file gmock-matchers_test.cc.
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), IntFunction(), OfType(), and testing::ResultOf().
{
   Matcher<int> matcher = ResultOf(&IntFunction, Ge(85));
   EXPECT_EQ("which is mapped by the given callable to 90" + OfType("int"),
             Explain(matcher, 36));
   matcher = ResultOf(&IntFunction, GreaterThan(85));
   EXPECT_EQ("which is mapped by the given callable to 90" + OfType("int") +
             ", which is 5 more than 85", Explain(matcher, 36));
 }