YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AllOfTest , ExplainsResult)
Definition at line 2200 of file gmock-matchers_test.cc.
References testing::AllOf(), EXPECT_EQ, Explain(), GreaterThan(), and testing::Lt().
{
   Matcher<int> m;
   // Successful match.  Both matchers need to explain.  The second
   // matcher doesn't give an explanation, so only the first matcher's
   // explanation is printed.
   m = AllOf(GreaterThan(10), Lt(30));
   EXPECT_EQ("which is 15 more than 10", Explain(m, 25));
   // Successful match.  Both matchers need to explain.
   m = AllOf(GreaterThan(10), GreaterThan(20));
   EXPECT_EQ("which is 20 more than 10, and which is 10 more than 20",
             Explain(m, 30));
   // Successful match.  All matchers need to explain.  The second
   // matcher doesn't given an explanation.
   m = AllOf(GreaterThan(10), Lt(30), GreaterThan(20));
   EXPECT_EQ("which is 15 more than 10, and which is 5 more than 20",
             Explain(m, 25));
   // Successful match.  All matchers need to explain.
   m = AllOf(GreaterThan(10), GreaterThan(20), GreaterThan(30));
   EXPECT_EQ("which is 30 more than 10, and which is 20 more than 20, "
             "and which is 10 more than 30",
             Explain(m, 40));
   // Failed match.  The first matcher, which failed, needs to
   // explain.
   m = AllOf(GreaterThan(10), GreaterThan(20));
   EXPECT_EQ("which is 5 less than 10", Explain(m, 5));
   // Failed match.  The second matcher, which failed, needs to
   // explain.  Since it doesn't given an explanation, nothing is
   // printed.
   m = AllOf(GreaterThan(10), Lt(30));
   EXPECT_EQ("", Explain(m, 40));
   // Failed match.  The second matcher, which failed, needs to
   // explain.
   m = AllOf(GreaterThan(10), GreaterThan(20));
   EXPECT_EQ("which is 5 less than 20", Explain(m, 15));
 }