YOUR NAME's CS132 programs: testing::TEST_F
testing::TEST_F (CurrentTestInfoTest , WorksForFirstTestInATestCase)
Definition at line 6533 of file gtest_unittest.cc.
References ASSERT_TRUE, testing::UnitTest::current_test_info(), EXPECT_STREQ, testing::UnitTest::GetInstance(), testing::TestInfo::name(), and testing::TestInfo::test_case_name().
{
   const TestInfo* test_info =
     UnitTest::GetInstance()->current_test_info();
   ASSERT_TRUE(NULL != test_info)
       << "There is a test running so we should have a valid TestInfo.";
   EXPECT_STREQ("CurrentTestInfoTest", test_info->test_case_name())
       << "Expected the name of the currently running test case.";
   EXPECT_STREQ("WorksForFirstTestInATestCase", test_info->name())
       << "Expected the name of the currently running test.";
 }