YOUR NAME's CS132 programs: testing::internal::GetRandomSeedFromFlag
int testing::internal::GetRandomSeedFromFlag (Int32 random_seed_flag) inline
Definition at line 136 of file gtest-internal-inl.h.
References GetTimeInMillis().
Referenced by operator<<(), and testing::internal::UnitTestImpl::RunAllTests().
{
   const unsigned int raw_seed = (random_seed_flag == 0) ?
       static_cast<unsigned int>(GetTimeInMillis()) :
       static_cast<unsigned int>(random_seed_flag);
   // Normalizes the actual seed to range [1, kMaxRandomSeed] such that
   // it's easy to type.
   const int normalized_seed =
       static_cast<int>((raw_seed - 1U) %
                        static_cast<unsigned int>(kMaxRandomSeed)) + 1;
   return normalized_seed;
 }