YOUR NAME's CS132 programs: fuse_gtest_files.FuseGTest
def fuse_gtest_files.FuseGTest (gtest_root, output_dir)
Fuses gtest.h and gtest-all.cc.
Definition at line 229 of file fuse_gtest_files.py.
References FuseGTestAllCc(), FuseGTestH(), ValidateGTestRootDir(), and ValidateOutputDir().
Referenced by main().
 def FuseGTest(gtest_root, output_dir):
   """Fuses gtest.h and gtest-all.cc."""
   ValidateGTestRootDir(gtest_root)
   ValidateOutputDir(output_dir)
   FuseGTestH(gtest_root, output_dir)
   FuseGTestAllCc(gtest_root, output_dir)