YOUR NAME's CS132 programs: gen_gtest_pred_impl.ImplementationForArity
def gen_gtest_pred_impl.ImplementationForArity (n)
Returns the implementation of n-ary predicate assertions.
Definition at line 205 of file gen_gtest_pred_impl.py.
References Arity(), Iter(), and Title().
Referenced by GenerateHeader().
 def ImplementationForArity(n):
   """Returns the implementation of n-ary predicate assertions."""
   # A map the defines the values used in the implementation template.
   DEFS = {
     'n' : str(n),
     'vs' : Iter(n, 'v%s', sep=', '),
     'vts' : Iter(n, '#v%s', sep=', '),
     'arity' : Arity(n),
     'Arity' : Title(Arity(n))
     }
   impl = """
 // Helper function for implementing {EXPECT|ASSERT}_PRED%(n)s.  Don't use
 // this in your code.
 template <typename Pred""" % DEFS
   impl += Iter(n, """,
           typename T%s""")
   impl += """>
 AssertionResult AssertPred%(n)sHelper(const char* pred_text""" % DEFS
   impl += Iter(n, """,
                                   const char* e%s""")
   impl += """,
                                   Pred pred"""
   impl += Iter(n, """,
                                   const T%s& v%s""")
   impl += """) {
   if (pred(%(vs)s)) return AssertionSuccess();
 """ % DEFS
   impl += '  return AssertionFailure() << pred_text << "("'
   impl += Iter(n, """
                             << e%s""", sep=' << ", "')
   impl += ' << ") evaluates to false, where"'
   impl += Iter(n, """
                             << "\\n" << e%s << " evaluates to " << v%s""")
   impl += """;
 }
 // Internal macro for implementing {EXPECT|ASSERT}_PRED_FORMAT%(n)s.
 // Don't use this in your code.
 #define GTEST_PRED_FORMAT%(n)s_(pred_format, %(vs)s, on_failure)\\
   GTEST_ASSERT_(pred_format(%(vts)s, %(vs)s), \\
                 on_failure)
 // Internal macro for implementing {EXPECT|ASSERT}_PRED%(n)s.  Don't use
 // this in your code.
 #define GTEST_PRED%(n)s_(pred, %(vs)s, on_failure)\\
   GTEST_ASSERT_(::testing::AssertPred%(n)sHelper(#pred""" % DEFS
   impl += Iter(n, """, \\
                                              #v%s""")
   impl += """, \\
                                              pred"""
   impl += Iter(n, """, \\
                                              v%s""")
   impl += """), on_failure)
 // %(Arity)s predicate assertion macros.
 #define EXPECT_PRED_FORMAT%(n)s(pred_format, %(vs)s) \\
   GTEST_PRED_FORMAT%(n)s_(pred_format, %(vs)s, GTEST_NONFATAL_FAILURE_)
 #define EXPECT_PRED%(n)s(pred, %(vs)s) \\
   GTEST_PRED%(n)s_(pred, %(vs)s, GTEST_NONFATAL_FAILURE_)
 #define ASSERT_PRED_FORMAT%(n)s(pred_format, %(vs)s) \\
   GTEST_PRED_FORMAT%(n)s_(pred_format, %(vs)s, GTEST_FATAL_FAILURE_)
 #define ASSERT_PRED%(n)s(pred, %(vs)s) \\
   GTEST_PRED%(n)s_(pred, %(vs)s, GTEST_FATAL_FAILURE_)
 """ % DEFS
   return impl