YOUR NAME's CS132 programs: testing::ElementsAre
internal::ElementsAreMatcher< ::testing::tuple<> > testing::ElementsAre () inline
Definition at line 570 of file gmock-generated-matchers.h.
References Args().
Referenced by TEST(), testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
               {
   typedef ::testing::tuple<> Args;
   return internal::ElementsAreMatcher<Args>(Args());
 }