YOUR NAME's CS132 programs: testing::Value
template<typename T , typename M > bool testing::Value (const T & value, M matcher) inline
Definition at line 4347 of file gmock-matchers.h.
References Matches().
Referenced by testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo(), and testing::gmock_matchers_test::TEST().
{
   return testing::Matches(matcher)(value);
 }