YOUR NAME's CS132 programs: testing::Eq
template<typename T > internal::EqMatcher<T> testing::Eq (T x) inline
Definition at line 3742 of file gmock-matchers.h.
Referenced by std::tr1::gtest_internal::SameSizeTuplePrefixComparator< k, k >::Eq(), testing::Matcher< T >::Matcher(), testing::Matcher< const internal::string & >::Matcher(), testing::Matcher< internal::string >::Matcher(), std::tr1::operator==(), testing::internal::ExpectationTester::SetCallCount(), testing::gmock_matchers_test::TEST(), TEST(), testing::gmock_generated_function_mockers_test::TEST_F(), testing::gmock_matchers_test::TEST_F(), and TypedEq().
 { return internal::EqMatcher<T>(x); }