YOUR NAME's CS132 programs: testing::internal::GetCurrentExecutableName
FilePath testing::internal::GetCurrentExecutableName ()
Definition at line 399 of file gtest.cc.
References GetArgvs(), testing::internal::FilePath::RemoveDirectoryName(), and testing::internal::FilePath::Set().
Referenced by testing::internal::UnitTestOptions::GetAbsolutePathToOutputFile(), and testing::TEST_F().
{
   FilePath result;
 #if GTEST_OS_WINDOWS
   result.Set(FilePath(GetArgvs()[0]).RemoveExtension("exe"));
 #else
   result.Set(FilePath(GetArgvs()[0]));
 #endif  // GTEST_OS_WINDOWS
   return result.RemoveDirectoryName();
 }