YOUR NAME's CS132 programs: gmock_output_test.GetNormalizedCommandOutputAndLeakyTests
def gmock_output_test.GetNormalizedCommandOutputAndLeakyTests (cmd)
Runs a command and returns its normalized output and a list of leaky tests.
Args:
  cmd:  the shell command.
Definition at line 144 of file gmock_output_test.py.
References GetNormalizedOutputAndLeakyTests(), and GetShellCommandOutput().
Referenced by gmock_output_test.GMockOutputTest.testOutput().
 def GetNormalizedCommandOutputAndLeakyTests(cmd):
   """Runs a command and returns its normalized output and a list of leaky tests.
   Args:
     cmd:  the shell command.
   """
   # Disables exception pop-ups on Windows.
   os.environ['GTEST_CATCH_EXCEPTIONS'] = '1'
   return GetNormalizedOutputAndLeakyTests(GetShellCommandOutput(cmd))