YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST_F
testing::gmock_generated_function_mockers_test::TEST_F (FunctionMockerTest , MocksFunctionWithNonConstReferenceArgument)
Definition at line 234 of file gmock-generated-function-mockers_test.cc.
References EXPECT_CALL, EXPECT_TRUE, testing::Ref(), testing::Return(), and testing::gmock_generated_function_mockers_test::FooInterface::TakesNonConstReference().
{
   int a = 0;
   EXPECT_CALL(mock_foo_, TakesNonConstReference(Ref(a)))
       .WillOnce(Return(true));
   EXPECT_TRUE(foo_->TakesNonConstReference(a));
 }