YOUR NAME's CS132 programs: testing::internal::DoubleNearPredFormat
AssertionResult testing::internal::DoubleNearPredFormat (const char * expr1, const char * expr2, const char * abs_error_expr, double val1, double val2, double abs_error)
Definition at line 1362 of file gtest.cc.
References testing::AssertionFailure(), and testing::AssertionSuccess().
Referenced by CmpHelperFloatingPointEQ().
{
   const double diff = fabs(val1 - val2);
   if (diff <= abs_error) return AssertionSuccess();
   // TODO(wan): do not print the value of an expression if it's
   // already a literal.
   return AssertionFailure()
       << "The difference between " << expr1 << " and " << expr2
       << " is " << diff << ", which exceeds " << abs_error_expr << ", where\n"
       << expr1 << " evaluates to " << val1 << ",\n"
       << expr2 << " evaluates to " << val2 << ", and\n"
       << abs_error_expr << " evaluates to " << abs_error << ".";
 }