YOUR NAME's CS132 programs: pump.WrapLongLine
def pump.WrapLongLine (line, output)
Definition at line 790 of file pump.py.
References IsHeaderGuardIncludeOrOneLineIWYUPragma(), IsInPreprocessorDirective(), IsMultiLineIWYUPragma(), IsSingleLineComment(), WrapComment(), WrapPlainCode(), and WrapPreprocessorDirective().
Referenced by BeautifyCode().
 def WrapLongLine(line, output):
   line = line.rstrip()
   if len(line) <= 80:
     output.append(line)
   elif IsSingleLineComment(line):
     if IsHeaderGuardIncludeOrOneLineIWYUPragma(line):
       # The style guide made an exception to allow long header guard lines,
       # includes and IWYU pragmas.
       output.append(line)
     else:
       WrapComment(line, output)
   elif IsInPreprocessorDirective(output, line):
     if IsHeaderGuardIncludeOrOneLineIWYUPragma(line):
       # The style guide made an exception to allow long header guard lines,
       # includes and IWYU pragmas.
       output.append(line)
     else:
       WrapPreprocessorDirective(line, output)
   elif IsMultiLineIWYUPragma(line):
     output.append(line)
   else:
     WrapPlainCode(line, output)