YOUR NAME's CS132 programs: testing::internal::ParseGoogleTestFlag
bool testing::internal::ParseGoogleTestFlag (const char *const arg)
Definition at line 5223 of file gtest.cc.
References testing::internal::UnitTestImpl::catch_exceptions(), testing::internal::posix::FClose(), testing::internal::posix::FOpen(), g_help_flag, GTEST_FLAG, kAlsoRunDisabledTestsFlag, kBreakOnFailureFlag, kCatchExceptionsFlag, kColorFlag, kDeathTestStyleFlag, kDeathTestUseFork, kFilterFlag, kInternalRunDeathTestFlag, kListTestsFlag, kOutputFlag, kPrintTimeFlag, kRandomSeedFlag, kRepeatFlag, kShuffleFlag, kStackTraceDepthFlag, kStreamResultToFlag, kThrowOnFailureFlag, gmock_output_test::output, ParseBoolFlag(), ParseInt32Flag(), ParseStringFlag(), testing::internal::UnitTestImpl::random_seed(), ReadEntireFile(), and SplitString().
Referenced by ParseGoogleTestFlagsOnlyImpl().
{
   return ParseBoolFlag(arg, kAlsoRunDisabledTestsFlag,
                        &GTEST_FLAG(also_run_disabled_tests)) ||
       ParseBoolFlag(arg, kBreakOnFailureFlag,
                     &GTEST_FLAG(break_on_failure)) ||
       ParseBoolFlag(arg, kCatchExceptionsFlag,
                     &GTEST_FLAG(catch_exceptions)) ||
       ParseStringFlag(arg, kColorFlag, &GTEST_FLAG(color)) ||
       ParseStringFlag(arg, kDeathTestStyleFlag,
                       &GTEST_FLAG(death_test_style)) ||
       ParseBoolFlag(arg, kDeathTestUseFork,
                     &GTEST_FLAG(death_test_use_fork)) ||
       ParseStringFlag(arg, kFilterFlag, &GTEST_FLAG(filter)) ||
       ParseStringFlag(arg, kInternalRunDeathTestFlag,
                       &GTEST_FLAG(internal_run_death_test)) ||
       ParseBoolFlag(arg, kListTestsFlag, &GTEST_FLAG(list_tests)) ||
       ParseStringFlag(arg, kOutputFlag, &GTEST_FLAG(output)) ||
       ParseBoolFlag(arg, kPrintTimeFlag, &GTEST_FLAG(print_time)) ||
       ParseInt32Flag(arg, kRandomSeedFlag, &GTEST_FLAG(random_seed)) ||
       ParseInt32Flag(arg, kRepeatFlag, &GTEST_FLAG(repeat)) ||
       ParseBoolFlag(arg, kShuffleFlag, &GTEST_FLAG(shuffle)) ||
       ParseInt32Flag(arg, kStackTraceDepthFlag,
                      &GTEST_FLAG(stack_trace_depth)) ||
       ParseStringFlag(arg, kStreamResultToFlag,
                       &GTEST_FLAG(stream_result_to)) ||
       ParseBoolFlag(arg, kThrowOnFailureFlag,
                     &GTEST_FLAG(throw_on_failure));
 }