YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForMultiMapTypes)
Definition at line 4452 of file gmock-matchers_test.cc.
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), testing::Pair(), and testing::WhenSorted().
{
     multimap<int, int> ifib;
     ifib.insert(make_pair(8, 6));
     ifib.insert(make_pair(2, 3));
     ifib.insert(make_pair(1, 1));
     ifib.insert(make_pair(3, 4));
     ifib.insert(make_pair(1, 2));
     ifib.insert(make_pair(5, 5));
     EXPECT_THAT(ifib, WhenSorted(ElementsAre(Pair(1, 1),
                                              Pair(1, 2),
                                              Pair(2, 3),
                                              Pair(3, 4),
                                              Pair(5, 5),
                                              Pair(8, 6))));
     EXPECT_THAT(ifib, Not(WhenSorted(ElementsAre(Pair(8, 6),
                                                  Pair(2, 3),
                                                  Pair(1, 1),
                                                  Pair(3, 4),
                                                  Pair(1, 2),
                                                  Pair(5, 5)))));
 }