YOUR NAME's CS132 programs: testing::gmock_matchers_test::ValueIsPositive
bool testing::gmock_matchers_test::ValueIsPositive (const Uncopyable & x)
Definition at line 3371 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Uncopyable::value().
Referenced by TEST(), and TEST_F().
 { return x.value() > 0; }