YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ResultOfTest , CanDescribeItself)
Definition at line 3812 of file gmock-matchers_test.cc.
References Describe(), DescribeNegation(), EXPECT_EQ, IntToStringFunction(), testing::ResultOf(), and testing::StrEq().
{
   Matcher<int> matcher = ResultOf(&IntToStringFunction, StrEq("foo"));
   EXPECT_EQ("is mapped by the given callable to a value that "
             "is equal to \"foo\"", Describe(matcher));
   EXPECT_EQ("is mapped by the given callable to a value that "
             "isn't equal to \"foo\"", DescribeNegation(matcher));
 }