YOUR NAME's CS132 programs: upload.StatusUpdate
def upload.StatusUpdate (msg)
Print a status message to stdout.
If 'verbosity' is greater than 0, print the message.
Args:
  msg: The string to print.
Definition at line 97 of file upload.py.
Referenced by upload.SubversionVCS.GetBaseFile(), upload.MercurialVCS.GetBaseFile(), main(), RealMain(), upload.AbstractRpcServer.Send(), upload.VersionControlSystem.UploadBaseFiles(), and UploadSeparatePatches().
 def StatusUpdate(msg):
   """Print a status message to stdout.
   If 'verbosity' is greater than 0, print the message.
   Args:
     msg: The string to print.
   """
   if verbosity > 0:
     print msg