YOUR NAME's CS132 programs: testing::internal::HasOneFailure
AssertionResult testing::internal::HasOneFailure (const char * , const char * , const char * , const TestPartResultArray & results, TestPartResult::Type type, const string & substr)
Definition at line 631 of file gtest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), testing::TestPartResultArray::GetTestPartResult(), testing::TestPartResult::kFatalFailure, testing::TestPartResult::message(), testing::TestPartResultArray::size(), testing::TestPartResult::type(), and upload::type.
Referenced by testing::internal::SingleFailureChecker::~SingleFailureChecker().
{
   const std::string expected(type == TestPartResult::kFatalFailure ?
                         "1 fatal failure" :
                         "1 non-fatal failure");
   Message msg;
   if (results.size() != 1) {
     msg << "Expected: " << expected << "\n"
         << "  Actual: " << results.size() << " failures";
     for (int i = 0; i < results.size(); i++) {
       msg << "\n" << results.GetTestPartResult(i);
     }
     return AssertionFailure() << msg;
   }
   const TestPartResult& r = results.GetTestPartResult(0);
   if (r.type() != type) {
     return AssertionFailure() << "Expected: " << expected << "\n"
                               << "  Actual:\n"
                               << r;
   }
   if (strstr(r.message(), substr.c_str()) == NULL) {
     return AssertionFailure() << "Expected: " << expected << " containing \""
                               << substr << "\"\n"
                               << "  Actual:\n"
                               << r;
   }
   return AssertionSuccess();
 }