YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (UnorderedElementsAreArrayTest , VectorBool)
Definition at line 4715 of file gmock-matchers_test.cc.
References EXPECT_TRUE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
{
   const bool a[] = {0, 1, 0, 1, 1};
   const bool b[] = {1, 0, 1, 1, 0};
   std::vector<bool> expected(a, a + GTEST_ARRAY_SIZE_(a));
   std::vector<bool> actual(b, b + GTEST_ARRAY_SIZE_(b));
   StringMatchResultListener listener;
   EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(expected),
                                  actual, &listener)) << listener.str();
 }