YOUR NAME's CS132 programs: testing::internal::GetCapturedStdout
GTEST_API_ std::string testing::internal::GetCapturedStdout ()
Referenced by CheckedDowncastToActualType(), testing::internal::ExpectationTester::SetCallCount(), testing::gmock_nice_strict_test::MockBar::str(), testing::gmock_nice_strict_test::TEST(), TEST(), testing::InitGoogleTestTest::TestParsingFlags(), and testing::internal::GTestLog::~GTestLog().