YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (UnorderedPointwiseTest , RejectsWrongSize)
Definition at line 5607 of file gmock-matchers_test.cc.
References EXPECT_EQ, EXPECT_THAT, Explain(), testing::Gt(), testing::Not(), and testing::UnorderedPointwise().
{
   const double lhs[2] = {1, 2};
   const int rhs[1] = {0};
   EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs)));
   EXPECT_EQ("which has 2 elements",
             Explain(UnorderedPointwise(Gt(), rhs), lhs));
   const int rhs2[3] = {0, 1, 2};
   EXPECT_THAT(lhs, Not(UnorderedPointwise(Gt(), rhs2)));
 }