YOUR NAME's CS132 programs: gmock_output_test.GetNormalizedOutputAndLeakyTests
def gmock_output_test.GetNormalizedOutputAndLeakyTests (output)
Normalizes the output of gmock_output_test_.
Args:
  output: The test output.
Returns:
  A tuple (the normalized test output, the list of test names that have
  leaked mocks).
Definition at line 119 of file gmock_output_test.py.
References GetLeakyTests(), NormalizeErrorMarker(), RemoveLocations(), RemoveMemoryAddresses(), RemoveReportHeaderAndFooter(), RemoveTestNamesOfLeakedMocks(), and ToUnixLineEnding().
Referenced by GetNormalizedCommandOutputAndLeakyTests().
 def GetNormalizedOutputAndLeakyTests(output):
   """Normalizes the output of gmock_output_test_.
   Args:
     output: The test output.
   Returns:
     A tuple (the normalized test output, the list of test names that have
     leaked mocks).
   """
   output = ToUnixLineEnding(output)
   output = RemoveReportHeaderAndFooter(output)
   output = NormalizeErrorMarker(output)
   output = RemoveLocations(output)
   output = RemoveMemoryAddresses(output)
   return (RemoveTestNamesOfLeakedMocks(output), GetLeakyTests(output))