YOUR NAME's CS132 programs: testing::internal::Expect
void testing::internal::Expect (bool condition, const char * file, int line, const string & msg) inline
Definition at line 294 of file gmock-internal-utils.h.
Referenced by Expect(), testing::internal::UntypedOnCallSpecBase::ExpectSpecProperty(), testing::internal::ExpectationBase::ExpectSpecProperty(), ReportUninterestingCall(), testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith(), and testing::internal::UntypedFunctionMockerBase::VerifyAndClearExpectationsLocked().
{
   if (!condition) {
     GetFailureReporter()->ReportFailure(FailureReporterInterface::kNonfatal,
                                         file, line, msg);
   }
 }