YOUR NAME's CS132 programs: gtest_filter_unittest.RunAndExtractTestList
def gtest_filter_unittest.RunAndExtractTestList (args = None)
Runs the test program and returns its exit code and a list of tests run.
Definition at line 188 of file gtest_filter_unittest.py.
Referenced by gtest_filter_unittest.GTestFilterUnitTest.RunAndVerify(), gtest_filter_unittest.GTestFilterUnitTest.RunAndVerifyAllowingDisabled(), and gtest_filter_unittest.GTestFilterUnitTest.testFlagOverridesEnvVar().
 def RunAndExtractTestList(args = None):
   """Runs the test program and returns its exit code and a list of tests run."""
   p = gtest_test_utils.Subprocess([COMMAND] + (args or []), env=environ)
   tests_run = []
   test_case = ''
   test = ''
   for line in p.output.split('\n'):
     match = TEST_CASE_REGEX.match(line)
     if match is not None:
       test_case = match.group(1)
     else:
       match = TEST_REGEX.match(line)
       if match is not None:
         test = match.group(1)
         tests_run.append(test_case + '.' + test)
   return (tests_run, p.exit_code)