YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (BeginEndDistanceIsTest , ExplainsResult)
Definition at line 4610 of file gmock-matchers_test.cc.
References testing::AnyOf(), testing::BeginEndDistanceIs(), EXPECT_EQ, Explain(), GreaterThan(), and testing::Lt().
{
   Matcher<vector<int> > m1 = BeginEndDistanceIs(2);
   Matcher<vector<int> > m2 = BeginEndDistanceIs(Lt(2));
   Matcher<vector<int> > m3 = BeginEndDistanceIs(AnyOf(0, 3));
   Matcher<vector<int> > m4 = BeginEndDistanceIs(GreaterThan(1));
   vector<int> container;
   EXPECT_EQ("whose distance between begin() and end() 0 doesn't match",
             Explain(m1, container));
   EXPECT_EQ("whose distance between begin() and end() 0 matches",
             Explain(m2, container));
   EXPECT_EQ("whose distance between begin() and end() 0 matches",
             Explain(m3, container));
   EXPECT_EQ(
       "whose distance between begin() and end() 0 doesn't match, which is 1 "
       "less than 1",
       Explain(m4, container));
   container.push_back(0);
   container.push_back(0);
   EXPECT_EQ("whose distance between begin() and end() 2 matches",
             Explain(m1, container));
   EXPECT_EQ("whose distance between begin() and end() 2 doesn't match",
             Explain(m2, container));
   EXPECT_EQ("whose distance between begin() and end() 2 doesn't match",
             Explain(m3, container));
   EXPECT_EQ(
       "whose distance between begin() and end() 2 matches, which is 1 more "
       "than 1",
       Explain(m4, container));
 }