YOUR NAME's CS132 programs: pump.Eof
def pump.Eof ()
Returns the special cursor to denote the end-of-file.
Definition at line 132 of file pump.py.
Referenced by pump.Cursor.__str__(), SubString(), and TokenizeLines().
 def Eof():
   """Returns the special cursor to denote the end-of-file."""
   return Cursor(-1, -1)