YOUR NAME's CS132 programs: testing::internal::TEST_F
testing::internal::TEST_F (ListenerTest , DoesFoo)
Definition at line 158 of file gtest-listener_test.cc.
References g_events, and SUCCEED.
Referenced by operator<<(), testing::TEST(), and testing::TEST_F().
{
   // Test execution order within a test case is not guaranteed so we are not
   // recording the test name.
   g_events->push_back("ListenerTest::* Test Body");
   SUCCEED();  // Triggers OnTestPartResult.
 }