YOUR NAME's CS132 programs: testing::gmock_matchers_test::Describe
template<typename T > string testing::gmock_matchers_test::Describe (const Matcher< T > & m)
Definition at line 202 of file gmock-matchers_test.cc.
References testing::internal::MatcherBase< T >::DescribeTo().
Referenced by AllOfMatches(), AnyOfMatches(), MATCHER_P(), TEST(), and TEST_F().
{
   stringstream ss;
   m.DescribeTo(&ss);
   return ss.str();
 }