YOUR NAME's CS132 programs: pump.ParseExpTokenInParens
def pump.ParseExpTokenInParens (lines, pos)
Definition at line 281 of file pump.py.
References MakeToken(), Skip(), SkipUntil(), and SubString().
Referenced by TokenizeLines().
 def ParseExpTokenInParens(lines, pos):
   def ParseInParens(pos):
     pos = Skip(lines, pos, OPTIONAL_WHITE_SPACES_REGEX)
     pos = Skip(lines, pos, r'\(')
     pos = Parse(pos)
     pos = Skip(lines, pos, r'\)')
     return pos
   def Parse(pos):
     pos = SkipUntil(lines, pos, r'\(|\)', ')')
     if SubString(lines, pos, pos + 1) == '(':
       pos = Parse(pos + 1)
       pos = Skip(lines, pos, r'\)')
       return Parse(pos)
     else:
       return pos
   start = pos.Clone()
   pos = ParseInParens(pos)
   return MakeToken(lines, start, pos, 'exp')