YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PointwiseTest , RejectsWrongSize)
Definition at line 5496 of file gmock-matchers_test.cc.
References EXPECT_EQ, EXPECT_THAT, Explain(), testing::Gt(), testing::Not(), and testing::Pointwise().
{
   const double lhs[2] = {1, 2};
   const int rhs[1] = {0};
   EXPECT_THAT(lhs, Not(Pointwise(Gt(), rhs)));
   EXPECT_EQ("which contains 2 values",
             Explain(Pointwise(Gt(), rhs), lhs));
   const int rhs2[3] = {0, 1, 2};
   EXPECT_THAT(lhs, Not(Pointwise(Gt(), rhs2)));
 }