YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AnyOfTest , CanDescribeNegation)
Definition at line 2343 of file gmock-matchers_test.cc.
References testing::AnyOf(), DescribeNegation(), testing::Eq(), EXPECT_EQ, testing::Ge(), testing::Gt(), testing::Le(), and testing::Lt().
{
   Matcher<int> m;
   m = AnyOf(Le(1), Ge(3));
   EXPECT_EQ("(isn't <= 1) and (isn't >= 3)",
             DescribeNegation(m));
   m = AnyOf(Lt(0), Eq(1), Eq(2));
   EXPECT_EQ("(isn't < 0) and "
             "((isn't equal to 1) and (isn't equal to 2))",
             DescribeNegation(m));
   m = AnyOf(Lt(0), Eq(1), Eq(2), Eq(3));
   EXPECT_EQ("((isn't < 0) and "
             "(isn't equal to 1)) and "
             "((isn't equal to 2) and "
             "(isn't equal to 3))",
             DescribeNegation(m));
   m = AnyOf(Le(0), Gt(10), 3, 5, 7);
   EXPECT_EQ("((isn't <= 0) and "
             "(isn't > 10)) and "
             "((isn't equal to 3) and "
             "((isn't equal to 5) and "
             "(isn't equal to 7)))",
             DescribeNegation(m));
 }