YOUR NAME's CS132 programs: pump.SubString
def pump.SubString (lines, start, end)
Returns a substring in lines.
Definition at line 208 of file pump.py.
References Eof().
Referenced by MakeToken(), ParseExpTokenInParens(), and TokenizeLines().
 def SubString(lines, start, end):
   """Returns a substring in lines."""
   if end == Eof():
     end = Cursor(len(lines) - 1, len(lines[-1]))
   if start >= end:
     return ''
   if start.line == end.line:
     return lines[start.line][start.column:end.column]
   result_lines = ([lines[start.line][start.column:]] +
                   lines[start.line + 1:end.line] +
                   [lines[end.line][:end.column]])
   return ''.join(result_lines)