YOUR NAME's CS132 programs: testing::internal::WriteToShardStatusFileIfNeeded
void testing::internal::WriteToShardStatusFileIfNeeded ()
Definition at line 4693 of file gtest.cc.
References COLOR_RED, ColoredPrintf(), testing::internal::posix::FOpen(), and testing::internal::posix::GetEnv().
Referenced by testing::internal::UnitTestImpl::RunAllTests(), and testing::internal::GTestFlagSaver::~GTestFlagSaver().
{
   const char* const test_shard_file = posix::GetEnv(kTestShardStatusFile);
   if (test_shard_file != NULL) {
     FILE* const file = posix::FOpen(test_shard_file, "w");
     if (file == NULL) {
       ColoredPrintf(COLOR_RED,
                     "Could not write to the test shard status file \"%s\" "
                     "specified by the %s environment variable.\n",
                     test_shard_file, kTestShardStatusFile);
       fflush(stdout);
       exit(EXIT_FAILURE);
     }
     fclose(file);
   }
 }