YOUR NAME's CS132 programs: testing::AtLeast
GTEST_API_ Cardinality testing::AtLeast (int n)
Definition at line 140 of file gmock-cardinalities.cc.
References Between().
Referenced by AnyNumber(), testing::Cardinality::DescribeTo(), testing::internal::ExpectationTester::SetCallCount(), and testing::internal::TypedExpectation< F >::WillRepeatedly().
 { return Between(n, INT_MAX); }