YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ContainerEqExtraTest , MultipleValuesAddedAndRemoved)
Definition at line 4264 of file gmock-matchers_test.cc.
References testing::ContainerEq(), EXPECT_EQ, EXPECT_FALSE, Explain(), and testing::internal::MatcherBase< T >::Matches().
{
   static const int vals[] = {1, 1, 2, 3, 5, 8};
   static const int test_vals[] = {1, 2, 3, 92, 46};
   list<size_t> my_set(vals, vals + 6);
   list<size_t> test_set(test_vals, test_vals + 5);
   const Matcher<const list<size_t> > m = ContainerEq(my_set);
   EXPECT_FALSE(m.Matches(test_set));
   EXPECT_EQ("which has these unexpected elements: 92, 46,\n"
             "and doesn't have these expected elements: 5, 8",
             Explain(m, test_set));
 }