YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (ExplainMatchResultTest , AllOf_False_True)
Definition at line 4003 of file gmock-matchers_test.cc.
References testing::AllOf(), DivisibleBy(), EXPECT_EQ, and Explain().
{
   const Matcher<int> m = AllOf(DivisibleBy(4), DivisibleBy(3));
   EXPECT_EQ("which is 2 modulo 4", Explain(m, 6));
 }