YOUR NAME's CS132 programs: testing::internal::FormatMatcherDescription
GTEST_API_ string testing::internal::FormatMatcherDescription (bool negation, const char * matcher_name, const Strings & param_values)
Definition at line 127 of file gmock-matchers.cc.
References ConvertIdentifierNameToWords(), and JoinAsTuple().
Referenced by MatcherBindSecond(), and testing::gmock_matchers_test::TEST().
{
   string result = ConvertIdentifierNameToWords(matcher_name);
   if (param_values.size() >= 1)
     result += " " + JoinAsTuple(param_values);
   return negation ? "not (" + result + ")" : result;
 }