YOUR NAME's CS132 programs: testing::UnorderedPointwise
template<typename Tuple2Matcher , typename RhsContainer > internal::UnorderedElementsAreArrayMatcher< typename internal::BoundSecondMatcher< Tuple2Matcher, typename internal::StlContainerView<GTEST_REMOVE_CONST_(RhsContainer)>::type::value_type> > testing::UnorderedPointwise (const Tuple2Matcher & tuple2_matcher, const RhsContainer & rhs_container) inline
Definition at line 4223 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, testing::internal::MatcherBindSecond(), upload::type, and UnorderedElementsAreArray().
Referenced by testing::gmock_matchers_test::TEST().
{
   // This following line is for working around a bug in MSVC 8.0,
   // which causes RhsContainer to be a const type sometimes (e.g. when
   // rhs_container is a const int[]).
   typedef GTEST_REMOVE_CONST_(RhsContainer) RawRhsContainer;
   // RhsView allows the same code to handle RhsContainer being a
   // STL-style container and it being a native C-style array.
   typedef typename internal::StlContainerView<RawRhsContainer> RhsView;
   typedef typename RhsView::type RhsStlContainer;
   typedef typename RhsStlContainer::value_type Second;
   const RhsStlContainer& rhs_stl_container =
       RhsView::ConstReference(rhs_container);
   // Create a matcher for each element in rhs_container.
   ::std::vector<internal::BoundSecondMatcher<Tuple2Matcher, Second> > matchers;
   for (typename RhsStlContainer::const_iterator it = rhs_stl_container.begin();
        it != rhs_stl_container.end(); ++it) {
     matchers.push_back(
         internal::MatcherBindSecond(tuple2_matcher, *it));
   }
   // Delegate the work to UnorderedElementsAreArray().
   return UnorderedElementsAreArray(matchers);
 }