YOUR NAME's CS132 programs: gen_gtest_pred_impl.GenerateHeader
def gen_gtest_pred_impl.GenerateHeader (n)
Given the maximum arity n, updates the header file that implements
the predicate assertions.
Definition at line 315 of file gen_gtest_pred_impl.py.
References GenerateFile(), HeaderPostamble(), HeaderPreamble(), ImplementationForArity(), and OneTo().
Referenced by GenerateUnitTest().
 def GenerateHeader(n):
   """Given the maximum arity n, updates the header file that implements
   the predicate assertions."""
   GenerateFile(HEADER,
                HeaderPreamble(n)
                + ''.join([ImplementationForArity(i) for i in OneTo(n)])
                + HeaderPostamble())