YOUR NAME's CS132 programs: testing::gmock_matchers_test::MATCHER_P
testing::gmock_matchers_test::MATCHER_P (FieldIIs , inner_matcher , "")
Definition at line 3184 of file gmock-matchers_test.cc.
References testing::_, Describe(), DescribeNegation(), EXPECT_EQ, EXPECT_THAT, EXPECT_TRUE, Explain(), testing::ExplainMatchResult(), testing::HasSubstr(), testing::gmock_matchers_test::Derived::i, testing::internal::IsNull(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), testing::Pointee(), and testing::internal::TEST().
{
   return ExplainMatchResult(inner_matcher, arg.i, result_listener);
 }