YOUR NAME's CS132 programs: testing::internal::TempDir
std::string testing::internal::TempDir ()
Definition at line 1058 of file gtest-port.cc.
References testing::internal::posix::GetEnv().
Referenced by CheckedDowncastToActualType(), and testing::TEST_F().
                     {
 #if GTEST_OS_WINDOWS_MOBILE
   return "\\temp\\";
 #elif GTEST_OS_WINDOWS
   const char* temp_dir = posix::GetEnv("TEMP");
   if (temp_dir == NULL || temp_dir[0] == '\0')
     return "\\temp\\";
   else if (temp_dir[strlen(temp_dir) - 1] == '\\')
     return temp_dir;
   else
     return std::string(temp_dir) + "\\";
 #elif GTEST_OS_LINUX_ANDROID
   return "/sdcard/";
 #else
   return "/tmp/";
 #endif  // GTEST_OS_WINDOWS_MOBILE
 }