YOUR NAME's CS132 programs: testing::internal::FormatForComparisonFailureMessage
template<typename T1 , typename T2 > std::string testing::internal::FormatForComparisonFailureMessage (const T1 & value, const T2 &)
Definition at line 349 of file gtest-printers.h.
Referenced by CmpHelperEQ(), CmpHelperEQFailure(), CmpHelperOpFailure(), and testing::gtest_printers_test::TEST().
{
   return FormatForComparison<T1, T2>::Format(value);
 }