YOUR NAME's CS132 programs: testing::TEST_F
testing::TEST_F (InitGoogleTestTest , ThrowOnFailureTrue)
Definition at line 6365 of file gtest_unittest.cc.
References testing::Flags::break_on_failure, testing::internal::FilePath::c_str(), EXPECT_TRUE, testing::Flags::Filter(), testing::Flags::filter, testing::internal::posix::FOpen(), testing::internal::FilePath::GenerateUniqueFileName(), testing::internal::GetCurrentExecutableName(), GTEST_FLAG_PREFIX_, GTEST_TEST_PARSING_FLAGS_, testing::Flags::list_tests, testing::internal::posix::RmDir(), testing::InitGoogleTestTest::SetUp(), testing::Test::TearDown(), testing::internal::TempDir(), testing::internal::TEST_F(), testdata_path_, and testing::Flags::ThrowOnFailure().
{
   const char* argv[] = {
     "foo.exe",
     "--gtest_throw_on_failure=1",
     NULL
   };
   const char* argv2[] = {
     "foo.exe",
     NULL
   };
   GTEST_TEST_PARSING_FLAGS_(argv, argv2, Flags::ThrowOnFailure(true), false);
 }