YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PointwiseTest , WorksForRhsNativeArray)
Definition at line 5476 of file gmock-matchers_test.cc.
References EXPECT_THAT, testing::Gt(), testing::Lt(), testing::Not(), testing::Pointwise(), and testing::internal::TEST().
{
   const int rhs[] = {1, 2, 3};
   vector<int> lhs;
   lhs.push_back(2);
   lhs.push_back(4);
   lhs.push_back(6);
   EXPECT_THAT(lhs, Pointwise(Gt(), rhs));
   EXPECT_THAT(lhs, Not(Pointwise(Lt(), rhs)));
 }