YOUR NAME's CS132 programs: testing::internal::GetElementOr
template<typename E > E testing::internal::GetElementOr (const std::vector< E > & v, int i, E default_value) inline
Definition at line 303 of file gtest-internal-inl.h.
Referenced by testing::internal::UnitTestImpl::GetMutableTestCase(), testing::internal::UnitTestImpl::GetTestCase(), testing::TestCase::GetTestInfo(), and operator<<().
{
   return (i < 0 || i >= static_cast<int>(v.size())) ? default_value : v[i];
 }