YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST
testing::gmock_generated_function_mockers_test::TEST (TemplateMockTest , Works)
Definition at line 416 of file gmock-generated-function-mockers_test.cc.
References testing::_, testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, testing::gmock_generated_function_mockers_test::StackInterface< T >::GetSize(), testing::gmock_generated_function_mockers_test::StackInterface< T >::GetTop(), testing::gmock_generated_function_mockers_test::StackInterface< T >::Pop(), testing::gmock_generated_function_mockers_test::StackInterface< T >::Push(), testing::Return(), and testing::ReturnRef().
{
   MockStack<int> mock;
   EXPECT_CALL(mock, GetSize())
       .WillOnce(Return(0))
       .WillOnce(Return(1))
       .WillOnce(Return(0));
   EXPECT_CALL(mock, Push(_));
   int n = 5;
   EXPECT_CALL(mock, GetTop())
       .WillOnce(ReturnRef(n));
   EXPECT_CALL(mock, Pop())
       .Times(AnyNumber());
   EXPECT_EQ(0, mock.GetSize());
   mock.Push(5);
   EXPECT_EQ(1, mock.GetSize());
   EXPECT_EQ(5, mock.GetTop());
   mock.Pop();
   EXPECT_EQ(0, mock.GetSize());
 }