YOUR NAME's CS132 programs: testing::Exactly
GTEST_API_ Cardinality testing::Exactly (int n)
Definition at line 154 of file gmock-cardinalities.cc.
References Between().
Referenced by testing::Cardinality::DescribeTo(), testing::internal::TypedExpectation< F >::Times(), and testing::internal::TypedExpectation< F >::WillOnce().
 { return Between(n, n); }