YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (ApiTest , TestCaseImmutableAccessorsWork)
Definition at line 147 of file gtest-unittest-api_test.cc.
References ASSERT_EQ, ASSERT_TRUE, testing::TestCase::disabled_test_count(), EXPECT_EQ, EXPECT_FALSE, EXPECT_STREQ, EXPECT_TRUE, testing::internal::UnitTestHelper::FindTestCase(), testing::internal::UnitTestHelper::GetSortedTests(), IsNull(), testing::TestCase::name(), testing::TestCase::should_run(), testing::TestCase::test_to_run_count(), testing::TestCase::total_test_count(), and testing::TestCase::type_param().
{
   const TestCase* test_case = UnitTestHelper::FindTestCase("ApiTest");
   ASSERT_TRUE(test_case != NULL);
   EXPECT_STREQ("ApiTest", test_case->name());
   EXPECT_TRUE(IsNull(test_case->type_param()));
   EXPECT_TRUE(test_case->should_run());
   EXPECT_EQ(1, test_case->disabled_test_count());
   EXPECT_EQ(3, test_case->test_to_run_count());
   ASSERT_EQ(4, test_case->total_test_count());
   const TestInfo** tests = UnitTestHelper::GetSortedTests(test_case);
   EXPECT_STREQ("DISABLED_Dummy1", tests[0]->name());
   EXPECT_STREQ("ApiTest", tests[0]->test_case_name());
   EXPECT_TRUE(IsNull(tests[0]->value_param()));
   EXPECT_TRUE(IsNull(tests[0]->type_param()));
   EXPECT_FALSE(tests[0]->should_run());
   EXPECT_STREQ("TestCaseDisabledAccessorsWork", tests[1]->name());
   EXPECT_STREQ("ApiTest", tests[1]->test_case_name());
   EXPECT_TRUE(IsNull(tests[1]->value_param()));
   EXPECT_TRUE(IsNull(tests[1]->type_param()));
   EXPECT_TRUE(tests[1]->should_run());
   EXPECT_STREQ("TestCaseImmutableAccessorsWork", tests[2]->name());
   EXPECT_STREQ("ApiTest", tests[2]->test_case_name());
   EXPECT_TRUE(IsNull(tests[2]->value_param()));
   EXPECT_TRUE(IsNull(tests[2]->type_param()));
   EXPECT_TRUE(tests[2]->should_run());
   EXPECT_STREQ("UnitTestImmutableAccessorsWork", tests[3]->name());
   EXPECT_STREQ("ApiTest", tests[3]->test_case_name());
   EXPECT_TRUE(IsNull(tests[3]->value_param()));
   EXPECT_TRUE(IsNull(tests[3]->type_param()));
   EXPECT_TRUE(tests[3]->should_run());
   delete[] tests;
   tests = NULL;
 #if GTEST_HAS_TYPED_TEST
   test_case = UnitTestHelper::FindTestCase("TestCaseWithCommentTest/0");
   ASSERT_TRUE(test_case != NULL);
   EXPECT_STREQ("TestCaseWithCommentTest/0", test_case->name());
   EXPECT_STREQ(GetTypeName<int>().c_str(), test_case->type_param());
   EXPECT_TRUE(test_case->should_run());
   EXPECT_EQ(0, test_case->disabled_test_count());
   EXPECT_EQ(1, test_case->test_to_run_count());
   ASSERT_EQ(1, test_case->total_test_count());
   tests = UnitTestHelper::GetSortedTests(test_case);
   EXPECT_STREQ("Dummy", tests[0]->name());
   EXPECT_STREQ("TestCaseWithCommentTest/0", tests[0]->test_case_name());
   EXPECT_TRUE(IsNull(tests[0]->value_param()));
   EXPECT_STREQ(GetTypeName<int>().c_str(), tests[0]->type_param());
   EXPECT_TRUE(tests[0]->should_run());
   delete[] tests;
 #endif  // GTEST_HAS_TYPED_TEST
 }