YOUR NAME's CS132 programs: testing::internal::FormatCompilerIndependentFileLocation
GTEST_API_::std::string testing::internal::FormatCompilerIndependentFileLocation (const char * file, int line)
Definition at line 898 of file gtest-port.cc.
References StreamableToString().
Referenced by FormatEpochTimeInMillisAsIso8601(), testing::internal::RE::PartialMatch(), and TEST().
{
   const std::string file_name(file == NULL ? kUnknownFile : file);
   if (line < 0)
     return file_name;
   else
     return file_name + ":" + StreamableToString(line);
 }