YOUR NAME's CS132 programs: testing::internal::CmpHelperSTRNE
AssertionResult testing::internal::CmpHelperSTRNE (const char * s1_expression, const char * s2_expression, const wchar_t * s1, const wchar_t * s2)
Definition at line 1885 of file gtest.cc.
References testing::AssertionFailure(), testing::AssertionSuccess(), and testing::PrintToString().
{
   if (!String::WideCStringEquals(s1, s2)) {
     return AssertionSuccess();
   }
   return AssertionFailure() << "Expected: (" << s1_expression << ") != ("
                             << s2_expression << "), actual: "
                             << PrintToString(s1)
                             << " vs " << PrintToString(s2);
 }