YOUR NAME's CS132 programs: pump.ParseToAST
def pump.ParseToAST (pump_src_text)
Convert the given Pump source text into an AST.
Definition at line 577 of file pump.py.
References ParseCodeNode(), and Tokenize().
Referenced by ConvertFromPumpSource().
 def ParseToAST(pump_src_text):
   """Convert the given Pump source text into an AST."""
   tokens = list(Tokenize(pump_src_text))
   code_node = ParseCodeNode(tokens)
   return code_node