YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (BeginEndDistanceIsTest , CanDescribeSelf)
Definition at line 4603 of file gmock-matchers_test.cc.
References testing::BeginEndDistanceIs(), Describe(), DescribeNegation(), and EXPECT_EQ.
{
   Matcher<vector<int> > m = BeginEndDistanceIs(2);
   EXPECT_EQ("distance between begin() and end() is equal to 2", Describe(m));
   EXPECT_EQ("distance between begin() and end() isn't equal to 2",
             DescribeNegation(m));
 }