YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (AnyOfTest , ExplainsResult)
Definition at line 2385 of file gmock-matchers_test.cc.
References testing::AnyOf(), EXPECT_EQ, Explain(), GreaterThan(), testing::Gt(), and testing::Lt().
{
   Matcher<int> m;
   // Failed match.  Both matchers need to explain.  The second
   // matcher doesn't give an explanation, so only the first matcher's
   // explanation is printed.
   m = AnyOf(GreaterThan(10), Lt(0));
   EXPECT_EQ("which is 5 less than 10", Explain(m, 5));
   // Failed match.  Both matchers need to explain.
   m = AnyOf(GreaterThan(10), GreaterThan(20));
   EXPECT_EQ("which is 5 less than 10, and which is 15 less than 20",
             Explain(m, 5));
   // Failed match.  All matchers need to explain.  The second
   // matcher doesn't given an explanation.
   m = AnyOf(GreaterThan(10), Gt(20), GreaterThan(30));
   EXPECT_EQ("which is 5 less than 10, and which is 25 less than 30",
             Explain(m, 5));
   // Failed match.  All matchers need to explain.
   m = AnyOf(GreaterThan(10), GreaterThan(20), GreaterThan(30));
   EXPECT_EQ("which is 5 less than 10, and which is 15 less than 20, "
             "and which is 25 less than 30",
             Explain(m, 5));
   // Successful match.  The first matcher, which succeeded, needs to
   // explain.
   m = AnyOf(GreaterThan(10), GreaterThan(20));
   EXPECT_EQ("which is 5 more than 10", Explain(m, 15));
   // Successful match.  The second matcher, which succeeded, needs to
   // explain.  Since it doesn't given an explanation, nothing is
   // printed.
   m = AnyOf(GreaterThan(10), Lt(30));
   EXPECT_EQ("", Explain(m, 0));
   // Successful match.  The second matcher, which succeeded, needs to
   // explain.
   m = AnyOf(GreaterThan(30), GreaterThan(20));
   EXPECT_EQ("which is 5 more than 20", Explain(m, 25));
 }