YOUR NAME's CS132 programs: testing::gmock_matchers_test::Explain
template<typename MatcherType , typename Value > string testing::gmock_matchers_test::Explain (const MatcherType & m, const Value & x)
Definition at line 218 of file gmock-matchers_test.cc.
References testing::ExplainMatchResult(), and testing::StringMatchResultListener::str().
Referenced by MATCHER_P(), TEST(), and TEST_F().
{
   StringMatchResultListener listener;
   ExplainMatchResult(m, x, &listener);
   return listener.str();
 }