YOUR NAME's CS132 programs: testing::internal::CheckedDowncastToActualType
template<class Derived , class Base > Derived* testing::internal::CheckedDowncastToActualType (Base * base)
Definition at line 1398 of file gtest-port.h.
References CaptureStderr(), CaptureStdout(), GetArgvs(), GetCapturedStderr(), GetCapturedStdout(), GetFileSize(), GTEST_API_, GTEST_CHECK_, GTEST_CHECK_POSIX_SUCCESS_, GTEST_DISALLOW_COPY_AND_ASSIGN_, ReadEntireFile(), gtest_break_on_failure_unittest::Run(), and TempDir().
{
 #if GTEST_HAS_RTTI
   GTEST_CHECK_(typeid(*base) == typeid(Derived));
 #endif
 #if GTEST_HAS_DOWNCAST_
   return ::down_cast<Derived*>(base);
 #elif GTEST_HAS_RTTI
   return dynamic_cast<Derived*>(base);  // NOLINT
 #else
   return static_cast<Derived*>(base);  // Poor man's downcast.
 #endif
 }