YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (FormatCompilerIndependentFileLocationTest , FormatsUknownFileAndLine)
Definition at line 303 of file gtest-port_test.cc.
References ASSERT_EQ, EXPECT_EQ, FormatCompilerIndependentFileLocation(), GetThreadCount(), testing::internal::Mutex::Lock(), TEST(), and testing::internal::Mutex::Unlock().
{
   EXPECT_EQ("unknown file", FormatCompilerIndependentFileLocation(NULL, -1));
 }