YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (EachTest , AcceptsMatcher)
Definition at line 5396 of file gmock-matchers_test.cc.
References testing::Each(), EXPECT_THAT, testing::Gt(), and testing::Not().
{
   const int a[] = {1, 2, 3};
   EXPECT_THAT(a, Each(Gt(0)));
   EXPECT_THAT(a, Not(Each(Gt(1))));
 }