YOUR NAME's CS132 programs: testing::internal::UniversalPrint
template<typename T > void testing::internal::UniversalPrint (const T & value, ::std::ostream * os)
Definition at line 852 of file gtest-printers.h.
References testing::gtest_printers_test::Print().
Referenced by DefaultPrintTo(), testing::internal::StrEqualityMatcher< StringType >::DescribeNegationTo(), testing::internal::HasSubstrMatcher< StringType >::DescribeNegationTo(), testing::internal::StartsWithMatcher< StringType >::DescribeNegationTo(), testing::internal::EndsWithMatcher< StringType >::DescribeNegationTo(), testing::internal::ContainerEqMatcher< Container >::DescribeNegationTo(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::DescribeNegationTo(), testing::internal::HasSubstrMatcher< StringType >::DescribeTo(), testing::internal::StartsWithMatcher< StringType >::DescribeTo(), testing::internal::EndsWithMatcher< StringType >::DescribeTo(), testing::internal::ContainerEqMatcher< Container >::DescribeTo(), testing::internal::TuplePrefix< N >::ExplainMatchFailuresTo(), testing::internal::ContainerEqMatcher< Container >::MatchAndExplain(), testing::internal::WhenSortedByMatcher< Comparator, ContainerMatcher >::Impl< LhsContainer >::MatchAndExplain(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::Impl< LhsContainer >::MatchAndExplain(), MatchPrintAndExplain(), testing::internal::ComparisonBase< LtMatcher< Rhs >, Rhs, AnyLt >::operator Matcher< Lhs >(), testing::internal::BoundSecondMatcher< Tuple2Matcher, Second >::operator=(), testing::internal::UniversalPrinter< T & >::Print(), testing::internal::UniversalTersePrinter< T >::Print(), testing::internal::UniversalTersePrinter< T & >::Print(), testing::internal::UniversalTersePrinter< const char * >::Print(), testing::internal::UniversalTersePrinter< char * >::Print(), PrintRawArrayTo(), and testing::gtest_printers_test::TEST().
{
   // A workarond for the bug in VC++ 7.1 that prevents us from instantiating
   // UniversalPrinter with T directly.
   typedef T T1;
   UniversalPrinter<T1>::Print(value, os);
 }