YOUR NAME's CS132 programs: testing::internal::Assert
template<typename From , typename To > void testing::internal::Assert (bool condition, const char * file, int line) inline
Definition at line 288 of file gmock-internal-utils.h.
Referenced by testing::internal::UntypedOnCallSpecBase::AssertSpecProperty(), testing::internal::ExpectationBase::AssertSpecProperty(), testing::internal::BuiltInDefaultValueGetter< T, false >::Get(), testing::internal::UntypedFunctionMockerBase::GetHandleOf(), Invalid(), testing::internal::UntypedFunctionMockerBase::MockObject(), testing::internal::UntypedFunctionMockerBase::Name(), testing::Action< InnerFunctionType >::Perform(), and testing::internal::FunctionMockerBase< R(A1, A2)>::PerformDefaultAction().
{
   Assert(condition, file, line, "Assertion failed.");
 }