YOUR NAME's CS132 programs: testing::internal::InitGoogleMockImpl
template<typename CharType > void testing::internal::InitGoogleMockImpl (int * argc, CharType ** argv)
Definition at line 128 of file gmock.cc.
References GMOCK_FLAG, testing::InitGoogleTest(), and StreamableToString().
Referenced by testing::InitGoogleMock().
{
   // Makes sure Google Test is initialized.  InitGoogleTest() is
   // idempotent, so it's fine if the user has already called it.
   InitGoogleTest(argc, argv);
   if (*argc <= 0) return;
   for (int i = 1; i != *argc; i++) {
     const std::string arg_string = StreamableToString(argv[i]);
     const char* const arg = arg_string.c_str();
     // Do we see a Google Mock flag?
     if (ParseGoogleMockBoolFlag(arg, "catch_leaked_mocks",
                                 &GMOCK_FLAG(catch_leaked_mocks)) ||
         ParseGoogleMockStringFlag(arg, "verbose", &GMOCK_FLAG(verbose))) {
       // Yes.  Shift the remainder of the argv list left by one.  Note
       // that argv has (*argc + 1) elements, the last one always being
       // NULL.  The following loop moves the trailing NULL element as
       // well.
       for (int j = i; j != *argc; j++) {
         argv[j] = argv[j + 1];
       }
       // Decrements the argument count.
       (*argc)--;
       // We also need to decrement the iterator as we just removed
       // an element.
       i--;
     }
   }
 }