YOUR NAME's CS132 programs: testing::internal::GetThreadCount
size_t testing::internal::GetThreadCount ()
Definition at line 169 of file gtest-port.cc.
References ADD_FAILURE, testing::internal::Mutex::AssertHeld(), EXPECT_TRUE, testing::internal::RE::FullMatch(), GTEST_CHECK_, GTEST_DISALLOW_COPY_AND_ASSIGN_, testing::internal::Mutex::Lock(), testing::internal::Mutex::Mutex(), testing::internal::RE::PartialMatch(), testing::internal::posix::StrDup(), testing::internal::Mutex::Unlock(), and testing::internal::RE::~RE().
Referenced by testing::internal::ThreadLocal< testing::TestPartResultReporterInterface * >::set(), and TEST().
{
   // There's no portable way to detect the number of threads, so we just
   // return 0 to indicate that we cannot detect it.
   return 0;
 }