YOUR NAME's CS132 programs: testing::MakePolymorphicMatcher
template<class Impl > PolymorphicMatcher<Impl> testing::MakePolymorphicMatcher (const Impl & impl) inline
Definition at line 496 of file gmock-matchers.h.
Referenced by ContainerEq(), ContainsRegex(), testing::gmock_matchers_test::DivisibleBy(), EndsWith(), Field(), HasSubstr(), testing::gmock_matchers_test::IsHalfOf(), IsNull(), MatchesRegex(), NotNull(), testing::gmock_matchers_test::PolymorphicIsEven(), Property(), testing::gmock_matchers_test::ReferencesBarOrIsZero(), StartsWith(), StrCaseEq(), StrCaseNe(), StrEq(), StrNe(), Truly(), and WhenDynamicCastTo().
{
   return PolymorphicMatcher<Impl>(impl);
 }