YOUR NAME's CS132 programs: testing::Property
template<typename Class , typename PropertyType , typename PropertyMatcher > PolymorphicMatcher< internal::PropertyMatcher<Class, PropertyType> > testing::Property (PropertyType(Class::*)() const property, const PropertyMatcher & matcher) inline
Definition at line 3913 of file gmock-matchers.h.
References GTEST_REFERENCE_TO_CONST_, MakePolymorphicMatcher(), and MatcherCast().
Referenced by TEST(), and testing::gmock_matchers_test::TEST().
{
   return MakePolymorphicMatcher(
       internal::PropertyMatcher<Class, PropertyType>(
           property,
           MatcherCast<GTEST_REFERENCE_TO_CONST_(PropertyType)>(matcher)));
   // The call to MatcherCast() is required for supporting inner
   // matchers of compatible types.  For example, it allows
   //   Property(&Foo::bar, m)
   // to compile where bar() returns an int32 and m is a matcher for int64.
 }