YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (MatcherAssertionTest , WorksForMonomorphicMatcher)
Definition at line 2684 of file gmock-matchers_test.cc.
References ASSERT_THAT, testing::EndsWith(), EXPECT_NONFATAL_FAILURE, EXPECT_THAT, testing::Gt(), OfType(), and testing::StartsWith().
{
   Matcher<const char*> starts_with_he = StartsWith("he");
   ASSERT_THAT("hello", starts_with_he);
   Matcher<const string&> ends_with_ok = EndsWith("ok");
   ASSERT_THAT("book", ends_with_ok);
   const string bad = "bad";
   EXPECT_NONFATAL_FAILURE(EXPECT_THAT(bad, ends_with_ok),
                           "Value of: bad\n"
                           "Expected: ends with \"ok\"\n"
                           "  Actual: \"bad\"");
   Matcher<int> is_greater_than_5 = Gt(5);
   EXPECT_NONFATAL_FAILURE(EXPECT_THAT(5, is_greater_than_5),
                           "Value of: 5\n"
                           "Expected: is > 5\n"
                           "  Actual: 5" + OfType("int"));
 }