YOUR NAME's CS132 programs: testing::internal::ConvertIdentifierNameToWords
GTEST_API_ string testing::internal::ConvertIdentifierNameToWords (const char * id_name)
Definition at line 54 of file gmock-internal-utils.cc.
References IsAlNum(), IsAlpha(), IsDigit(), IsLower(), IsUpper(), and ToLower().
Referenced by FormatMatcherDescription().
{
   string result;
   char prev_char = '\0';
   for (const char* p = id_name; *p != '\0'; prev_char = *(p++)) {
     // We don't care about the current locale as the input is
     // guaranteed to be a valid C++ identifier name.
     const bool starts_new_word = IsUpper(*p) ||
         (!IsAlpha(prev_char) && IsLower(*p)) ||
         (!IsDigit(prev_char) && IsDigit(*p));
     if (IsAlNum(*p)) {
       if (starts_new_word && result != "")
         result += ' ';
       result += ToLower(*p);
     }
   }
   return result;
 }