YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST
testing::gmock_generated_function_mockers_test::TEST (MockFunctionTest , WorksFor10Arguments)
Definition at line 588 of file gmock-generated-function-mockers_test.cc.
References testing::_, EXPECT_CALL, EXPECT_EQ, testing::gmock_matchers_test::foo, testing::Return(), testing::ReturnRef(), and TEST().
{
   MockFunction<int(bool a0, char a1, int a2, int a3, int a4,
                    int a5, int a6, char a7, int a8, bool a9)> foo;
   EXPECT_CALL(foo, Call(_, 'a', _, _, _, _, _, _, _, _))
       .WillOnce(Return(1))
       .WillOnce(Return(2));
   EXPECT_EQ(1, foo.Call(false, 'a', 0, 0, 0, 0, 0, 'b', 0, true));
   EXPECT_EQ(2, foo.Call(true, 'a', 0, 0, 0, 0, 0, 'b', 1, false));
 }