YOUR NAME's CS132 programs: testing::internal::StreamableToString
template<typename T > std::string testing::internal::StreamableToString (const T & streamable)
Definition at line 243 of file gtest-message.h.
Referenced by FormatCompilerIndependentFileLocation(), FormatEpochTimeInMillisAsIso8601(), FormatFileLocation(), testing::TestCase::GetTestInfo(), InitGoogleMockImpl(), InitGoogleTestImpl(), testing::internal::FilePath::MakeFileName(), testing::internal::PrettyUnitTestResultPrinter::OnTestCaseEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestEnd(), testing::internal::PrettyUnitTestResultPrinter::OnTestIterationEnd(), ParseGoogleTestFlagsOnlyImpl(), testing::TEST(), and testing::internal::TestResultAccessor::test_part_results().
{
   return (Message() << streamable).GetString();
 }