YOUR NAME's CS132 programs: testing::Invoke
template<typename FunctionImpl > PolymorphicAction<internal::InvokeAction<FunctionImpl> > testing::Invoke (FunctionImpl function_impl)
Definition at line 114 of file gmock-more-actions.h.
References MakePolymorphicAction().
Referenced by testing::internal::ExpectationTester::SetCallCount(), testing::gmock_nice_strict_test::MockBar::str(), testing::gmock_more_actions_test::TEST(), testing::gmock_nice_strict_test::TEST(), testing::gmock_generated_actions_test::TEST(), and TEST().
{
   return MakePolymorphicAction(
       internal::InvokeAction<FunctionImpl>(function_impl));
 }