YOUR NAME's CS132 programs: testing::gmock_more_actions_test::TEST
testing::gmock_more_actions_test::TEST (InvokeTest , FunctionWithUnusedParameters)
Definition at line 327 of file gmock-more-actions_test.cc.
References EXPECT_EQ, testing::Invoke(), std::tr1::make_tuple(), testing::Action< F >::Perform(), and SumOfFirst2().
{
   Action<int(int, int, double, const string&)> a1 =
       Invoke(SumOfFirst2);
   string s("hi");
   EXPECT_EQ(12, a1.Perform(
     tuple<int, int, double, const string&>(10, 2, 5.6, s)));
   Action<int(int, int, bool, int*)> a2 =
       Invoke(SumOfFirst2);
   EXPECT_EQ(23, a2.Perform(make_tuple(20, 3, true, static_cast<int*>(NULL))));
 }