YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST
testing::gmock_generated_function_mockers_test::TEST (TemplateMockTest , MethodWithCommaInReturnTypeWorks)
Definition at line 438 of file gmock-generated-function-mockers_test.cc.
References testing::_, testing::AnyNumber(), EXPECT_CALL, EXPECT_EQ, GTEST_DISALLOW_COPY_AND_ASSIGN_, MOCK_CONST_METHOD0_T_WITH_CALLTYPE, MOCK_METHOD0_T_WITH_CALLTYPE, MOCK_METHOD1_T_WITH_CALLTYPE, testing::Return(), testing::ReturnRef(), and TEST().
{
   MockStack<int> mock;
   const std::map<int, int> a_map;
   EXPECT_CALL(mock, ReturnTypeWithComma())
       .WillOnce(Return(a_map));
   EXPECT_CALL(mock, ReturnTypeWithComma(1))
       .WillOnce(Return(a_map));
   EXPECT_EQ(a_map, mock.ReturnTypeWithComma());
   EXPECT_EQ(a_map, mock.ReturnTypeWithComma(1));
 }