YOUR NAME's CS132 programs: testing::StaticAssertTypeEq
template<typename T1 , typename T2 > bool testing::StaticAssertTypeEq ()
Definition at line 2150 of file gtest.h.
Referenced by testing::internal::StlContainerView< RawContainer >::ConstReference(), testing::internal::ContainerEqMatcher< Container >::ContainerEqMatcher(), testing::internal::PointwiseMatcher< TupleMatcher, RhsContainer >::PointwiseMatcher(), and testing::internal::TEST().
{
   (void)internal::StaticAssertTypeEqHelper<T1, T2>();
   return true;
 }