YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PropertyForPointerTest , CanExplainMatchResult)
Definition at line 3782 of file gmock-matchers_test.cc.
References EXPECT_EQ, Explain(), testing::Ge(), GreaterThan(), OfType(), testing::Property(), and testing::gmock_matchers_test::AClass::set_n().
{
   Matcher<const AClass*> m = Property(&AClass::n, Ge(0));
   AClass a;
   a.set_n(1);
   EXPECT_EQ("", Explain(m, static_cast<const AClass*>(NULL)));
   EXPECT_EQ(
       "which points to an object whose given property is 1" + OfType("int"),
       Explain(m, &a));
   m = Property(&AClass::n, GreaterThan(0));
   EXPECT_EQ("which points to an object whose given property is 1" +
             OfType("int") + ", which is 1 more than 0",
             Explain(m, &a));
 }