YOUR NAME's CS132 programs: testing::gmock_generated_function_mockers_test::TEST_F
testing::gmock_generated_function_mockers_test::TEST_F (FunctionMockerTest , MocksVoidFunction)
Definition at line 191 of file gmock-generated-function-mockers_test.cc.
References EXPECT_CALL, testing::Lt(), and testing::gmock_generated_function_mockers_test::FooInterface::VoidReturning().
Referenced by TEST_F().
{
   EXPECT_CALL(mock_foo_, VoidReturning(Lt(100)));
   foo_->VoidReturning(0);
 }