YOUR NAME's CS132 programs: testing::internal::ParseBoolFlag
bool testing::internal::ParseBoolFlag (const char * str, const char * flag, bool * value)
Definition at line 5053 of file gtest.cc.
References ParseFlagValue().
Referenced by ParseGoogleTestFlag(), and ParseGoogleTestFlagsOnlyImpl().
{
   // Gets the value of the flag as a string.
   const char* const value_str = ParseFlagValue(str, flag, true);
   // Aborts if the parsing failed.
   if (value_str == NULL) return false;
   // Converts the string value to a bool.
   *value = !(*value_str == '0' || *value_str == 'f' || *value_str == 'F');
   return true;
 }