YOUR NAME's CS132 programs: testing::internal::PrintRawArrayTo
template<typename T > void testing::internal::PrintRawArrayTo (const T a[], size_t count, ::std::ostream * os)
Definition at line 548 of file gtest-printers.h.
References count, GTEST_API_, PrintStringTo(), PrintTo(), and UniversalPrint().
Referenced by UniversalPrintArray().
{
   UniversalPrint(a[0], os);
   for (size_t i = 1; i != count; i++) {
     *os << ", ";
     UniversalPrint(a[i], os);
   }
 }