YOUR NAME's CS132 programs: testing::AddGlobalTestEnvironment
Environment* testing::AddGlobalTestEnvironment (Environment * env) inline
Definition at line 1350 of file gtest.h.
References testing::UnitTest::GetInstance(), GTEST_API_, and InitGoogleTest().
Referenced by main().
{
   return UnitTest::GetInstance()->AddEnvironment(env);
 }