YOUR NAME's CS132 programs: testing::internal::Shuffle
template<typename E > void testing::internal::Shuffle (internal::Random * random, std::vector< E > * v) inline
Definition at line 333 of file gtest-internal-inl.h.
References ShuffleRange().
Referenced by testing::TestCase::GetTestInfo(), and operator<<().
{
   ShuffleRange(random, 0, static_cast<int>(v->size()), v);
 }