YOUR NAME's CS132 programs: testing::internal::CopyArray
template<typename T , typename U , size_t N> void testing::internal::CopyArray (const T(&) from[N], U(*) to[N]) inline
Definition at line 1004 of file gtest-internal.h.
Referenced by ArrayAwareFind(), CopyArray(), and testing::internal::NativeArray< Element >::operator==().
{
   internal::CopyArray(from, N, *to);
 }