YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (StreamlikeTest , Iteration)
Definition at line 4572 of file gmock-matchers_test.cc.
References testing::gmock_matchers_test::Streamlike< T >::begin(), testing::BeginEndDistanceIs(), testing::gmock_matchers_test::Streamlike< T >::end(), EXPECT_EQ, EXPECT_THAT, testing::Not(), SCOPED_TRACE, and testing::internal::TEST().
{
   const int a[5] = {2, 1, 4, 5, 3};
   Streamlike<int> s(a, a + 5);
   Streamlike<int>::const_iterator it = s.begin();
   const int* ip = a;
   while (it != s.end()) {
     SCOPED_TRACE(ip - a);
     EXPECT_EQ(*ip++, *it++);
   }
 }