YOUR NAME's CS132 programs: gtest_break_on_failure_unittest.Run
def gtest_break_on_failure_unittest.Run (command)
Runs a command; returns 1 if it was killed by a signal, or 0 otherwise.
Definition at line 80 of file gtest_break_on_failure_unittest.py.
Referenced by testing::internal.CheckedDowncastToActualType(), testing::Test.HasFailure(), gtest_break_on_failure_unittest.GTestBreakOnFailureUnitTest.RunAndVerify(), and testing::internal.TransformTupleValues().
 def Run(command):
   """Runs a command; returns 1 if it was killed by a signal, or 0 otherwise."""
   p = gtest_test_utils.Subprocess(command, env=environ)
   if p.terminated_by_signal:
     return 1
   else:
     return 0
 # The tests.