YOUR NAME's CS132 programs: testing::internal::FindMaxBipartiteMatching
GTEST_API_ ElementMatcherPairs testing::internal::FindMaxBipartiteMatching (const MatchMatrix & g)
Definition at line 308 of file gmock-matchers.cc.
References testing::internal::MaxBipartiteMatchState::Compute(), and gen_gtest_pred_impl::Iter().
Referenced by FindPairing(), and testing::gmock_matchers_test::TEST_P().
{
   return MaxBipartiteMatchState(g).Compute();
 }