YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , PerformanceHalfStrict)
Definition at line 4862 of file gmock-matchers_test.cc.
References testing::_, EXPECT_TRUE, testing::ExplainMatchResult(), testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
{
   std::vector<int> s;
   std::vector<Matcher<int> > mv;
   for (int i = 0; i < 100; ++i) {
     s.push_back(i);
     if (i & 1) {
       mv.push_back(_);
     } else {
       mv.push_back(i);
     }
   }
   StringMatchResultListener listener;
   EXPECT_TRUE(ExplainMatchResult(UnorderedElementsAreArray(mv),
                                  s, &listener)) << listener.str();
 }