YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (TrulyTest , CanDescribeSelf)
Definition at line 2499 of file gmock-matchers_test.cc.
References Describe(), EXPECT_EQ, IsPositive(), and testing::Truly().
{
   Matcher<double> m = Truly(IsPositive);
   EXPECT_EQ("satisfies the given predicate",
             Describe(m));
 }