YOUR NAME's CS132 programs: std::tr1::GTEST_BY_REF_
template<int k, GTEST_10_TYPENAMES_(T) > std::tr1::GTEST_BY_REF_ (GTEST_TUPLE_ELEMENT_(k,GTEST_10_TUPLE_(T))) const
Definition at line 936 of file gtest-tuple.h.
Referenced by GTEST_1_TUPLE_(), GTEST_2_TUPLE_(), GTEST_3_TUPLE_(), GTEST_4_TUPLE_(), GTEST_5_TUPLE_(), GTEST_6_TUPLE_(), GTEST_7_TUPLE_(), GTEST_8_TUPLE_(), and GTEST_9_TUPLE_().
{
   return gtest_internal::Get<k>::ConstField(t);
 }