YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (WhenSortedTest , WorksForNonEmptyContainer)
Definition at line 4431 of file gmock-matchers_test.cc.
References testing::ElementsAre(), EXPECT_THAT, testing::Not(), and testing::WhenSorted().
{
   list<string> words;
   words.push_back("3");
   words.push_back("1");
   words.push_back("2");
   words.push_back("2");
   EXPECT_THAT(words, WhenSorted(ElementsAre("1", "2", "2", "3")));
   EXPECT_THAT(words, Not(WhenSorted(ElementsAre("3", "1", "2", "2"))));
 }