YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_F
testing::gmock_matchers_test::TEST_F (UnorderedElementsAreTest , FailsWhenAnElementMatchesNoMatcher)
Definition at line 4816 of file gmock-matchers_test.cc.
References EXPECT_FALSE, testing::ExplainMatchResult(), GTEST_ARRAY_SIZE_, testing::StringMatchResultListener::str(), and testing::UnorderedElementsAreArray().
{
   const int a[] = {1, 2, 3};
   std::vector<int> s(a, a + GTEST_ARRAY_SIZE_(a));
   std::vector<Matcher<int> > mv;
   mv.push_back(1);
   mv.push_back(2);
   mv.push_back(2);
   // The element with value '3' matches nothing: fail fast.
   StringMatchResultListener listener;
   EXPECT_FALSE(ExplainMatchResult(UnorderedElementsAreArray(mv),
                                   s, &listener)) << listener.str();
 }