YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (PairTest , CanExplainMatchResultTo)
Definition at line 1381 of file gmock-matchers_test.cc.
References EXPECT_EQ, Explain(), GreaterThan(), and testing::Pair().
{
   // If neither field matches, Pair() should explain about the first
   // field.
   const Matcher<pair<int, int> > m = Pair(GreaterThan(0), GreaterThan(0));
   EXPECT_EQ("whose first field does not match, which is 1 less than 0",
             Explain(m, make_pair(-1, -2)));
   // If the first field matches but the second doesn't, Pair() should
   // explain about the second field.
   EXPECT_EQ("whose second field does not match, which is 2 less than 0",
             Explain(m, make_pair(1, -2)));
   // If the first field doesn't match but the second does, Pair()
   // should explain about the first field.
   EXPECT_EQ("whose first field does not match, which is 1 less than 0",
             Explain(m, make_pair(-1, 2)));
   // If both fields match, Pair() should explain about them both.
   EXPECT_EQ("whose both fields match, where the first field is a value "
             "which is 1 more than 0, and the second field is a value "
             "which is 2 more than 0",
             Explain(m, make_pair(1, 2)));
   // If only the first match has an explanation, only this explanation should
   // be printed.
   const Matcher<pair<int, int> > explain_first = Pair(GreaterThan(0), 0);
   EXPECT_EQ("whose both fields match, where the first field is a value "
             "which is 1 more than 0",
             Explain(explain_first, make_pair(1, 0)));
   // If only the second match has an explanation, only this explanation should
   // be printed.
   const Matcher<pair<int, int> > explain_second = Pair(0, GreaterThan(0));
   EXPECT_EQ("whose both fields match, where the second field is a value "
             "which is 1 more than 0",
             Explain(explain_second, make_pair(0, 1)));
 }