YOUR NAME's CS132 programs: fuse_gmock_files.FuseGMockGTestAllCc
def fuse_gmock_files.FuseGMockGTestAllCc (gmock_root, output_dir)
Scans folder gmock_root to generate gmock-gtest-all.cc in output_dir.
Definition at line 204 of file fuse_gmock_files.py.
References FuseGMockAllCcToFile(), and GetGTestRootDir().
Referenced by FuseGMock().
 def FuseGMockGTestAllCc(gmock_root, output_dir):
   """Scans folder gmock_root to generate gmock-gtest-all.cc in output_dir."""
   output_file = file(os.path.join(output_dir, GMOCK_GTEST_ALL_CC_OUTPUT), 'w')
   # First, fuse gtest-all.cc into gmock-gtest-all.cc.
   gtest.FuseGTestAllCcToFile(GetGTestRootDir(gmock_root), output_file)
   # Next, append fused gmock-all.cc to gmock-gtest-all.cc.
   FuseGMockAllCcToFile(gmock_root, output_file)
   output_file.close()