YOUR NAME's CS132 programs: testing::internal::GetArgvs
const ::std::vector< testing::internal::string > & testing::internal::GetArgvs ()
Definition at line 389 of file gtest.cc.
References g_argvs.
Referenced by CheckedDowncastToActualType(), testing::internal::Random::Generate(), GetCurrentExecutableName(), and ReadEntireFile().
{
 #if defined(GTEST_CUSTOM_GET_ARGVS_)
   return GTEST_CUSTOM_GET_ARGVS_();
 #else  // defined(GTEST_CUSTOM_GET_ARGVS_)
   return g_argvs;
 #endif  // defined(GTEST_CUSTOM_GET_ARGVS_)
 }