YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST_P
testing::gmock_matchers_test::TEST_P (BipartiteTest , Exhaustive)
Definition at line 5102 of file gmock-matchers_test.cc.
References testing::internal::MatchMatrix::DebugString(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, FindBacktrackingMaxBPM(), testing::internal::FindMaxBipartiteMatching(), testing::internal::MatchMatrix::HasEdge(), testing::INSTANTIATE_TEST_CASE_P(), testing::internal::MatchMatrix::LhsSize(), testing::internal::MatchMatrix::NextGraph(), testing::PrintToString(), testing::internal::MatchMatrix::RhsSize(), and SCOPED_TRACE.
{
   int nodes = GetParam();
   MatchMatrix graph(nodes, nodes);
   do {
     ElementMatcherPairs matches =
         internal::FindMaxBipartiteMatching(graph);
     EXPECT_EQ(FindBacktrackingMaxBPM(graph).size(), matches.size())
         << "graph: " << graph.DebugString();
     // Check that all elements of matches are in the graph.
     // Check that elements of first and second are unique.
     std::vector<bool> seen_element(graph.LhsSize());
     std::vector<bool> seen_matcher(graph.RhsSize());
     SCOPED_TRACE(PrintToString(matches));
     for (size_t i = 0; i < matches.size(); ++i) {
       size_t ilhs = matches[i].first;
       size_t irhs = matches[i].second;
       EXPECT_TRUE(graph.HasEdge(ilhs, irhs));
       EXPECT_FALSE(seen_element[ilhs]);
       EXPECT_FALSE(seen_matcher[irhs]);
       seen_element[ilhs] = true;
       seen_matcher[irhs] = true;
     }
   } while (graph.NextGraph());
 }