YOUR NAME's CS132 programs: testing::internal::StringStreamToString
std::string testing::internal::StringStreamToString (::std::stringstream * stream)
Definition at line 1982 of file gtest.cc.
Referenced by CmpHelperFloatingPointEQ(), FloatingPointLE(), testing::Message::GetString(), testing::internal::XmlUnitTestResultPrinter::OnTestIterationEnd(), and WideStringToUtf8().
{
   const ::std::string& str = ss->str();
   const char* const start = str.c_str();
   const char* const end = start + str.length();
   std::string result;
   result.reserve(2 * (end - start));
   for (const char* ch = start; ch != end; ++ch) {
     if (*ch == '\0') {
       result += "\\0";  // Replaces NUL with "\\0";
     } else {
       result += *ch;
     }
   }
   return result;
 }