YOUR NAME's CS132 programs: testing::ContainerEq
template<typename Container > PolymorphicMatcher<internal::ContainerEqMatcher< GTEST_REMOVE_CONST_(Container)> > testing::ContainerEq (const Container & rhs) inline
Definition at line 4150 of file gmock-matchers.h.
References GTEST_REMOVE_CONST_, and MakePolymorphicMatcher().
Referenced by TEST(), and testing::gmock_matchers_test::TEST().
{
   // This following line is for working around a bug in MSVC 8.0,
   // which causes Container to be a const type sometimes.
   typedef GTEST_REMOVE_CONST_(Container) RawContainer;
   return MakePolymorphicMatcher(
       internal::ContainerEqMatcher<RawContainer>(rhs));
 }