YOUR NAME's CS132 programs: testing::AnyOf
template<typename M1 , typename M2 > internal::AnyOfResult2<M1, M2>::type testing::AnyOf (M1 m1, M2 m2) inline
Definition at line 1085 of file gmock-generated-matchers.h.
Referenced by AnyOf(), ExplainMatchResult(), TEST(), testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
                     {
   return typename internal::AnyOfResult2<M1, M2>::type(
       m1,
       m2);
 }