YOUR NAME's CS132 programs: testing::gtest_printers_test::HasPrefix
template<typename StringType > AssertionResult testing::gtest_printers_test::HasPrefix (const StringType & str, const StringType & prefix)
Definition at line 542 of file gtest-printers_test.cc.
References testing::AssertionFailure(), and testing::AssertionSuccess().
Referenced by TEST().
{
   if (str.find(prefix, 0) == 0)
     return AssertionSuccess();
   const bool is_wide_string = sizeof(prefix[0]) > 1;
   const char* const begin_string_quote = is_wide_string ? "L\"" : "\"";
   return AssertionFailure()
       << begin_string_quote << prefix << "\" is not a prefix of "
       << begin_string_quote << str << "\"\n";
 }