YOUR NAME's CS132 programs: testing::DoubleEq
internal::FloatingEqMatcher<double> testing::DoubleEq (double rhs) inline
Definition at line 3815 of file gmock-matchers.h.
Referenced by TEST(), testing::gmock_matchers_test::TEST(), and testing::gmock_matchers_test::TEST_F().
{
   return internal::FloatingEqMatcher<double>(rhs, false);
 }