YOUR NAME's CS132 programs: testing::internal::CaseInsensitiveCStringEquals
bool testing::internal::CaseInsensitiveCStringEquals (const char * lhs, const char * rhs) inline
Definition at line 1090 of file gmock-matchers.h.
References CaseInsensitiveCStringEquals().
Referenced by CmpHelperSTRCASEEQ(), CmpHelperSTRCASENE(), testing::internal::String::EndsWithCaseInsensitive(), and ShouldUseColor().
{
   return String::CaseInsensitiveCStringEquals(lhs, rhs);
 }