YOUR NAME's CS132 programs: testing::internal::PrintFullTestCommentIfPresent
void testing::internal::PrintFullTestCommentIfPresent (const TestInfo & test_info)
Definition at line 3009 of file gtest.cc.
References testing::TestInfo::type_param(), testing::TestCase::type_param(), and testing::TestInfo::value_param().
Referenced by testing::internal::PrettyUnitTestResultPrinter::OnEnvironmentsTearDownStart(), and testing::internal::PrettyUnitTestResultPrinter::OnTestEnd().
{
   const char* const type_param = test_info.type_param();
   const char* const value_param = test_info.value_param();
   if (type_param != NULL || value_param != NULL) {
     printf(", where ");
     if (type_param != NULL) {
       printf("%s = %s", kTypeParamLabel, type_param);
       if (value_param != NULL)
         printf(" and ");
     }
     if (value_param != NULL) {
       printf("%s = %s", kValueParamLabel, value_param);
     }
   }
 }