YOUR NAME's CS132 programs: testing::internal::CmpHelperEQFailure
template<typename T1 , typename T2 > AssertionResult testing::internal::CmpHelperEQFailure (const char * lhs_expression, const char * rhs_expression, const T1 & lhs, const T2 & rhs)
Definition at line 1375 of file gtest.h.
References EqFailure(), and FormatForComparisonFailureMessage().
Referenced by CmpHelperEQ().
{
   return EqFailure(lhs_expression,
                    rhs_expression,
                    FormatForComparisonFailureMessage(lhs, rhs),
                    FormatForComparisonFailureMessage(rhs, lhs),
                    false);
 }