YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (MakePolymorphicMatcherTest , ConstructsMatcherUsingNewAPI)
Definition at line 505 of file gmock-matchers_test.cc.
References Describe(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), testing::internal::MatcherBase< T >::Matches(), testing::Not(), and PolymorphicIsEven().
{
   // Using PolymorphicIsEven() as a Matcher<int>.
   const Matcher<int> m1 = PolymorphicIsEven();
   EXPECT_TRUE(m1.Matches(42));
   EXPECT_FALSE(m1.Matches(43));
   EXPECT_EQ("is even", Describe(m1));
   const Matcher<int> not_m1 = Not(m1);
   EXPECT_EQ("is odd", Describe(not_m1));
   EXPECT_EQ("% 2 == 0", Explain(m1, 42));
   // Using PolymorphicIsEven() as a Matcher<char>.
   const Matcher<char> m2 = PolymorphicIsEven();
   EXPECT_TRUE(m2.Matches('\x42'));
   EXPECT_FALSE(m2.Matches('\x43'));
   EXPECT_EQ("is even", Describe(m2));
   const Matcher<char> not_m2 = Not(m2);
   EXPECT_EQ("is odd", Describe(not_m2));
   EXPECT_EQ("% 2 == 0", Explain(m2, '\x42'));
 }