YOUR NAME's CS132 programs: testing::gmock_matchers_test::AnyOfMatches
void testing::gmock_matchers_test::AnyOfMatches (int num, const Matcher< int > & m)
Definition at line 2244 of file gmock-matchers_test.cc.
References Describe(), EXPECT_FALSE, EXPECT_TRUE, testing::internal::MatcherBase< T >::Matches(), and SCOPED_TRACE.
Referenced by TEST().
{
   SCOPED_TRACE(Describe(m));
   EXPECT_FALSE(m.Matches(0));
   for (int i = 1; i <= num; ++i) {
     EXPECT_TRUE(m.Matches(i));
   }
   EXPECT_FALSE(m.Matches(num + 1));
 }