YOUR NAME's CS132 programs: testing::gmock_matchers_test::TEST
testing::gmock_matchers_test::TEST (MatcherInterfaceTest , CanBeImplementedUsingNewAPI)
Definition at line 299 of file gmock-matchers_test.cc.
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, Explain(), testing::MakeMatcher(), and testing::internal::MatcherBase< T >::Matches().
{
   Matcher<int> m = MakeMatcher(new NewEvenMatcherImpl);
   EXPECT_TRUE(m.Matches(2));
   EXPECT_FALSE(m.Matches(3));
   EXPECT_EQ("value % 2 == 0", Explain(m, 2));
   EXPECT_EQ("value % 2 == 1", Explain(m, 3));
 }