YOUR NAME's CS132 programs: testing::internal::TEST
testing::internal::TEST (RegexEngineSelectionTest , SelectsCorrectRegexEngine)
Definition at line 384 of file gtest-port_test.cc.
References ASSERT_FALSE, EXPECT_FALSE, EXPECT_NONFATAL_FAILURE, EXPECT_PRED1, EXPECT_STREQ, EXPECT_TRUE, testing::internal::RE::FullMatch(), GTEST_USES_POSIX_RE, testing::internal::RE::PartialMatch(), testing::internal::RE::pattern(), TEST(), testing::TYPED_TEST(), and testing::TYPED_TEST_CASE().
{
 #if !GTEST_USES_PCRE
 # if GTEST_HAS_POSIX_RE
   EXPECT_TRUE(GTEST_USES_POSIX_RE);
 # else
   EXPECT_TRUE(GTEST_USES_SIMPLE_RE);
 # endif
 #endif  // !GTEST_USES_PCRE
 }