YOUR NAME's CS132 programs: testing::internal::Log
GTEST_API_ void testing::internal::Log (LogSeverity severity, const string & message, int stack_frames_to_skip)
Definition at line 131 of file gmock-internal-utils.cc.
References GetCurrentOsStackTraceExceptTop(), testing::UnitTest::GetInstance(), kWarning, LogIsVisible(), and gtest_output_test::message.
Referenced by testing::internal::ExpectationBase::CheckActionCountIfNotDone(), LogWithLocation(), ReportUninterestingCall(), and testing::internal::UntypedFunctionMockerBase::UntypedInvokeWith().
{
   if (!LogIsVisible(severity))
     return;
   // Ensures that logs from different threads don't interleave.
   MutexLock l(&g_log_mutex);
   // "using ::std::cout;" doesn't work with Symbian's STLport, where cout is a
   // macro.
   if (severity == kWarning) {
     // Prints a GMOCK WARNING marker to make the warnings easily searchable.
     std::cout << "\nGMOCK WARNING:";
   }
   // Pre-pends a new-line to message if it doesn't start with one.
   if (message.empty() || message[0] != '\n') {
     std::cout << "\n";
   }
   std::cout << message;
   if (stack_frames_to_skip >= 0) {
 #ifdef NDEBUG
     // In opt mode, we have to be conservative and skip no stack frame.
     const int actual_to_skip = 0;
 #else
     // In dbg mode, we can do what the caller tell us to do (plus one
     // for skipping this function's stack frame).
     const int actual_to_skip = stack_frames_to_skip + 1;
 #endif  // NDEBUG
     // Appends a new-line to message if it doesn't end with one.
     if (!message.empty() && *message.rbegin() != '\n') {
       std::cout << "\n";
     }
     std::cout << "Stack trace:\n"
          << ::testing::internal::GetCurrentOsStackTraceExceptTop(
              ::testing::UnitTest::GetInstance(), actual_to_skip);
   }
   std::cout << ::std::flush;
 }