YOUR NAME's CS132 programs: testing::internal::CmpHelperSTRCASEEQ
AssertionResult testing::internal::CmpHelperSTRCASEEQ (const char * s1_expression, const char * s2_expression, const char * s1, const char * s2)
Definition at line 1503 of file gtest.cc.
References testing::AssertionSuccess(), CaseInsensitiveCStringEquals(), EqFailure(), and testing::PrintToString().
{
   if (String::CaseInsensitiveCStringEquals(lhs, rhs)) {
     return AssertionSuccess();
   }
   return EqFailure(lhs_expression,
                    rhs_expression,
                    PrintToString(lhs),
                    PrintToString(rhs),
                    true);
 }